import type { SelectPrimitive } from "@govtech-bb/form-types";

// Centrally-managed country list: Barbados first, then Caribbean neighbours,
// then the rest of the world alphabetically, with "Other" last. Forms
// reference this bare (no options override) so updates here reach every form.
export const Country: SelectPrimitive = {
  fieldId: "country",
  label: "Country",
  htmlType: "select",
  options: [
    { label: "Barbados", value: "barbados" },
    { label: "Antigua and Barbuda", value: "antigua-and-barbuda" },
    { label: "Bahamas", value: "bahamas" },
    { label: "Belize", value: "belize" },
    { label: "Cuba", value: "cuba" },
    { label: "Dominica", value: "dominica" },
    { label: "Dominican Republic", value: "dominican-republic" },
    { label: "Grenada", value: "grenada" },
    { label: "Guyana", value: "guyana" },
    { label: "Haiti", value: "haiti" },
    { label: "Jamaica", value: "jamaica" },
    { label: "Saint Kitts and Nevis", value: "saint-kitts-and-nevis" },
    { label: "Saint Lucia", value: "saint-lucia" },
    {
      label: "Saint Vincent and the Grenadines",
      value: "saint-vincent-and-the-grenadines",
    },
    { label: "Suriname", value: "suriname" },
    { label: "Trinidad and Tobago", value: "trinidad-and-tobago" },
    { label: "Afghanistan", value: "afghanistan" },
    { label: "Albania", value: "albania" },
    { label: "Algeria", value: "algeria" },
    { label: "Andorra", value: "andorra" },
    { label: "Angola", value: "angola" },
    { label: "Argentina", value: "argentina" },
    { label: "Armenia", value: "armenia" },
    { label: "Australia", value: "australia" },
    { label: "Austria", value: "austria" },
    { label: "Azerbaijan", value: "azerbaijan" },
    { label: "Bangladesh", value: "bangladesh" },
    { label: "Belarus", value: "belarus" },
    { label: "Belgium", value: "belgium" },
    { label: "Bolivia", value: "bolivia" },
    { label: "Bosnia and Herzegovina", value: "bosnia-and-herzegovina" },
    { label: "Brazil", value: "brazil" },
    { label: "Bulgaria", value: "bulgaria" },
    { label: "Cambodia", value: "cambodia" },
    { label: "Cameroon", value: "cameroon" },
    { label: "Canada", value: "canada" },
    { label: "Chile", value: "chile" },
    { label: "China", value: "china" },
    { label: "Colombia", value: "colombia" },
    { label: "Costa Rica", value: "costa-rica" },
    { label: "Croatia", value: "croatia" },
    { label: "Czech Republic", value: "czech-republic" },
    { label: "Democratic Republic of the Congo", value: "dr-congo" },
    { label: "Denmark", value: "denmark" },
    { label: "Ecuador", value: "ecuador" },
    { label: "Egypt", value: "egypt" },
    { label: "Eritrea", value: "eritrea" },
    { label: "Estonia", value: "estonia" },
    { label: "Ethiopia", value: "ethiopia" },
    { label: "Finland", value: "finland" },
    { label: "France", value: "france" },
    { label: "Georgia", value: "georgia" },
    { label: "Germany", value: "germany" },
    { label: "Ghana", value: "ghana" },
    { label: "Greece", value: "greece" },
    { label: "Guatemala", value: "guatemala" },
    { label: "Honduras", value: "honduras" },
    { label: "Hungary", value: "hungary" },
    { label: "India", value: "india" },
    { label: "Indonesia", value: "indonesia" },
    { label: "Iran", value: "iran" },
    { label: "Iraq", value: "iraq" },
    { label: "Ireland", value: "ireland" },
    { label: "Israel", value: "israel" },
    { label: "Italy", value: "italy" },
    { label: "Japan", value: "japan" },
    { label: "Jordan", value: "jordan" },
    { label: "Kazakhstan", value: "kazakhstan" },
    { label: "Kenya", value: "kenya" },
    { label: "Kuwait", value: "kuwait" },
    { label: "Latvia", value: "latvia" },
    { label: "Lebanon", value: "lebanon" },
    { label: "Libya", value: "libya" },
    { label: "Lithuania", value: "lithuania" },
    { label: "Luxembourg", value: "luxembourg" },
    { label: "Malaysia", value: "malaysia" },
    { label: "Mexico", value: "mexico" },
    { label: "Moldova", value: "moldova" },
    { label: "Morocco", value: "morocco" },
    { label: "Mozambique", value: "mozambique" },
    { label: "Namibia", value: "namibia" },
    { label: "Nepal", value: "nepal" },
    { label: "Netherlands", value: "netherlands" },
    { label: "New Zealand", value: "new-zealand" },
    { label: "Nicaragua", value: "nicaragua" },
    { label: "Nigeria", value: "nigeria" },
    { label: "Norway", value: "norway" },
    { label: "Pakistan", value: "pakistan" },
    { label: "Panama", value: "panama" },
    { label: "Paraguay", value: "paraguay" },
    { label: "Peru", value: "peru" },
    { label: "Philippines", value: "philippines" },
    { label: "Poland", value: "poland" },
    { label: "Portugal", value: "portugal" },
    { label: "Romania", value: "romania" },
    { label: "Russia", value: "russia" },
    { label: "Saudi Arabia", value: "saudi-arabia" },
    { label: "Senegal", value: "senegal" },
    { label: "Serbia", value: "serbia" },
    { label: "Sierra Leone", value: "sierra-leone" },
    { label: "Singapore", value: "singapore" },
    { label: "Slovakia", value: "slovakia" },
    { label: "Somalia", value: "somalia" },
    { label: "South Africa", value: "south-africa" },
    { label: "South Korea", value: "south-korea" },
    { label: "Spain", value: "spain" },
    { label: "Sri Lanka", value: "sri-lanka" },
    { label: "Sudan", value: "sudan" },
    { label: "Sweden", value: "sweden" },
    { label: "Switzerland", value: "switzerland" },
    { label: "Syria", value: "syria" },
    { label: "Taiwan", value: "taiwan" },
    { label: "Tanzania", value: "tanzania" },
    { label: "Thailand", value: "thailand" },
    { label: "Tunisia", value: "tunisia" },
    { label: "Turkey", value: "turkey" },
    { label: "Uganda", value: "uganda" },
    { label: "Ukraine", value: "ukraine" },
    { label: "United Kingdom", value: "united-kingdom" },
    { label: "United States", value: "united-states" },
    { label: "Uruguay", value: "uruguay" },
    { label: "Uzbekistan", value: "uzbekistan" },
    { label: "Venezuela", value: "venezuela" },
    { label: "Vietnam", value: "vietnam" },
    { label: "Yemen", value: "yemen" },
    { label: "Zambia", value: "zambia" },
    { label: "Zimbabwe", value: "zimbabwe" },
    { label: "Other", value: "other" },
  ],
  multiple: false,
  validations: {
    required: {
      value: true,
      error: "Country is required",
    },
  },
};
