import { SelectPrimitive } from "@govtech-bb/form-types";

// Centrally-managed nationality list: Barbadian first, then Caribbean
// neighbours, then the rest of the world alphabetically, with "Other" last.
// Forms reference this bare (no options override) so updates here reach
// every form.
export const Nationality: SelectPrimitive = {
  fieldId: "nationality",
  htmlType: "select",
  label: "Nationality / Citizenship",
  options: [
    { label: "Barbadian", value: "barbadian" },
    { label: "Antiguan and Barbudan", value: "antiguan-and-barbudan" },
    { label: "Bahamian", value: "bahamian" },
    { label: "Belizean", value: "belizean" },
    { label: "Cuban", value: "cuban" },
    { label: "Dominican", value: "dominican" },
    { label: "Grenadian", value: "grenadian" },
    { label: "Guyanese", value: "guyanese" },
    { label: "Haitian", value: "haitian" },
    { label: "Jamaican", value: "jamaican" },
    { label: "Kittsian and Nevisian", value: "kittsian-and-nevisian" },
    { label: "Saint Lucian", value: "saint-lucian" },
    { label: "Surinamese", value: "surinamese" },
    {
      label: "Trinidadian and Tobagonian",
      value: "trinidadian-and-tobagonian",
    },
    { label: "Vincentian", value: "vincentian" },
    { label: "Afghan", value: "afghan" },
    { label: "Albanian", value: "albanian" },
    { label: "Algerian", value: "algerian" },
    { label: "American", value: "american" },
    { label: "Andorran", value: "andorran" },
    { label: "Angolan", value: "angolan" },
    { label: "Argentine", value: "argentine" },
    { label: "Armenian", value: "armenian" },
    { label: "Australian", value: "australian" },
    { label: "Austrian", value: "austrian" },
    { label: "Azerbaijani", value: "azerbaijani" },
    { label: "Bangladeshi", value: "bangladeshi" },
    { label: "Belarusian", value: "belarusian" },
    { label: "Belgian", value: "belgian" },
    { label: "Bolivian", value: "bolivian" },
    { label: "Bosnian", value: "bosnian" },
    { label: "Brazilian", value: "brazilian" },
    { label: "British", value: "british" },
    { label: "Bulgarian", value: "bulgarian" },
    { label: "Cambodian", value: "cambodian" },
    { label: "Cameroonian", value: "cameroonian" },
    { label: "Canadian", value: "canadian" },
    { label: "Chilean", value: "chilean" },
    { label: "Chinese", value: "chinese" },
    { label: "Colombian", value: "colombian" },
    { label: "Congolese", value: "congolese" },
    { label: "Costa Rican", value: "costa-rican" },
    { label: "Croatian", value: "croatian" },
    { label: "Czech", value: "czech" },
    { label: "Danish", value: "danish" },
    { label: "Dutch", value: "dutch" },
    { label: "Ecuadorian", value: "ecuadorian" },
    { label: "Egyptian", value: "egyptian" },
    { label: "Eritrean", value: "eritrean" },
    { label: "Estonian", value: "estonian" },
    { label: "Ethiopian", value: "ethiopian" },
    { label: "Filipino", value: "filipino" },
    { label: "Finnish", value: "finnish" },
    { label: "French", value: "french" },
    { label: "Georgian", value: "georgian" },
    { label: "German", value: "german" },
    { label: "Ghanaian", value: "ghanaian" },
    { label: "Greek", value: "greek" },
    { label: "Guatemalan", value: "guatemalan" },
    { label: "Honduran", value: "honduran" },
    { label: "Hungarian", value: "hungarian" },
    { label: "Indian", value: "indian" },
    { label: "Indonesian", value: "indonesian" },
    { label: "Iranian", value: "iranian" },
    { label: "Iraqi", value: "iraqi" },
    { label: "Irish", value: "irish" },
    { label: "Israeli", value: "israeli" },
    { label: "Italian", value: "italian" },
    { label: "Ivorian", value: "ivorian" },
    { label: "Japanese", value: "japanese" },
    { label: "Jordanian", value: "jordanian" },
    { label: "Kazakhstani", value: "kazakhstani" },
    { label: "Kenyan", value: "kenyan" },
    { label: "Korean", value: "korean" },
    { label: "Kuwaiti", value: "kuwaiti" },
    { label: "Latvian", value: "latvian" },
    { label: "Lebanese", value: "lebanese" },
    { label: "Libyan", value: "libyan" },
    { label: "Lithuanian", value: "lithuanian" },
    { label: "Luxembourgish", value: "luxembourgish" },
    { label: "Malaysian", value: "malaysian" },
    { label: "Maldivian", value: "maldivian" },
    { label: "Mexican", value: "mexican" },
    { label: "Moldovan", value: "moldovan" },
    { label: "Moroccan", value: "moroccan" },
    { label: "Mozambican", value: "mozambican" },
    { label: "Myanmar", value: "myanmar" },
    { label: "Namibian", value: "namibian" },
    { label: "Nepalese", value: "nepalese" },
    { label: "New Zealander", value: "new-zealander" },
    { label: "Nicaraguan", value: "nicaraguan" },
    { label: "Nigerian", value: "nigerian" },
    { label: "Norwegian", value: "norwegian" },
    { label: "Pakistani", value: "pakistani" },
    { label: "Panamanian", value: "panamanian" },
    { label: "Paraguayan", value: "paraguayan" },
    { label: "Peruvian", value: "peruvian" },
    { label: "Polish", value: "polish" },
    { label: "Portuguese", value: "portuguese" },
    { label: "Romanian", value: "romanian" },
    { label: "Russian", value: "russian" },
    { label: "Saudi Arabian", value: "saudi-arabian" },
    { label: "Senegalese", value: "senegalese" },
    { label: "Serbian", value: "serbian" },
    { label: "Sierra Leonean", value: "sierra-leonean" },
    { label: "Singaporean", value: "singaporean" },
    { label: "Slovak", value: "slovak" },
    { label: "Somali", value: "somali" },
    { label: "South African", value: "south-african" },
    { label: "Spanish", value: "spanish" },
    { label: "Sri Lankan", value: "sri-lankan" },
    { label: "Sudanese", value: "sudanese" },
    { label: "Swedish", value: "swedish" },
    { label: "Swiss", value: "swiss" },
    { label: "Syrian", value: "syrian" },
    { label: "Taiwanese", value: "taiwanese" },
    { label: "Tanzanian", value: "tanzanian" },
    { label: "Thai", value: "thai" },
    { label: "Tunisian", value: "tunisian" },
    { label: "Turkish", value: "turkish" },
    { label: "Ugandan", value: "ugandan" },
    { label: "Ukrainian", value: "ukrainian" },
    { label: "Uruguayan", value: "uruguayan" },
    { label: "Uzbekistani", value: "uzbekistani" },
    { label: "Venezuelan", value: "venezuelan" },
    { label: "Vietnamese", value: "vietnamese" },
    { label: "Yemeni", value: "yemeni" },
    { label: "Zambian", value: "zambian" },
    { label: "Zimbabwean", value: "zimbabwean" },
    { label: "Other", value: "other" },
  ],
  multiple: false,
  validations: {
    required: {
      value: true,
      error: "Nationality is required",
    },
  },
};
