import type { SelectPrimitive } from "@govtech-bb/form-types";

export const PrimarySchool: SelectPrimitive = {
  fieldId: "primary-school",
  label: "Primary School",
  htmlType: "select",
  options: [
    { label: "A Dacosta Edwards", value: "a-dacosta-edwards" },
    { label: "All Saints' Primary", value: "all-saints-primary" },
    { label: "Arthur Smith Primary", value: "arthur-smith-primary" },
    { label: "Bay Primary School", value: "bay-primary-school" },
    { label: "Bayley's Primary", value: "bayleys-primary" },
    { label: "Belmont Primary", value: "belmont-primary" },
    { label: "Blackman/Gollop Primary", value: "blackman-gollop-primary" },
    { label: "Charles F Broome", value: "charles-f-broome" },
    { label: "Christ Church Girls", value: "christ-church-girls" },
    { label: "Cuthbert Moore Primary", value: "cuthbert-moore-primary" },
    { label: "Deacons Primary", value: "deacons-primary" },
    { label: "Eagle Hall Primary", value: "eagle-hall-primary" },
    { label: "Eden Lodge", value: "eden-lodge" },
    { label: "Ellerton Primary", value: "ellerton-primary" },
    { label: "Elliot Belgrave", value: "elliot-belgrave" },
    { label: "Good Shepherd Primary", value: "good-shepherd-primary" },
    { label: "Gordon Greenidge Primary", value: "gordon-greenidge-primary" },
    { label: "Gordon Walters", value: "gordon-walters" },
    { label: "Grantley Prescod Memorial", value: "grantley-prescod-memorial" },
    { label: "Grazettes Primary", value: "grazettes-primary" },
    { label: "Half Moon Fort", value: "half-moon-fort" },
    { label: "Hilda Skeene Primary", value: "hilda-skeene-primary" },
    { label: "Hillaby Turner's Hall", value: "hillaby-turners-hall" },
    { label: "Hindsbury Primary", value: "hindsbury-primary" },
    { label: "Holy Innocents' Primary", value: "holy-innocents-primary" },
    { label: "Ignatius Byer Primary", value: "ignatius-byer-primary" },
    { label: "Kelly's Fantastic School", value: "kellys-fantastic-school" },
    { label: "Lawrence T Gay", value: "lawrence-t-gay" },
    { label: "Luther Thorne Memorial", value: "luther-thorne-memorial" },
    { label: "Milton Lynch Primary", value: "milton-lynch-primary" },
    {
      label: "Mount Tabor Primary School",
      value: "mount-tabor-primary-school",
    },
    { label: "New Horizon Academy", value: "new-horizon-academy" },
    {
      label: "Reynold Weekes Primary School",
      value: "reynold-weekes-primary-school",
    },
    { label: "Roland Edwards Primary", value: "roland-edwards-primary" },
    { label: "Selah Primary School", value: "selah-primary-school" },
    { label: "Sharon Primary", value: "sharon-primary" },
    { label: "St. Albans Primary", value: "st-albans-primary" },
    { label: "St. Ambrose Primary", value: "st-ambrose-primary" },
    { label: "St. Bartholomew Primary", value: "st-bartholomew-primary" },
    { label: "St. Bernard's Primary", value: "st-bernards-primary" },
    { label: "St. Catherine's Primary", value: "st-catherines-primary" },
    { label: "St. Christopher Primary", value: "st-christopher-primary" },
    { label: "St. Elizabeth Primary", value: "st-elizabeth-primary" },
    { label: "St. George Primary", value: "st-george-primary" },
    { label: "St. Giles Primary", value: "st-giles-primary" },
    { label: "St. James Primary", value: "st-james-primary" },
    { label: "St. John's Primary", value: "st-johns-primary" },
    { label: "St. Joseph Primary", value: "st-joseph-primary" },
    { label: "St. Jude's Primary", value: "st-judes-primary" },
    { label: "St. Lawrence Primary", value: "st-lawrence-primary" },
    { label: "St. Lucy's Primary", value: "st-lucys-primary" },
    { label: "St. Lukes/Brighton Primary", value: "st-lukes-brighton-primary" },
    {
      label: "St. Margaret's Primary School",
      value: "st-margarets-primary-school",
    },
    { label: "St. Marks Primary", value: "st-marks-primary" },
    { label: "St. Martins Mangrove", value: "st-martins-mangrove" },
    { label: "St. Mary's Primary", value: "st-marys-primary" },
    { label: "St. Matthew's Primary", value: "st-matthews-primary" },
    { label: "St. Paul Primary", value: "st-paul-primary" },
    { label: "St. Philip Primary", value: "st-philip-primary" },
    { label: "St. Silas Primary", value: "st-silas-primary" },
    { label: "St. Stephen's Primary", value: "st-stephens-primary" },
    { label: "The Ann Hill School", value: "the-ann-hill-school" },
    { label: "The Irving Wilson School", value: "the-irving-wilson-school" },
    { label: "Vauxhall Primary", value: "vauxhall-primary" },
    { label: "Welches Primary", value: "welches-primary" },
    { label: "Wesley Hall Infants", value: "wesley-hall-infants" },
    { label: "Wesley Hall Junior", value: "wesley-hall-junior" },
    { label: "West Terrace", value: "west-terrace" },
    { label: "Westbury Primary", value: "westbury-primary" },
    { label: "Wilkie Cumberbatch", value: "wilkie-cumberbatch" },
    { label: "Workman's Primary", value: "workmans-primary" },
  ],
  multiple: false,
  ui: {
    width: "long",
  },
  validations: {
    required: {
      value: true,
      error: "Primary School is required",
    },
  },
};
