/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceServicesRouteImport } from './routes/_workspace.services'
import { Route as WorkspaceServicesServiceIdRouteImport } from './routes/_workspace.services.$serviceId'
import { Route as WorkspaceServicesServiceIdDocumentIdRouteImport } from './routes/_workspace.services.$serviceId.$documentId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceServicesRoute = WorkspaceServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceServicesServiceIdRoute =
  WorkspaceServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => WorkspaceServicesRoute,
  } as any)
const WorkspaceServicesServiceIdDocumentIdRoute =
  WorkspaceServicesServiceIdDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => WorkspaceServicesServiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/auth': typeof AuthRoute
  '/services': typeof WorkspaceServicesRouteWithChildren
  '/services/$serviceId': typeof WorkspaceServicesServiceIdRouteWithChildren
  '/services/$serviceId/$documentId': typeof WorkspaceServicesServiceIdDocumentIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/services': typeof WorkspaceServicesRouteWithChildren
  '/': typeof WorkspaceIndexRoute
  '/services/$serviceId': typeof WorkspaceServicesServiceIdRouteWithChildren
  '/services/$serviceId/$documentId': typeof WorkspaceServicesServiceIdDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/auth': typeof AuthRoute
  '/_workspace/services': typeof WorkspaceServicesRouteWithChildren
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/services/$serviceId': typeof WorkspaceServicesServiceIdRouteWithChildren
  '/_workspace/services/$serviceId/$documentId': typeof WorkspaceServicesServiceIdDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/services'
    | '/services/$serviceId'
    | '/services/$serviceId/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/services'
    | '/'
    | '/services/$serviceId'
    | '/services/$serviceId/$documentId'
  id:
    | '__root__'
    | '/_workspace'
    | '/auth'
    | '/_workspace/services'
    | '/_workspace/'
    | '/_workspace/services/$serviceId'
    | '/_workspace/services/$serviceId/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/services': {
      id: '/_workspace/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof WorkspaceServicesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/services/$serviceId': {
      id: '/_workspace/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof WorkspaceServicesServiceIdRouteImport
      parentRoute: typeof WorkspaceServicesRoute
    }
    '/_workspace/services/$serviceId/$documentId': {
      id: '/_workspace/services/$serviceId/$documentId'
      path: '/$documentId'
      fullPath: '/services/$serviceId/$documentId'
      preLoaderRoute: typeof WorkspaceServicesServiceIdDocumentIdRouteImport
      parentRoute: typeof WorkspaceServicesServiceIdRoute
    }
  }
}

interface WorkspaceServicesServiceIdRouteChildren {
  WorkspaceServicesServiceIdDocumentIdRoute: typeof WorkspaceServicesServiceIdDocumentIdRoute
}

const WorkspaceServicesServiceIdRouteChildren: WorkspaceServicesServiceIdRouteChildren =
  {
    WorkspaceServicesServiceIdDocumentIdRoute:
      WorkspaceServicesServiceIdDocumentIdRoute,
  }

const WorkspaceServicesServiceIdRouteWithChildren =
  WorkspaceServicesServiceIdRoute._addFileChildren(
    WorkspaceServicesServiceIdRouteChildren,
  )

interface WorkspaceServicesRouteChildren {
  WorkspaceServicesServiceIdRoute: typeof WorkspaceServicesServiceIdRouteWithChildren
}

const WorkspaceServicesRouteChildren: WorkspaceServicesRouteChildren = {
  WorkspaceServicesServiceIdRoute: WorkspaceServicesServiceIdRouteWithChildren,
}

const WorkspaceServicesRouteWithChildren =
  WorkspaceServicesRoute._addFileChildren(WorkspaceServicesRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceServicesRoute: typeof WorkspaceServicesRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceServicesRoute: WorkspaceServicesRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
