// Generates app/lib/services-catalogue.generated.ts from the landing content
// index. Offline-safe (filesystem read only, no network) — run it when landing
// content changes: `pnpm --filter @govtech-bb/feature-flagging-app generate:catalogue`.
//
// The generated landing list is baked into the SSR bundle; the live forms list
// (GET /form-definitions) and live statuses (GET /service_status) are fetched at
// request time and reconciled in app/lib/catalogue.ts.
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { loadContent } from "@govtech-bb/content";
import type { LandingService } from "../app/lib/catalogue";

async function main() {
  const { services, warnings } = await loadContent();
  for (const w of warnings) console.warn(w);

  const list: LandingService[] = services
    .map((s): LandingService => {
      const formId =
        typeof s.form_id === "string" && s.form_id.length > 0
          ? s.form_id
          : undefined;
      const category = s.category ?? s.categories?.[0];
      return {
        contentSlug: s.slug,
        title: s.title,
        ...(category ? { category } : {}),
        ...(formId ? { formId } : {}),
        ...(s.visibility ? { contentVisibility: s.visibility } : {}),
      };
    })
    .sort((a, b) => a.contentSlug.localeCompare(b.contentSlug));

  const body =
    "// GENERATED by scripts/generate-services-catalogue.ts — do not edit by hand.\n" +
    "// Regenerate with `pnpm --filter @govtech-bb/feature-flagging-app generate:catalogue`\n" +
    "// when landing content changes.\n" +
    'import type { LandingService } from "./catalogue";\n\n' +
    `export const LANDING_SERVICES: LandingService[] = ${JSON.stringify(list, null, 2)};\n`;

  const out = join(
    dirname(fileURLToPath(import.meta.url)),
    "..",
    "app",
    "lib",
    "services-catalogue.generated.ts",
  );
  await writeFile(out, body, "utf8");
  console.log(`Wrote ${list.length} landing services to ${out}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
