/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRetrieveRouteImport } from './routes/api.retrieve'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiFormFileRouteImport } from './routes/api.form-file'
import { Route as ApiDocumentsRouteImport } from './routes/api.documents'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiHealthPublicRouteImport } from './routes/api.health.public'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRetrieveRoute = ApiRetrieveRouteImport.update({
  id: '/api/retrieve',
  path: '/api/retrieve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormFileRoute = ApiFormFileRouteImport.update({
  id: '/api/form-file',
  path: '/api/form-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthPublicRoute = ApiHealthPublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => ApiHealthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/form-file': typeof ApiFormFileRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/retrieve': typeof ApiRetrieveRoute
  '/api/health/public': typeof ApiHealthPublicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/form-file': typeof ApiFormFileRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/retrieve': typeof ApiRetrieveRoute
  '/api/health/public': typeof ApiHealthPublicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/form-file': typeof ApiFormFileRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/retrieve': typeof ApiRetrieveRoute
  '/api/health/public': typeof ApiHealthPublicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/documents'
    | '/api/form-file'
    | '/api/health'
    | '/api/retrieve'
    | '/api/health/public'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/documents'
    | '/api/form-file'
    | '/api/health'
    | '/api/retrieve'
    | '/api/health/public'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/documents'
    | '/api/form-file'
    | '/api/health'
    | '/api/retrieve'
    | '/api/health/public'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDocumentsRoute: typeof ApiDocumentsRoute
  ApiFormFileRoute: typeof ApiFormFileRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ApiRetrieveRoute: typeof ApiRetrieveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/retrieve': {
      id: '/api/retrieve'
      path: '/api/retrieve'
      fullPath: '/api/retrieve'
      preLoaderRoute: typeof ApiRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-file': {
      id: '/api/form-file'
      path: '/api/form-file'
      fullPath: '/api/form-file'
      preLoaderRoute: typeof ApiFormFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/public': {
      id: '/api/health/public'
      path: '/public'
      fullPath: '/api/health/public'
      preLoaderRoute: typeof ApiHealthPublicRouteImport
      parentRoute: typeof ApiHealthRoute
    }
  }
}

interface ApiHealthRouteChildren {
  ApiHealthPublicRoute: typeof ApiHealthPublicRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthPublicRoute: ApiHealthPublicRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDocumentsRoute: ApiDocumentsRoute,
  ApiFormFileRoute: ApiFormFileRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiRetrieveRoute: ApiRetrieveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
