/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TellUsRouteImport } from './routes/tell-us'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceUnavailableRouteImport } from './routes/service-unavailable'
import { Route as SearchResultsRouteImport } from './routes/search-results'
import { Route as JavascriptRequiredRouteImport } from './routes/javascript-required'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GovernmentOrganisationsRouteImport } from './routes/government.organisations'
import { Route as GovernmentOrganisationsIndexRouteImport } from './routes/government.organisations.index'
import { Route as GovernmentOrganisationsSlugRouteImport } from './routes/government.organisations.$slug'

const TellUsRoute = TellUsRouteImport.update({
  id: '/tell-us',
  path: '/tell-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceUnavailableRoute = ServiceUnavailableRouteImport.update({
  id: '/service-unavailable',
  path: '/service-unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsRoute = SearchResultsRouteImport.update({
  id: '/search-results',
  path: '/search-results',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptRequiredRoute = JavascriptRequiredRouteImport.update({
  id: '/javascript-required',
  path: '/javascript-required',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentOrganisationsRoute = GovernmentOrganisationsRouteImport.update({
  id: '/government/organisations',
  path: '/government/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentOrganisationsIndexRoute =
  GovernmentOrganisationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GovernmentOrganisationsRoute,
  } as any)
const GovernmentOrganisationsSlugRoute =
  GovernmentOrganisationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => GovernmentOrganisationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/feedback': typeof FeedbackRoute
  '/javascript-required': typeof JavascriptRequiredRoute
  '/search-results': typeof SearchResultsRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/services': typeof ServicesRoute
  '/tell-us': typeof TellUsRoute
  '/government/organisations': typeof GovernmentOrganisationsRouteWithChildren
  '/government/organisations/$slug': typeof GovernmentOrganisationsSlugRoute
  '/government/organisations/': typeof GovernmentOrganisationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/feedback': typeof FeedbackRoute
  '/javascript-required': typeof JavascriptRequiredRoute
  '/search-results': typeof SearchResultsRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/services': typeof ServicesRoute
  '/tell-us': typeof TellUsRoute
  '/government/organisations/$slug': typeof GovernmentOrganisationsSlugRoute
  '/government/organisations': typeof GovernmentOrganisationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/feedback': typeof FeedbackRoute
  '/javascript-required': typeof JavascriptRequiredRoute
  '/search-results': typeof SearchResultsRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/services': typeof ServicesRoute
  '/tell-us': typeof TellUsRoute
  '/government/organisations': typeof GovernmentOrganisationsRouteWithChildren
  '/government/organisations/$slug': typeof GovernmentOrganisationsSlugRoute
  '/government/organisations/': typeof GovernmentOrganisationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/feedback'
    | '/javascript-required'
    | '/search-results'
    | '/service-unavailable'
    | '/services'
    | '/tell-us'
    | '/government/organisations'
    | '/government/organisations/$slug'
    | '/government/organisations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/feedback'
    | '/javascript-required'
    | '/search-results'
    | '/service-unavailable'
    | '/services'
    | '/tell-us'
    | '/government/organisations/$slug'
    | '/government/organisations'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/feedback'
    | '/javascript-required'
    | '/search-results'
    | '/service-unavailable'
    | '/services'
    | '/tell-us'
    | '/government/organisations'
    | '/government/organisations/$slug'
    | '/government/organisations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  FeedbackRoute: typeof FeedbackRoute
  JavascriptRequiredRoute: typeof JavascriptRequiredRoute
  SearchResultsRoute: typeof SearchResultsRoute
  ServiceUnavailableRoute: typeof ServiceUnavailableRoute
  ServicesRoute: typeof ServicesRoute
  TellUsRoute: typeof TellUsRoute
  GovernmentOrganisationsRoute: typeof GovernmentOrganisationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tell-us': {
      id: '/tell-us'
      path: '/tell-us'
      fullPath: '/tell-us'
      preLoaderRoute: typeof TellUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-unavailable': {
      id: '/service-unavailable'
      path: '/service-unavailable'
      fullPath: '/service-unavailable'
      preLoaderRoute: typeof ServiceUnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-results': {
      id: '/search-results'
      path: '/search-results'
      fullPath: '/search-results'
      preLoaderRoute: typeof SearchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript-required': {
      id: '/javascript-required'
      path: '/javascript-required'
      fullPath: '/javascript-required'
      preLoaderRoute: typeof JavascriptRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government/organisations': {
      id: '/government/organisations'
      path: '/government/organisations'
      fullPath: '/government/organisations'
      preLoaderRoute: typeof GovernmentOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government/organisations/': {
      id: '/government/organisations/'
      path: '/'
      fullPath: '/government/organisations/'
      preLoaderRoute: typeof GovernmentOrganisationsIndexRouteImport
      parentRoute: typeof GovernmentOrganisationsRoute
    }
    '/government/organisations/$slug': {
      id: '/government/organisations/$slug'
      path: '/$slug'
      fullPath: '/government/organisations/$slug'
      preLoaderRoute: typeof GovernmentOrganisationsSlugRouteImport
      parentRoute: typeof GovernmentOrganisationsRoute
    }
  }
}

interface GovernmentOrganisationsRouteChildren {
  GovernmentOrganisationsSlugRoute: typeof GovernmentOrganisationsSlugRoute
  GovernmentOrganisationsIndexRoute: typeof GovernmentOrganisationsIndexRoute
}

const GovernmentOrganisationsRouteChildren: GovernmentOrganisationsRouteChildren =
  {
    GovernmentOrganisationsSlugRoute: GovernmentOrganisationsSlugRoute,
    GovernmentOrganisationsIndexRoute: GovernmentOrganisationsIndexRoute,
  }

const GovernmentOrganisationsRouteWithChildren =
  GovernmentOrganisationsRoute._addFileChildren(
    GovernmentOrganisationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  FeedbackRoute: FeedbackRoute,
  JavascriptRequiredRoute: JavascriptRequiredRoute,
  SearchResultsRoute: SearchResultsRoute,
  ServiceUnavailableRoute: ServiceUnavailableRoute,
  ServicesRoute: ServicesRoute,
  TellUsRoute: TellUsRoute,
  GovernmentOrganisationsRoute: GovernmentOrganisationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
