/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TellUsRouteImport } from './routes/tell-us'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceUnavailableRouteImport } from './routes/service-unavailable'
import { Route as SearchResultsRouteImport } from './routes/search-results'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PreviewStartPageRouteImport } from './routes/preview-start-page'
import { Route as JavascriptRequiredRouteImport } from './routes/javascript-required'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankHolidayCalendarIndexRouteImport } from './routes/bank-holiday-calendar/index'
import { Route as HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteImport } from './routes/health-and-emergency-services/find-an-emergency-shelter/route'
import { Route as HealthAndEmergencyServicesFindAnEmergencyShelterIndexRouteImport } from './routes/health-and-emergency-services/find-an-emergency-shelter/index'
import { Route as PensionsAndGratuitiesCalculateYourPensionFormRouteImport } from './routes/pensions-and-gratuities/calculate-your-pension/form'
import { Route as MoneyFinancialSupportCalculateSeverancePayFormRouteImport } from './routes/money-financial-support/calculate-severance-pay/form'
import { Route as HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRouteImport } from './routes/health-and-emergency-services/find-an-emergency-shelter/guidance'
import { Route as HealthAndEmergencyServicesFindAnEmergencyShelterFindRouteImport } from './routes/health-and-emergency-services/find-an-emergency-shelter/find'
import { Route as BusinessTradeCropOverPermitsFormRouteImport } from './routes/business-trade/crop-over-permits/form'

const TellUsRoute = TellUsRouteImport.update({
  id: '/tell-us',
  path: '/tell-us',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceUnavailableRoute = ServiceUnavailableRouteImport.update({
  id: '/service-unavailable',
  path: '/service-unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsRoute = SearchResultsRouteImport.update({
  id: '/search-results',
  path: '/search-results',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewStartPageRoute = PreviewStartPageRouteImport.update({
  id: '/preview-start-page',
  path: '/preview-start-page',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptRequiredRoute = JavascriptRequiredRouteImport.update({
  id: '/javascript-required',
  path: '/javascript-required',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankHolidayCalendarIndexRoute =
  BankHolidayCalendarIndexRouteImport.update({
    id: '/bank-holiday-calendar/',
    path: '/bank-holiday-calendar/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute =
  HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteImport.update({
    id: '/health-and-emergency-services/find-an-emergency-shelter',
    path: '/health-and-emergency-services/find-an-emergency-shelter',
    getParentRoute: () => rootRouteImport,
  } as any)
const HealthAndEmergencyServicesFindAnEmergencyShelterIndexRoute =
  HealthAndEmergencyServicesFindAnEmergencyShelterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute,
  } as any)
const PensionsAndGratuitiesCalculateYourPensionFormRoute =
  PensionsAndGratuitiesCalculateYourPensionFormRouteImport.update({
    id: '/pensions-and-gratuities/calculate-your-pension/form',
    path: '/pensions-and-gratuities/calculate-your-pension/form',
    getParentRoute: () => rootRouteImport,
  } as any)
const MoneyFinancialSupportCalculateSeverancePayFormRoute =
  MoneyFinancialSupportCalculateSeverancePayFormRouteImport.update({
    id: '/money-financial-support/calculate-severance-pay/form',
    path: '/money-financial-support/calculate-severance-pay/form',
    getParentRoute: () => rootRouteImport,
  } as any)
const HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRoute =
  HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRouteImport.update({
    id: '/guidance',
    path: '/guidance',
    getParentRoute: () =>
      HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute,
  } as any)
const HealthAndEmergencyServicesFindAnEmergencyShelterFindRoute =
  HealthAndEmergencyServicesFindAnEmergencyShelterFindRouteImport.update({
    id: '/find',
    path: '/find',
    getParentRoute: () =>
      HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute,
  } as any)
const BusinessTradeCropOverPermitsFormRoute =
  BusinessTradeCropOverPermitsFormRouteImport.update({
    id: '/business-trade/crop-over-permits/form',
    path: '/business-trade/crop-over-permits/form',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRoute
  '/javascript-required': typeof JavascriptRequiredRoute
  '/preview-start-page': typeof PreviewStartPageRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search-results': typeof SearchResultsRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tell-us': typeof TellUsRoute
  '/health-and-emergency-services/find-an-emergency-shelter': typeof HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteWithChildren
  '/bank-holiday-calendar/': typeof BankHolidayCalendarIndexRoute
  '/business-trade/crop-over-permits/form': typeof BusinessTradeCropOverPermitsFormRoute
  '/health-and-emergency-services/find-an-emergency-shelter/find': typeof HealthAndEmergencyServicesFindAnEmergencyShelterFindRoute
  '/health-and-emergency-services/find-an-emergency-shelter/guidance': typeof HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRoute
  '/money-financial-support/calculate-severance-pay/form': typeof MoneyFinancialSupportCalculateSeverancePayFormRoute
  '/pensions-and-gratuities/calculate-your-pension/form': typeof PensionsAndGratuitiesCalculateYourPensionFormRoute
  '/health-and-emergency-services/find-an-emergency-shelter/': typeof HealthAndEmergencyServicesFindAnEmergencyShelterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRoute
  '/javascript-required': typeof JavascriptRequiredRoute
  '/preview-start-page': typeof PreviewStartPageRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search-results': typeof SearchResultsRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tell-us': typeof TellUsRoute
  '/bank-holiday-calendar': typeof BankHolidayCalendarIndexRoute
  '/business-trade/crop-over-permits/form': typeof BusinessTradeCropOverPermitsFormRoute
  '/health-and-emergency-services/find-an-emergency-shelter/find': typeof HealthAndEmergencyServicesFindAnEmergencyShelterFindRoute
  '/health-and-emergency-services/find-an-emergency-shelter/guidance': typeof HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRoute
  '/money-financial-support/calculate-severance-pay/form': typeof MoneyFinancialSupportCalculateSeverancePayFormRoute
  '/pensions-and-gratuities/calculate-your-pension/form': typeof PensionsAndGratuitiesCalculateYourPensionFormRoute
  '/health-and-emergency-services/find-an-emergency-shelter': typeof HealthAndEmergencyServicesFindAnEmergencyShelterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/analytics': typeof AnalyticsRoute
  '/feedback': typeof FeedbackRoute
  '/javascript-required': typeof JavascriptRequiredRoute
  '/preview-start-page': typeof PreviewStartPageRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search-results': typeof SearchResultsRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tell-us': typeof TellUsRoute
  '/health-and-emergency-services/find-an-emergency-shelter': typeof HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteWithChildren
  '/bank-holiday-calendar/': typeof BankHolidayCalendarIndexRoute
  '/business-trade/crop-over-permits/form': typeof BusinessTradeCropOverPermitsFormRoute
  '/health-and-emergency-services/find-an-emergency-shelter/find': typeof HealthAndEmergencyServicesFindAnEmergencyShelterFindRoute
  '/health-and-emergency-services/find-an-emergency-shelter/guidance': typeof HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRoute
  '/money-financial-support/calculate-severance-pay/form': typeof MoneyFinancialSupportCalculateSeverancePayFormRoute
  '/pensions-and-gratuities/calculate-your-pension/form': typeof PensionsAndGratuitiesCalculateYourPensionFormRoute
  '/health-and-emergency-services/find-an-emergency-shelter/': typeof HealthAndEmergencyServicesFindAnEmergencyShelterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/analytics'
    | '/feedback'
    | '/javascript-required'
    | '/preview-start-page'
    | '/robots.txt'
    | '/search-results'
    | '/service-unavailable'
    | '/services'
    | '/sitemap.xml'
    | '/tell-us'
    | '/health-and-emergency-services/find-an-emergency-shelter'
    | '/bank-holiday-calendar/'
    | '/business-trade/crop-over-permits/form'
    | '/health-and-emergency-services/find-an-emergency-shelter/find'
    | '/health-and-emergency-services/find-an-emergency-shelter/guidance'
    | '/money-financial-support/calculate-severance-pay/form'
    | '/pensions-and-gratuities/calculate-your-pension/form'
    | '/health-and-emergency-services/find-an-emergency-shelter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/analytics'
    | '/feedback'
    | '/javascript-required'
    | '/preview-start-page'
    | '/robots.txt'
    | '/search-results'
    | '/service-unavailable'
    | '/services'
    | '/sitemap.xml'
    | '/tell-us'
    | '/bank-holiday-calendar'
    | '/business-trade/crop-over-permits/form'
    | '/health-and-emergency-services/find-an-emergency-shelter/find'
    | '/health-and-emergency-services/find-an-emergency-shelter/guidance'
    | '/money-financial-support/calculate-severance-pay/form'
    | '/pensions-and-gratuities/calculate-your-pension/form'
    | '/health-and-emergency-services/find-an-emergency-shelter'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/analytics'
    | '/feedback'
    | '/javascript-required'
    | '/preview-start-page'
    | '/robots.txt'
    | '/search-results'
    | '/service-unavailable'
    | '/services'
    | '/sitemap.xml'
    | '/tell-us'
    | '/health-and-emergency-services/find-an-emergency-shelter'
    | '/bank-holiday-calendar/'
    | '/business-trade/crop-over-permits/form'
    | '/health-and-emergency-services/find-an-emergency-shelter/find'
    | '/health-and-emergency-services/find-an-emergency-shelter/guidance'
    | '/money-financial-support/calculate-severance-pay/form'
    | '/pensions-and-gratuities/calculate-your-pension/form'
    | '/health-and-emergency-services/find-an-emergency-shelter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AnalyticsRoute: typeof AnalyticsRoute
  FeedbackRoute: typeof FeedbackRoute
  JavascriptRequiredRoute: typeof JavascriptRequiredRoute
  PreviewStartPageRoute: typeof PreviewStartPageRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchResultsRoute: typeof SearchResultsRoute
  ServiceUnavailableRoute: typeof ServiceUnavailableRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TellUsRoute: typeof TellUsRoute
  HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteWithChildren
  BankHolidayCalendarIndexRoute: typeof BankHolidayCalendarIndexRoute
  BusinessTradeCropOverPermitsFormRoute: typeof BusinessTradeCropOverPermitsFormRoute
  MoneyFinancialSupportCalculateSeverancePayFormRoute: typeof MoneyFinancialSupportCalculateSeverancePayFormRoute
  PensionsAndGratuitiesCalculateYourPensionFormRoute: typeof PensionsAndGratuitiesCalculateYourPensionFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tell-us': {
      id: '/tell-us'
      path: '/tell-us'
      fullPath: '/tell-us'
      preLoaderRoute: typeof TellUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-unavailable': {
      id: '/service-unavailable'
      path: '/service-unavailable'
      fullPath: '/service-unavailable'
      preLoaderRoute: typeof ServiceUnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-results': {
      id: '/search-results'
      path: '/search-results'
      fullPath: '/search-results'
      preLoaderRoute: typeof SearchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-start-page': {
      id: '/preview-start-page'
      path: '/preview-start-page'
      fullPath: '/preview-start-page'
      preLoaderRoute: typeof PreviewStartPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript-required': {
      id: '/javascript-required'
      path: '/javascript-required'
      fullPath: '/javascript-required'
      preLoaderRoute: typeof JavascriptRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-holiday-calendar/': {
      id: '/bank-holiday-calendar/'
      path: '/bank-holiday-calendar'
      fullPath: '/bank-holiday-calendar/'
      preLoaderRoute: typeof BankHolidayCalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-and-emergency-services/find-an-emergency-shelter': {
      id: '/health-and-emergency-services/find-an-emergency-shelter'
      path: '/health-and-emergency-services/find-an-emergency-shelter'
      fullPath: '/health-and-emergency-services/find-an-emergency-shelter'
      preLoaderRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-and-emergency-services/find-an-emergency-shelter/': {
      id: '/health-and-emergency-services/find-an-emergency-shelter/'
      path: '/'
      fullPath: '/health-and-emergency-services/find-an-emergency-shelter/'
      preLoaderRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterIndexRouteImport
      parentRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute
    }
    '/pensions-and-gratuities/calculate-your-pension/form': {
      id: '/pensions-and-gratuities/calculate-your-pension/form'
      path: '/pensions-and-gratuities/calculate-your-pension/form'
      fullPath: '/pensions-and-gratuities/calculate-your-pension/form'
      preLoaderRoute: typeof PensionsAndGratuitiesCalculateYourPensionFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-financial-support/calculate-severance-pay/form': {
      id: '/money-financial-support/calculate-severance-pay/form'
      path: '/money-financial-support/calculate-severance-pay/form'
      fullPath: '/money-financial-support/calculate-severance-pay/form'
      preLoaderRoute: typeof MoneyFinancialSupportCalculateSeverancePayFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-and-emergency-services/find-an-emergency-shelter/guidance': {
      id: '/health-and-emergency-services/find-an-emergency-shelter/guidance'
      path: '/guidance'
      fullPath: '/health-and-emergency-services/find-an-emergency-shelter/guidance'
      preLoaderRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRouteImport
      parentRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute
    }
    '/health-and-emergency-services/find-an-emergency-shelter/find': {
      id: '/health-and-emergency-services/find-an-emergency-shelter/find'
      path: '/find'
      fullPath: '/health-and-emergency-services/find-an-emergency-shelter/find'
      preLoaderRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterFindRouteImport
      parentRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute
    }
    '/business-trade/crop-over-permits/form': {
      id: '/business-trade/crop-over-permits/form'
      path: '/business-trade/crop-over-permits/form'
      fullPath: '/business-trade/crop-over-permits/form'
      preLoaderRoute: typeof BusinessTradeCropOverPermitsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteChildren {
  HealthAndEmergencyServicesFindAnEmergencyShelterFindRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterFindRoute
  HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRoute
  HealthAndEmergencyServicesFindAnEmergencyShelterIndexRoute: typeof HealthAndEmergencyServicesFindAnEmergencyShelterIndexRoute
}

const HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteChildren: HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteChildren =
  {
    HealthAndEmergencyServicesFindAnEmergencyShelterFindRoute:
      HealthAndEmergencyServicesFindAnEmergencyShelterFindRoute,
    HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRoute:
      HealthAndEmergencyServicesFindAnEmergencyShelterGuidanceRoute,
    HealthAndEmergencyServicesFindAnEmergencyShelterIndexRoute:
      HealthAndEmergencyServicesFindAnEmergencyShelterIndexRoute,
  }

const HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteWithChildren =
  HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute._addFileChildren(
    HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AnalyticsRoute: AnalyticsRoute,
  FeedbackRoute: FeedbackRoute,
  JavascriptRequiredRoute: JavascriptRequiredRoute,
  PreviewStartPageRoute: PreviewStartPageRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchResultsRoute: SearchResultsRoute,
  ServiceUnavailableRoute: ServiceUnavailableRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TellUsRoute: TellUsRoute,
  HealthAndEmergencyServicesFindAnEmergencyShelterRouteRoute:
    HealthAndEmergencyServicesFindAnEmergencyShelterRouteRouteWithChildren,
  BankHolidayCalendarIndexRoute: BankHolidayCalendarIndexRoute,
  BusinessTradeCropOverPermitsFormRoute: BusinessTradeCropOverPermitsFormRoute,
  MoneyFinancialSupportCalculateSeverancePayFormRoute:
    MoneyFinancialSupportCalculateSeverancePayFormRoute,
  PensionsAndGratuitiesCalculateYourPensionFormRoute:
    PensionsAndGratuitiesCalculateYourPensionFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
