/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TellUsRouteImport } from './routes/tell-us'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceUnavailableRouteImport } from './routes/service-unavailable'
import { Route as SearchResultsRouteImport } from './routes/search-results'
import { Route as JavascriptRequiredRouteImport } from './routes/javascript-required'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as BankHolidayCalendarRouteImport } from './routes/bank-holiday-calendar'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PensionsAndGratuitiesCalculateYourPensionFormRouteImport } from './routes/pensions-and-gratuities.calculate-your-pension.form'
import { Route as MoneyFinancialSupportCalculateSeverancePayFormRouteImport } from './routes/money-financial-support.calculate-severance-pay.form'
import { Route as BusinessTradeCropOverPermitsFormRouteImport } from './routes/business-trade.crop-over-permits.form'

const TellUsRoute = TellUsRouteImport.update({
  id: '/tell-us',
  path: '/tell-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceUnavailableRoute = ServiceUnavailableRouteImport.update({
  id: '/service-unavailable',
  path: '/service-unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsRoute = SearchResultsRouteImport.update({
  id: '/search-results',
  path: '/search-results',
  getParentRoute: () => rootRouteImport,
} as any)
const JavascriptRequiredRoute = JavascriptRequiredRouteImport.update({
  id: '/javascript-required',
  path: '/javascript-required',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const BankHolidayCalendarRoute = BankHolidayCalendarRouteImport.update({
  id: '/bank-holiday-calendar',
  path: '/bank-holiday-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PensionsAndGratuitiesCalculateYourPensionFormRoute =
  PensionsAndGratuitiesCalculateYourPensionFormRouteImport.update({
    id: '/pensions-and-gratuities/calculate-your-pension/form',
    path: '/pensions-and-gratuities/calculate-your-pension/form',
    getParentRoute: () => rootRouteImport,
  } as any)
const MoneyFinancialSupportCalculateSeverancePayFormRoute =
  MoneyFinancialSupportCalculateSeverancePayFormRouteImport.update({
    id: '/money-financial-support/calculate-severance-pay/form',
    path: '/money-financial-support/calculate-severance-pay/form',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessTradeCropOverPermitsFormRoute =
  BusinessTradeCropOverPermitsFormRouteImport.update({
    id: '/business-trade/crop-over-permits/form',
    path: '/business-trade/crop-over-permits/form',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bank-holiday-calendar': typeof BankHolidayCalendarRoute
  '/feedback': typeof FeedbackRoute
  '/javascript-required': typeof JavascriptRequiredRoute
  '/search-results': typeof SearchResultsRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/services': typeof ServicesRoute
  '/tell-us': typeof TellUsRoute
  '/business-trade/crop-over-permits/form': typeof BusinessTradeCropOverPermitsFormRoute
  '/money-financial-support/calculate-severance-pay/form': typeof MoneyFinancialSupportCalculateSeverancePayFormRoute
  '/pensions-and-gratuities/calculate-your-pension/form': typeof PensionsAndGratuitiesCalculateYourPensionFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bank-holiday-calendar': typeof BankHolidayCalendarRoute
  '/feedback': typeof FeedbackRoute
  '/javascript-required': typeof JavascriptRequiredRoute
  '/search-results': typeof SearchResultsRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/services': typeof ServicesRoute
  '/tell-us': typeof TellUsRoute
  '/business-trade/crop-over-permits/form': typeof BusinessTradeCropOverPermitsFormRoute
  '/money-financial-support/calculate-severance-pay/form': typeof MoneyFinancialSupportCalculateSeverancePayFormRoute
  '/pensions-and-gratuities/calculate-your-pension/form': typeof PensionsAndGratuitiesCalculateYourPensionFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bank-holiday-calendar': typeof BankHolidayCalendarRoute
  '/feedback': typeof FeedbackRoute
  '/javascript-required': typeof JavascriptRequiredRoute
  '/search-results': typeof SearchResultsRoute
  '/service-unavailable': typeof ServiceUnavailableRoute
  '/services': typeof ServicesRoute
  '/tell-us': typeof TellUsRoute
  '/business-trade/crop-over-permits/form': typeof BusinessTradeCropOverPermitsFormRoute
  '/money-financial-support/calculate-severance-pay/form': typeof MoneyFinancialSupportCalculateSeverancePayFormRoute
  '/pensions-and-gratuities/calculate-your-pension/form': typeof PensionsAndGratuitiesCalculateYourPensionFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/bank-holiday-calendar'
    | '/feedback'
    | '/javascript-required'
    | '/search-results'
    | '/service-unavailable'
    | '/services'
    | '/tell-us'
    | '/business-trade/crop-over-permits/form'
    | '/money-financial-support/calculate-severance-pay/form'
    | '/pensions-and-gratuities/calculate-your-pension/form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/bank-holiday-calendar'
    | '/feedback'
    | '/javascript-required'
    | '/search-results'
    | '/service-unavailable'
    | '/services'
    | '/tell-us'
    | '/business-trade/crop-over-permits/form'
    | '/money-financial-support/calculate-severance-pay/form'
    | '/pensions-and-gratuities/calculate-your-pension/form'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/bank-holiday-calendar'
    | '/feedback'
    | '/javascript-required'
    | '/search-results'
    | '/service-unavailable'
    | '/services'
    | '/tell-us'
    | '/business-trade/crop-over-permits/form'
    | '/money-financial-support/calculate-severance-pay/form'
    | '/pensions-and-gratuities/calculate-your-pension/form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BankHolidayCalendarRoute: typeof BankHolidayCalendarRoute
  FeedbackRoute: typeof FeedbackRoute
  JavascriptRequiredRoute: typeof JavascriptRequiredRoute
  SearchResultsRoute: typeof SearchResultsRoute
  ServiceUnavailableRoute: typeof ServiceUnavailableRoute
  ServicesRoute: typeof ServicesRoute
  TellUsRoute: typeof TellUsRoute
  BusinessTradeCropOverPermitsFormRoute: typeof BusinessTradeCropOverPermitsFormRoute
  MoneyFinancialSupportCalculateSeverancePayFormRoute: typeof MoneyFinancialSupportCalculateSeverancePayFormRoute
  PensionsAndGratuitiesCalculateYourPensionFormRoute: typeof PensionsAndGratuitiesCalculateYourPensionFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tell-us': {
      id: '/tell-us'
      path: '/tell-us'
      fullPath: '/tell-us'
      preLoaderRoute: typeof TellUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-unavailable': {
      id: '/service-unavailable'
      path: '/service-unavailable'
      fullPath: '/service-unavailable'
      preLoaderRoute: typeof ServiceUnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-results': {
      id: '/search-results'
      path: '/search-results'
      fullPath: '/search-results'
      preLoaderRoute: typeof SearchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/javascript-required': {
      id: '/javascript-required'
      path: '/javascript-required'
      fullPath: '/javascript-required'
      preLoaderRoute: typeof JavascriptRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-holiday-calendar': {
      id: '/bank-holiday-calendar'
      path: '/bank-holiday-calendar'
      fullPath: '/bank-holiday-calendar'
      preLoaderRoute: typeof BankHolidayCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pensions-and-gratuities/calculate-your-pension/form': {
      id: '/pensions-and-gratuities/calculate-your-pension/form'
      path: '/pensions-and-gratuities/calculate-your-pension/form'
      fullPath: '/pensions-and-gratuities/calculate-your-pension/form'
      preLoaderRoute: typeof PensionsAndGratuitiesCalculateYourPensionFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-financial-support/calculate-severance-pay/form': {
      id: '/money-financial-support/calculate-severance-pay/form'
      path: '/money-financial-support/calculate-severance-pay/form'
      fullPath: '/money-financial-support/calculate-severance-pay/form'
      preLoaderRoute: typeof MoneyFinancialSupportCalculateSeverancePayFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-trade/crop-over-permits/form': {
      id: '/business-trade/crop-over-permits/form'
      path: '/business-trade/crop-over-permits/form'
      fullPath: '/business-trade/crop-over-permits/form'
      preLoaderRoute: typeof BusinessTradeCropOverPermitsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BankHolidayCalendarRoute: BankHolidayCalendarRoute,
  FeedbackRoute: FeedbackRoute,
  JavascriptRequiredRoute: JavascriptRequiredRoute,
  SearchResultsRoute: SearchResultsRoute,
  ServiceUnavailableRoute: ServiceUnavailableRoute,
  ServicesRoute: ServicesRoute,
  TellUsRoute: TellUsRoute,
  BusinessTradeCropOverPermitsFormRoute: BusinessTradeCropOverPermitsFormRoute,
  MoneyFinancialSupportCalculateSeverancePayFormRoute:
    MoneyFinancialSupportCalculateSeverancePayFormRoute,
  PensionsAndGratuitiesCalculateYourPensionFormRoute:
    PensionsAndGratuitiesCalculateYourPensionFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
