import { createServerFn } from "@tanstack/react-start";
import { getRequestHeaders } from "@tanstack/react-start/server";
import { z } from "zod";
import { type SessionPayload } from "./session";
import { getSession } from "./session-cipher.server";
import { getSessionSecret } from "./secrets";
import {
  deployBranchName,
  deployBranchPrefix,
  eraseBranchName,
  type ServiceContractRecipe,
  type ValidationResult,
} from "@govtech-bb/form-types";
import { api, ApiError } from "./api-client";
import { listVersions, RECIPES_BASE, compareSemver } from "./github-recipes";
import { bumpMinor } from "../lib/version";
import {
  repoUrl,
  authHeaders,
  ghError,
  createBranchFrom,
  deleteBranch,
  getContents,
  putFile,
  openPullRequest,
  listOpenPRHeads,
} from "./github";

const DEFAULT_BASE_BRANCH = "dev";

/**
 * The branch the Deploy PR is opened against, from `PUBLISH_BASE_BRANCH`.
 * Resolution order:
 *   1. The LIVE runtime env var — wins wherever the platform exposes it
 *      (docker, ECS, local node), so changing it retargets deploys with no
 *      rebuild. Read via bracket access on purpose: Vite's `define` only
 *      rewrites the literal `process.env.PUBLISH_BASE_BRANCH`, so the bracket
 *      form survives the build as a real runtime read instead of being inlined.
 *   2. The build-time baked value (`process.env.PUBLISH_BASE_BRANCH_DEFAULT`,
 *      substituted by Vite — see vite.config.ts `define`). This is the fallback
 *      for Amplify Compute, whose SSR Lambda doesn't receive runtime env vars;
 *      set PUBLISH_BASE_BRANCH in the Amplify console and redeploy to change it.
 *   3. `dev`.
 * This is the single source of truth; both `publishRecipe` and
 * `getPublishBaseBranch` use it, so the value the modal shows can never diverge
 * from the PR's actual base.
 */
export function resolveBaseBranch(): string {
  const runtime = process.env["PUBLISH_BASE_BRANCH"]?.trim();
  if (runtime) return runtime;
  return process.env.PUBLISH_BASE_BRANCH_DEFAULT?.trim() || DEFAULT_BASE_BRANCH;
}

/**
 * Mirrors forms.ts's `requireToken()` but returns the full session payload so
 * callers can access `session.login` in addition to `session.accessToken`.
 */
async function requireSession(): Promise<SessionPayload> {
  const headers = getRequestHeaders();
  const cookie =
    (headers as { get?: (k: string) => string | null }).get?.("cookie") ??
    (headers as { cookie?: string }).cookie ??
    null;
  const secret = await getSessionSecret();
  const session = getSession(cookie, secret);
  if (!session) throw new Error("Not authenticated");
  return session;
}

function renderPrBody({
  recipe,
  authorLogin,
  description,
}: {
  recipe: ServiceContractRecipe;
  authorLogin: string;
  description: string;
}): string {
  const stepCount = recipe.steps.length;
  const desc = description.trim();
  return [
    "## Form publish",
    "",
    `- Form: **${recipe.title}**`,
    `- Form ID: \`${recipe.formId}\``,
    `- Version: \`${recipe.version}\``,
    `- Steps: ${stepCount}`,
    `- Author: @${authorLogin}`,
    "",
    "### Description",
    "",
    desc.length > 0 ? desc : "_No description provided._",
    "",
    "---",
    "",
    "Generated by the form_builder Deploy flow.",
    "Recipe content is in the file diff for this PR.",
  ].join("\n");
}

export const publishRecipe = createServerFn({ method: "POST" })
  .inputValidator(
    z.object({
      recipe: z.unknown(),
      description: z.string().default(""),
    }),
  )
  .handler(async ({ data }): Promise<{ prUrl: string; prNumber: number }> => {
    const recipe = data.recipe as ServiceContractRecipe;
    const description = data.description ?? "";
    const session = await requireSession();
    const token = session.accessToken;
    const baseBranch = resolveBaseBranch();

    // Server-side gate (defense-in-depth): the Deploy button already runs this
    // client-side, but the client is bypassable — the server must be the
    // authority. Reuse the API's /validate endpoint, which resolves every ref
    // against the full catalog (builtins + registry + live custom components
    // from the DB) that this frontend can't reach directly. Refuse to open any
    // branch/PR if the recipe is unresolvable, so a bad ref never reaches the
    // repo (the hole behind #504).
    const validation = await api.post<ValidationResult>(
      "/builder/registry/validate",
      { recipe },
    );
    if (!validation.ok) {
      const detail = validation.issues
        .map((i) => (i.path ? `${i.path}: ${i.message}` : i.message))
        .join("; ");
      throw new Error(`Recipe validation failed: ${detail}`);
    }

    // Gate (#873): the deploy version must be strictly ahead of every version
    // already on the base branch. The client computes its bump from the DB
    // draft, which is blind to manual repo bumps — fail fast with the real
    // latest rather than opening a doomed PR.
    const published = await listVersions(token, recipe.formId, baseBranch);
    const notAhead = published.filter(
      (v) => compareSemver(v, recipe.version) >= 0,
    );
    if (notAhead.length > 0) {
      const latest = published.reduce((b, v) =>
        compareSemver(v, b) > 0 ? v : b,
      );
      throw new Error(
        `Version ${recipe.version} is not ahead of ${baseBranch} (latest published: ${latest}). ` +
          `Reopen the form to pick up the latest version, then deploy again.`,
      );
    }

    // Reservation (#873): atomically claim (formId, version) in the builder DB
    // before touching GitHub. POST /builder/forms 409s on the existing
    // UNIQUE(form_id, version), so two concurrent deploys serialize here. The
    // row doubles as the pending-deploy draft (other users' pickers see it) and
    // is deleted post-merge by the archive-merged-drafts workflow.
    try {
      // userLogin (#874): the reservation save now passes the read-only-lock
      // gate, so a non-holder is rejected here before any GitHub work.
      await api.post("/builder/forms", {
        recipe,
        isNew: false,
        userLogin: session.login,
      });
    } catch (err) {
      if (err instanceof ApiError && err.status === 409) {
        throw new Error(
          `Version ${recipe.version} was just claimed by another deploy or save — ` +
            `reopen the form and try again.`,
        );
      }
      throw err;
    }

    // Any failure past this point must release the claim (best-effort — the
    // delete-version endpoint only removes unpublished draft rows).
    const releaseReservation = async (): Promise<void> => {
      try {
        await api.del(
          `/builder/forms/${recipe.formId}/versions/${recipe.version}`,
        );
      } catch (releaseErr) {
        console.warn(
          `release of reservation ${recipe.formId}@${recipe.version} failed:`,
          releaseErr,
        );
      }
    };

    // Single release point (#873): ANY post-reservation failure — including
    // fetch rejections and malformed responses that never reach an !ok check —
    // must free the claimed (formId, version). The inner catch only handles
    // branch cleanup; its rethrow lands here.
    try {
      // Namespaced, dot-free branch (see deployBranchName, #805).
      const branch = deployBranchName(recipe.formId, recipe.version);
      await createBranchFrom(token, baseBranch, branch);

      // From here on, any failure must attempt to delete `branch`.
      try {
        // The file must not already exist. (Checking the new branch is
        // equivalent to checking base — the branch was just created from it.)
        const recipePath = `apps/api/src/forms/form-definitions/recipes/${recipe.formId}/${recipe.version}.json`;
        const checkRes = await getContents(token, recipePath, branch);
        if (checkRes.status === 200) {
          throw new Error(
            `Version ${recipe.version} already exists on ${baseBranch}. Reopen the form to pick up the latest version, then deploy again.`,
          );
        }
        if (checkRes.status !== 404) {
          throw await ghError("Failed to check existing recipe", checkRes);
        }

        const putRes = await putFile(token, {
          path: recipePath,
          message: `Publish ${recipe.formId} v${recipe.version}`,
          content: JSON.stringify(recipe, null, 2) + "\n",
          branch,
        });
        if (!putRes.ok) {
          throw await ghError("Failed to write recipe file", putRes);
        }

        return await openPullRequest(token, {
          base: baseBranch,
          head: branch,
          title: `Publish form: ${recipe.title} v${recipe.version}`,
          body: renderPrBody({
            recipe,
            authorLogin: session.login,
            description,
          }),
        });
      } catch (err) {
        await deleteBranch(branch, token);
        throw err;
      }
    } catch (err) {
      await releaseReservation();
      throw err;
    }
  });

/**
 * Exposes the runtime-resolved Deploy base branch to the client. The builder
 * route's loader awaits this so the Deploy modal can show the actual branch
 * name. It's a `createServerFn` (not a plain loader read of `process.env`)
 * because the loader also runs in the browser on client-side navigation, where
 * `process.env.PUBLISH_BASE_BRANCH` would be `undefined`.
 */
export const getPublishBaseBranch = createServerFn({ method: "GET" }).handler(
  async (): Promise<string> => resolveBaseBranch(),
);

/**
 * Versions claimed by OPEN deploy PRs for this form on the base branch (#873).
 * Recognised by the deploy branch naming scheme
 * (`form-builder/<formId>-<v1-v2-v3>-<ts>`); a branch that fails to parse is
 * skipped (fail-open — the CI recipe-version-guard is the merge-time backstop).
 */
async function listOpenDeployClaims(
  token: string,
  formId: string,
  baseBranch: string,
): Promise<string[]> {
  const prefix = deployBranchPrefix(formId);
  const claims: string[] = [];
  for (const pr of await listOpenPRHeads(token, baseBranch)) {
    if (!pr.headRef.startsWith(prefix)) continue;
    const m = /^(\d+)-(\d+)-(\d+)-\d+$/.exec(pr.headRef.slice(prefix.length));
    if (m) claims.push(`${m[1]}.${m[2]}.${m[3]}`);
  }
  return claims;
}

/**
 * The next safe Deploy version for a form (#873): one minor bump past the
 * highest of (a) the builder's loaded version, (b) every version on the base
 * branch, and (c) every version claimed by an open deploy PR. Replaces the
 * client-only `bumpMinor(currentVersion)`, which is blind to manual repo bumps
 * and to other users' in-flight deploys.
 */
export const getNextDeployVersion = createServerFn({ method: "GET" })
  .inputValidator(
    z.object({
      formId: z.string().min(1),
      currentVersion: z.string().nullable(),
    }),
  )
  .handler(async ({ data }): Promise<{ version: string }> => {
    const session = await requireSession();
    const token = session.accessToken;
    const baseBranch = resolveBaseBranch();

    const published = await listVersions(token, data.formId, baseBranch);
    const claimed = await listOpenDeployClaims(token, data.formId, baseBranch);
    const all = [...published, ...claimed];
    if (data.currentVersion) all.push(data.currentVersion);
    if (all.length === 0) return { version: "1.0.0" };
    const highest = all.reduce((best, v) =>
      compareSemver(v, best) > 0 ? v : best,
    );
    return { version: bumpMinor(highest) };
  });

function renderErasePrBody({
  formId,
  title,
  versions,
  authorLogin,
  reason,
}: {
  formId: string;
  title: string;
  versions: string[];
  authorLogin: string;
  reason: string;
}): string {
  const r = reason.trim();
  return [
    "## Form erase",
    "",
    `- Form: **${title || formId}**`,
    `- Form ID: \`${formId}\``,
    `- Versions removed: ${versions.map((v) => `\`${v}\``).join(", ")}`,
    `- Author: @${authorLogin}`,
    "",
    "### Reason",
    "",
    r.length > 0 ? r : "_No reason provided._",
    "",
    "---",
    "",
    "Generated by the form_builder Erase flow.",
    "This PR deletes the form's on-disk recipe folder — the diff is solely the removed files.",
  ].join("\n");
}

/**
 * The inverse of `publishRecipe`: opens a review PR that permanently removes a
 * live published form's on-disk recipe folder
 * (`apps/api/src/forms/form-definitions/recipes/<formId>/`). See issue #599.
 *
 * Removal mechanism — the Git Data API (one commit): rather than N per-file
 * Contents-API deletes (each its own commit + blob-SHA juggling), build a
 * single tree off the base tip with every version file set to `sha: null`
 * (GitHub treats a null `sha` in create-tree as a delete), create one commit,
 * and point the branch at it. The resulting PR diff is solely the deleted folder.
 *
 * Server-side gates (the client buttons are bypassable, so the server is the
 * authority): refuse if the form is **disabled** — Erase is offered only on
 * LIVE published forms, which sidesteps the tombstone-vs-merge timing hazard
 * entirely (no tombstone to clear) — and refuse if the folder has **no
 * versions** (nothing published to erase). Either refusal happens before any
 * branch is created.
 */
export const eraseRecipe = createServerFn({ method: "POST" })
  .inputValidator(
    // Erase is strictly more destructive than the reversible Disable, so its
    // server-side validation is at least as strict: a non-empty formId and a
    // non-empty, bounded reason (parity with forms.ts `disableForm`). The
    // client modal already enforces this, but the client is bypassable and the
    // reason is the audit trail for a permanent deletion.
    z.object({
      formId: z.string().min(1),
      title: z.string().default(""),
      reason: z.string().min(1).max(2000),
    }),
  )
  .handler(async ({ data }): Promise<{ prUrl: string; prNumber: number }> => {
    const { formId } = data;
    const title = data.title ?? "";

    // The inputValidator above enforces this on the RPC path, but a direct
    // (in-process) call bypasses it, so re-check in the handler: the reason is
    // the audit trail for a permanent deletion and must be present and bounded.
    const reason = (data.reason ?? "").trim();
    if (!reason) {
      throw new Error("A reason is required to erase a form.");
    }
    if (reason.length > 2000) {
      throw new Error("Erase reason must be 2000 characters or fewer.");
    }

    const session = await requireSession();
    const token = session.accessToken;
    const baseBranch = resolveBaseBranch();

    // Gate 1: never erase a disabled form. A disabled form must be Enabled
    // first; restricting Erase to live forms means there is no tombstone to
    // clear (see #599 / #576).
    const disabled = await api.get<string[]>("/builder/forms/disabled");
    if (disabled.includes(formId)) {
      throw new Error(
        `Form "${formId}" is disabled — Enable it before erasing.`,
      );
    }

    // Gate 2: there must be something on disk to erase. List the folder's
    // version files on the base branch (reuses the publish read path).
    const versions = await listVersions(token, formId, baseBranch);
    if (versions.length === 0) {
      throw new Error(
        `No published recipe found for "${formId}" on ${baseBranch} — nothing to erase.`,
      );
    }

    const branch = eraseBranchName(formId);
    const baseSha = await createBranchFrom(token, baseBranch, branch);

    // From here on, any failure must attempt to delete `branch`.
    try {
      // Read the base commit to get its tree SHA.
      const commitRes = await fetch(repoUrl(`/git/commits/${baseSha}`), {
        headers: authHeaders(token),
      });
      if (!commitRes.ok) {
        throw await ghError("Failed to read base commit", commitRes);
      }
      const baseTreeSha = (
        (await commitRes.json()) as {
          tree: { sha: string };
        }
      ).tree.sha;

      // Create a tree off the base tree with every version file deleted
      // (a null `sha` removes the path).
      const treeRes = await fetch(repoUrl("/git/trees"), {
        method: "POST",
        headers: { ...authHeaders(token), "Content-Type": "application/json" },
        body: JSON.stringify({
          base_tree: baseTreeSha,
          tree: versions.map((v) => ({
            path: `${RECIPES_BASE}/${formId}/${v}.json`,
            mode: "100644",
            type: "blob",
            sha: null,
          })),
        }),
      });
      if (!treeRes.ok) {
        throw await ghError("Failed to create tree", treeRes);
      }
      const newTreeSha = ((await treeRes.json()) as { sha: string }).sha;

      // Create the commit parented on the base tip.
      const commitCreateRes = await fetch(repoUrl("/git/commits"), {
        method: "POST",
        headers: { ...authHeaders(token), "Content-Type": "application/json" },
        body: JSON.stringify({
          message: `Erase form: ${formId}`,
          tree: newTreeSha,
          parents: [baseSha],
        }),
      });
      if (!commitCreateRes.ok) {
        throw await ghError("Failed to create commit", commitCreateRes);
      }
      const newCommitSha = ((await commitCreateRes.json()) as { sha: string })
        .sha;

      // Fast-forward the branch ref to the new commit.
      const patchRes = await fetch(repoUrl(`/git/refs/heads/${branch}`), {
        method: "PATCH",
        headers: { ...authHeaders(token), "Content-Type": "application/json" },
        body: JSON.stringify({ sha: newCommitSha }),
      });
      if (!patchRes.ok) {
        throw await ghError("Failed to update branch ref", patchRes);
      }

      return await openPullRequest(token, {
        base: baseBranch,
        head: branch,
        title: `Erase form: ${title || formId} (${formId})`,
        body: renderErasePrBody({
          formId,
          title,
          versions,
          authorLogin: session.login,
          reason,
        }),
      });
    } catch (err) {
      await deleteBranch(branch, token);
      throw err;
    }
  });
