import { createServerFn } from "@tanstack/react-start";
import { getRequestHeaders } from "@tanstack/react-start/server";
import { z } from "zod";
import { type SessionPayload } from "./session";
import { getSession } from "./session-cipher.server";
import { getSessionSecret } from "./secrets";
import {
  deployBranchName,
  eraseBranchName,
  kebabIdSchema,
  KEBAB_ID_PATTERN,
  KEBAB_ID_ERROR,
  type ServiceContractRecipe,
  type ValidationResult,
} from "@govtech-bb/form-types";
import { api, ApiError } from "./api-client";
import { listVersions, RECIPES_BASE } from "./github-recipes";
import {
  repoUrl,
  authHeaders,
  ghError,
  createBranchFrom,
  deleteBranch,
  getContents,
  createdAtFromContents,
  putFile,
  openPullRequest,
} from "./github";

const DEFAULT_BASE_BRANCH = "dev";

/**
 * The branch the Deploy PR is opened against, from `PUBLISH_BASE_BRANCH`.
 * Resolution order:
 *   1. The LIVE runtime env var — wins wherever the platform exposes it
 *      (docker, ECS, local node), so changing it retargets deploys with no
 *      rebuild. Read via bracket access on purpose: Vite's `define` only
 *      rewrites the literal `process.env.PUBLISH_BASE_BRANCH`, so the bracket
 *      form survives the build as a real runtime read instead of being inlined.
 *   2. The build-time baked value (`process.env.PUBLISH_BASE_BRANCH_DEFAULT`,
 *      substituted by Vite — see vite.config.ts `define`). This is the fallback
 *      for Amplify Compute, whose SSR Lambda doesn't receive runtime env vars;
 *      set PUBLISH_BASE_BRANCH in the Amplify console and redeploy to change it.
 *   3. `dev`.
 * This is the single source of truth; both `publishRecipe` and
 * `getPublishBaseBranch` use it, so the value the modal shows can never diverge
 * from the PR's actual base.
 */
export function resolveBaseBranch(): string {
  const runtime = process.env["PUBLISH_BASE_BRANCH"]?.trim();
  if (runtime) return runtime;
  return process.env.PUBLISH_BASE_BRANCH_DEFAULT?.trim() || DEFAULT_BASE_BRANCH;
}

/**
 * Mirrors forms.ts's `requireToken()` but returns the full session payload so
 * callers can access `session.login` in addition to `session.accessToken`.
 */
async function requireSession(): Promise<SessionPayload> {
  const headers = getRequestHeaders();
  const cookie =
    (headers as { get?: (k: string) => string | null }).get?.("cookie") ??
    (headers as { cookie?: string }).cookie ??
    null;
  const secret = await getSessionSecret();
  const session = getSession(cookie, secret);
  if (!session) throw new Error("Not authenticated");
  return session;
}

function renderPrBody({
  recipe,
  authorLogin,
  description,
}: {
  recipe: ServiceContractRecipe;
  authorLogin: string;
  description: string;
}): string {
  const stepCount = recipe.steps.length;
  const desc = description.trim();
  return [
    "## Form publish",
    "",
    `- Form: **${recipe.title}**`,
    `- Form ID: \`${recipe.formId}\``,
    `- Steps: ${stepCount}`,
    `- Author: @${authorLogin}`,
    "",
    "### Description",
    "",
    desc.length > 0 ? desc : "_No description provided._",
    "",
    "---",
    "",
    "Generated by the form_builder Deploy flow.",
    "Recipe content is in the file diff for this PR.",
  ].join("\n");
}

export const publishRecipe = createServerFn({ method: "POST" })
  .inputValidator(
    z.object({
      recipe: z.unknown(),
      description: z.string().default(""),
    }),
  )
  .handler(async ({ data }): Promise<{ prUrl: string; prNumber: number }> => {
    const recipe = data.recipe as ServiceContractRecipe;
    const description = data.description ?? "";

    // Security gate (#293): `recipe` enters as `z.unknown()`, so before its
    // formId is interpolated into the GitHub recipe path or branch name, assert
    // it's a plain kebab-case id. A value like `../../../.github/workflows/evil`
    // would otherwise escape the recipes folder. This is a local, independent
    // check — the remote /validate call below resolves refs, not id format — and
    // the encodeURIComponent at the path sink is the second layer.
    if (!KEBAB_ID_PATTERN.test(recipe?.formId)) {
      throw new Error(`Invalid form ID. ${KEBAB_ID_ERROR}`);
    }

    const session = await requireSession();
    const token = session.accessToken;
    const baseBranch = resolveBaseBranch();

    // Server-side gate (defense-in-depth): the Deploy button already runs this
    // client-side, but the client is bypassable — the server must be the
    // authority. Reuse the API's /validate endpoint, which resolves every ref
    // against the full catalog (builtins + registry + live custom components
    // from the DB) that this frontend can't reach directly. Refuse to open any
    // branch/PR if the recipe is unresolvable, so a bad ref never reaches the
    // repo (the hole behind #504).
    const validation = await api.post<ValidationResult>(
      "/builder/registry/validate",
      { recipe },
    );
    if (!validation.ok) {
      const detail = validation.issues
        .map((i) => (i.path ? `${i.path}: ${i.message}` : i.message))
        .join("; ");
      throw new Error(`Recipe validation failed: ${detail}`);
    }

    // Persist the current draft and enforce the read-only lock (#874) before
    // touching GitHub: PUT /builder/forms/:formId runs through enforcePresence,
    // so a non-holder is rejected (409) here. (#1196: recipe versioning is
    // retired — there is no version reservation; publish overwrites the single
    // canonical flat file.)
    try {
      await api.put(`/builder/forms/${recipe.formId}`, {
        recipe,
        userLogin: session.login,
      });
    } catch (err) {
      if (err instanceof ApiError && err.status === 409) {
        throw new Error(
          "Another editor holds this form. Your session is read-only until their claim expires.",
        );
      }
      throw err;
    }

    // Namespaced, dot-free branch (see deployBranchName, #805).
    const branch = deployBranchName(recipe.formId);
    await createBranchFrom(token, baseBranch, branch);

    // From here on, any failure must attempt to delete `branch`.
    try {
      // Overwrite the canonical flat recipe file in place. It already exists on
      // the base branch (and so on this branch), so fetch its blob SHA — the
      // Contents API requires `sha` to update an existing file. The same
      // response carries the committed file's content, so preserve its original
      // `createdAt` rather than restamping it (#1720); `updatedAt` stays at the
      // freshly-serialized value. On first publish (no existing file) the recipe
      // is written verbatim with both stamps minted. encodeURIComponent on the
      // formId segment is defense-in-depth at the sink (#293) — a no-op for the
      // kebab id the guard above already enforced.
      const recipePath = `apps/api/src/forms/form-definitions/recipes/${encodeURIComponent(
        recipe.formId,
      )}.json`;
      const existing = await getContents(token, recipePath, branch);
      let existingSha: string | undefined;
      let preservedCreatedAt: string | undefined;
      if (existing.status === 200) {
        const body = (await existing.json()) as {
          sha?: string;
          content?: string;
        };
        existingSha = body.sha;
        preservedCreatedAt = createdAtFromContents(body);
      }
      const recipeToPublish = preservedCreatedAt
        ? { ...recipe, createdAt: preservedCreatedAt }
        : recipe;

      const putRes = await putFile(token, {
        path: recipePath,
        message: `Publish ${recipe.formId}`,
        content: JSON.stringify(recipeToPublish, null, 2) + "\n",
        branch,
        ...(existingSha ? { sha: existingSha } : {}),
      });
      if (!putRes.ok) {
        throw await ghError("Failed to write recipe file", putRes);
      }

      return await openPullRequest(token, {
        base: baseBranch,
        head: branch,
        title: `Publish form: ${recipe.title}`,
        body: renderPrBody({
          recipe,
          authorLogin: session.login,
          description,
        }),
      });
    } catch (err) {
      await deleteBranch(branch, token);
      throw err;
    }
  });

/**
 * Exposes the runtime-resolved Deploy base branch to the client. The builder
 * route's loader awaits this so the Deploy modal can show the actual branch
 * name. It's a `createServerFn` (not a plain loader read of `process.env`)
 * because the loader also runs in the browser on client-side navigation, where
 * `process.env.PUBLISH_BASE_BRANCH` would be `undefined`.
 */
export const getPublishBaseBranch = createServerFn({ method: "GET" }).handler(
  async (): Promise<string> => resolveBaseBranch(),
);

function renderErasePrBody({
  formId,
  title,
  versions,
  authorLogin,
  reason,
}: {
  formId: string;
  title: string;
  versions: string[];
  authorLogin: string;
  reason: string;
}): string {
  const r = reason.trim();
  return [
    "## Form erase",
    "",
    `- Form: **${title || formId}**`,
    `- Form ID: \`${formId}\``,
    `- Versions removed: ${versions.map((v) => `\`${v}\``).join(", ")}`,
    `- Author: @${authorLogin}`,
    "",
    "### Reason",
    "",
    r.length > 0 ? r : "_No reason provided._",
    "",
    "---",
    "",
    "Generated by the form_builder Erase flow.",
    "This PR deletes the form's on-disk recipe folder — the diff is solely the removed files.",
  ].join("\n");
}

/**
 * The inverse of `publishRecipe`: opens a review PR that permanently removes a
 * live published form's on-disk recipe folder
 * (`apps/api/src/forms/form-definitions/recipes/<formId>/`). See issue #599.
 *
 * Removal mechanism — the Git Data API (one commit): rather than N per-file
 * Contents-API deletes (each its own commit + blob-SHA juggling), build a
 * single tree off the base tip with every version file set to `sha: null`
 * (GitHub treats a null `sha` in create-tree as a delete), create one commit,
 * and point the branch at it. The resulting PR diff is solely the deleted folder.
 *
 * Server-side gates (the client buttons are bypassable, so the server is the
 * authority): refuse if the form is **disabled** — Erase is offered only on
 * LIVE published forms, which sidesteps the tombstone-vs-merge timing hazard
 * entirely (no tombstone to clear) — and refuse if the folder has **no
 * versions** (nothing published to erase). Either refusal happens before any
 * branch is created.
 */
export const eraseRecipe = createServerFn({ method: "POST" })
  .inputValidator(
    // Erase is strictly more destructive than the reversible Disable, so its
    // server-side validation is at least as strict: a non-empty formId and a
    // non-empty, bounded reason (parity with forms.ts `disableForm`). The
    // client modal already enforces this, but the client is bypassable and the
    // reason is the audit trail for a permanent deletion.
    z.object({
      // formId is interpolated into a GitHub path + branch name; pin it
      // to a kebab-case id so a traversal value can't escape the recipes folder.
      formId: kebabIdSchema,
      title: z.string().default(""),
      reason: z.string().min(1).max(2000),
    }),
  )
  .handler(async ({ data }): Promise<{ prUrl: string; prNumber: number }> => {
    const { formId } = data;
    const title = data.title ?? "";

    // The inputValidator above enforces this on the RPC path, but a direct
    // (in-process) call bypasses it, so re-check in the handler: the reason is
    // the audit trail for a permanent deletion and must be present and bounded.
    const reason = (data.reason ?? "").trim();
    if (!reason) {
      throw new Error("A reason is required to erase a form.");
    }
    if (reason.length > 2000) {
      throw new Error("Erase reason must be 2000 characters or fewer.");
    }
    // formId is interpolated into a GitHub path + branch name; re-check format
    // here too since a direct (in-process) call bypasses the inputValidator.
    if (!KEBAB_ID_PATTERN.test(formId)) {
      throw new Error(`Invalid form ID. ${KEBAB_ID_ERROR}`);
    }

    const session = await requireSession();
    const token = session.accessToken;
    const baseBranch = resolveBaseBranch();

    // Gate 1: never erase a disabled form. A disabled form must be Enabled
    // first; restricting Erase to live forms means there is no tombstone to
    // clear (see #599 / #576).
    const disabled = await api.get<string[]>("/builder/forms/disabled");
    if (disabled.includes(formId)) {
      throw new Error(
        `Form "${formId}" is disabled — Enable it before erasing.`,
      );
    }

    // Gate 2: there must be something on disk to erase. List the folder's
    // version files on the base branch (reuses the publish read path).
    // NOTE (#1196): erase still targets the legacy versioned dir; removing the
    // flat `recipes/{formId}.json` is deferred to the Phase-2 decommission when
    // the legacy dirs go away. Erase is rare and the dirs are retained through
    // Phase 1, so this stays correct in the interim.
    const versions = await listVersions(token, formId, baseBranch);
    if (versions.length === 0) {
      throw new Error(
        `No published recipe found for "${formId}" on ${baseBranch} — nothing to erase.`,
      );
    }

    const branch = eraseBranchName(formId);
    const baseSha = await createBranchFrom(token, baseBranch, branch);

    // From here on, any failure must attempt to delete `branch`.
    try {
      // Read the base commit to get its tree SHA.
      const commitRes = await fetch(repoUrl(`/git/commits/${baseSha}`), {
        headers: authHeaders(token),
      });
      if (!commitRes.ok) {
        throw await ghError("Failed to read base commit", commitRes);
      }
      const baseTreeSha = (
        (await commitRes.json()) as {
          tree: { sha: string };
        }
      ).tree.sha;

      // Create a tree off the base tree with every version file deleted
      // (a null `sha` removes the path).
      const treeRes = await fetch(repoUrl("/git/trees"), {
        method: "POST",
        headers: { ...authHeaders(token), "Content-Type": "application/json" },
        body: JSON.stringify({
          base_tree: baseTreeSha,
          tree: versions.map((v) => ({
            // Encode each user-provided segment; a no-op for the
            // kebab/semver values already enforced above.
            path: `${RECIPES_BASE}/${encodeURIComponent(
              formId,
            )}/${encodeURIComponent(v)}.json`,
            mode: "100644",
            type: "blob",
            sha: null,
          })),
        }),
      });
      if (!treeRes.ok) {
        throw await ghError("Failed to create tree", treeRes);
      }
      const newTreeSha = ((await treeRes.json()) as { sha: string }).sha;

      // Create the commit parented on the base tip.
      const commitCreateRes = await fetch(repoUrl("/git/commits"), {
        method: "POST",
        headers: { ...authHeaders(token), "Content-Type": "application/json" },
        body: JSON.stringify({
          message: `Erase form: ${formId}`,
          tree: newTreeSha,
          parents: [baseSha],
        }),
      });
      if (!commitCreateRes.ok) {
        throw await ghError("Failed to create commit", commitCreateRes);
      }
      const newCommitSha = ((await commitCreateRes.json()) as { sha: string })
        .sha;

      // Fast-forward the branch ref to the new commit.
      const patchRes = await fetch(repoUrl(`/git/refs/heads/${branch}`), {
        method: "PATCH",
        headers: { ...authHeaders(token), "Content-Type": "application/json" },
        body: JSON.stringify({ sha: newCommitSha }),
      });
      if (!patchRes.ok) {
        throw await ghError("Failed to update branch ref", patchRes);
      }

      return await openPullRequest(token, {
        base: baseBranch,
        head: branch,
        title: `Erase form: ${title || formId} (${formId})`,
        body: renderErasePrBody({
          formId,
          title,
          versions,
          authorLogin: session.login,
          reason,
        }),
      });
    } catch (err) {
      await deleteBranch(branch, token);
      throw err;
    }
  });
