import { createServerFn } from "@tanstack/react-start";
import { getRequestHeaders } from "@tanstack/react-start/server";
import { z } from "zod";
import { type SessionPayload } from "./session";
import { getSession } from "./session-cipher.server";
import type {
  ServiceContractRecipe,
  ValidationResult,
} from "@govtech-bb/form-types";
import { api } from "./api-client";

const REPO_NAME = "gov-bb";
const DEFAULT_BASE_BRANCH = "dev";
const GH_API = "https://api.github.com";

/**
 * The branch the Deploy PR is opened against, from `PUBLISH_BASE_BRANCH`.
 * Resolution order:
 *   1. The LIVE runtime env var — wins wherever the platform exposes it
 *      (docker, ECS, local node), so changing it retargets deploys with no
 *      rebuild. Read via bracket access on purpose: Vite's `define` only
 *      rewrites the literal `process.env.PUBLISH_BASE_BRANCH`, so the bracket
 *      form survives the build as a real runtime read instead of being inlined.
 *   2. The build-time baked value (`process.env.PUBLISH_BASE_BRANCH_DEFAULT`,
 *      substituted by Vite — see vite.config.ts `define`). This is the fallback
 *      for Amplify Compute, whose SSR Lambda doesn't receive runtime env vars;
 *      set PUBLISH_BASE_BRANCH in the Amplify console and redeploy to change it.
 *   3. `dev`.
 * This is the single source of truth; both `publishRecipe` and
 * `getPublishBaseBranch` use it, so the value the modal shows can never diverge
 * from the PR's actual base.
 */
function resolveBaseBranch(): string {
  const runtime = process.env["PUBLISH_BASE_BRANCH"]?.trim();
  if (runtime) return runtime;
  return process.env.PUBLISH_BASE_BRANCH_DEFAULT?.trim() || DEFAULT_BASE_BRANCH;
}

function repoOwner(): string {
  const v = process.env.GITHUB_ORG;
  if (!v) throw new Error("GITHUB_ORG is not set");
  return v;
}

function repoUrl(suffix: string): string {
  return `${GH_API}/repos/${repoOwner()}/${REPO_NAME}${suffix}`;
}

function authHeaders(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

async function ghError(label: string, res: Response): Promise<Error> {
  let body = "";
  try {
    body = await res.text();
  } catch {
    /* ignore */
  }
  return new Error(`${label} (status ${res.status}): ${body.slice(0, 500)}`);
}

/**
 * Mirrors forms.ts's `requireToken()` but returns the full session payload so
 * callers can access `session.login` in addition to `session.accessToken`.
 */
function requireSession(): SessionPayload {
  const headers = getRequestHeaders();
  const cookie =
    (headers as { get?: (k: string) => string | null }).get?.("cookie") ??
    (headers as { cookie?: string }).cookie ??
    null;
  const secret = process.env.SESSION_SECRET;
  if (!secret) throw new Error("SESSION_SECRET is not set");
  const session = getSession(cookie, secret);
  if (!session) throw new Error("Not authenticated");
  return session;
}

function renderPrBody({
  recipe,
  authorLogin,
  description,
}: {
  recipe: ServiceContractRecipe;
  authorLogin: string;
  description: string;
}): string {
  const stepCount = recipe.steps.length;
  const desc = description.trim();
  return [
    "## Form publish",
    "",
    `- Form: **${recipe.title}**`,
    `- Form ID: \`${recipe.formId}\``,
    `- Version: \`${recipe.version}\``,
    `- Steps: ${stepCount}`,
    `- Author: @${authorLogin}`,
    "",
    "### Description",
    "",
    desc.length > 0 ? desc : "_No description provided._",
    "",
    "---",
    "",
    "Generated by the form_builder Deploy flow.",
    "Recipe content is in the file diff for this PR.",
  ].join("\n");
}

async function deleteBranch(branch: string, token: string): Promise<void> {
  try {
    await fetch(repoUrl(`/git/refs/heads/${branch}`), {
      method: "DELETE",
      headers: authHeaders(token),
    });
  } catch (err) {
    // Best-effort cleanup. Log and swallow.
    console.warn(
      `publishRecipe: cleanup DELETE failed for branch ${branch}:`,
      err,
    );
  }
}

export const publishRecipe = createServerFn({ method: "POST" })
  .inputValidator(
    z.object({
      recipe: z.unknown(),
      description: z.string().default(""),
    }),
  )
  .handler(async ({ data }): Promise<{ prUrl: string; prNumber: number }> => {
    const recipe = data.recipe as ServiceContractRecipe;
    const description = data.description ?? "";
    const session = requireSession();
    const token = session.accessToken;
    const baseBranch = resolveBaseBranch();

    // Server-side gate (defense-in-depth): the Deploy button already runs this
    // client-side, but the client is bypassable — the server must be the
    // authority. Reuse the API's /validate endpoint, which resolves every ref
    // against the full catalog (builtins + registry + live custom components
    // from the DB) that this frontend can't reach directly. Refuse to open any
    // branch/PR if the recipe is unresolvable, so a bad ref never reaches the
    // repo (the hole behind #504).
    const validation = await api.post<ValidationResult>(
      "/builder/registry/validate",
      { recipe },
    );
    if (!validation.ok) {
      const detail = validation.issues
        .map((i) => (i.path ? `${i.path}: ${i.message}` : i.message))
        .join("; ");
      throw new Error(`Recipe validation failed: ${detail}`);
    }

    // Step 1: get base branch tip SHA
    const refRes = await fetch(repoUrl(`/git/ref/heads/${baseBranch}`), {
      headers: authHeaders(token),
    });
    if (!refRes.ok) {
      throw await ghError(`Failed to read ${baseBranch} branch`, refRes);
    }
    const refJson = (await refRes.json()) as { object: { sha: string } };
    const baseSha = refJson.object.sha;

    // Step 2: create namespaced branch
    const branch = `form-builder/${recipe.formId}-${recipe.version}-${Date.now()}`;
    const createRefRes = await fetch(repoUrl("/git/refs"), {
      method: "POST",
      headers: { ...authHeaders(token), "Content-Type": "application/json" },
      body: JSON.stringify({
        ref: `refs/heads/${branch}`,
        sha: baseSha,
      }),
    });
    if (!createRefRes.ok) {
      throw await ghError("Failed to create branch", createRefRes);
    }

    // From here on, any failure must attempt to delete `branch`.
    try {
      // Step 3: check the file doesn't already exist on the new branch.
      // (Checking on the base branch would be equivalent because the branch was
      // just created from it; we use the new branch so the URL pattern matches
      // step 4.)
      const contentsPath = `/contents/apps/api/src/forms/form-definitions/recipes/${recipe.formId}/${recipe.version}.json`;
      const checkRes = await fetch(
        repoUrl(`${contentsPath}?ref=${encodeURIComponent(branch)}`),
        { headers: authHeaders(token) },
      );
      if (checkRes.status === 200) {
        throw new Error(
          `Version ${recipe.version} already exists on ${baseBranch}. Bump the version and try again.`,
        );
      }
      if (checkRes.status !== 404) {
        throw await ghError("Failed to check existing recipe", checkRes);
      }

      // Step 4: write the file
      const fileContent = JSON.stringify(recipe, null, 2) + "\n";
      const putRes = await fetch(repoUrl(contentsPath), {
        method: "PUT",
        headers: {
          ...authHeaders(token),
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: `Publish ${recipe.formId} v${recipe.version}`,
          content: Buffer.from(fileContent, "utf8").toString("base64"),
          branch,
        }),
      });
      if (!putRes.ok) {
        throw await ghError("Failed to write recipe file", putRes);
      }

      // Step 5: open the PR
      const prRes = await fetch(repoUrl("/pulls"), {
        method: "POST",
        headers: {
          ...authHeaders(token),
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          base: baseBranch,
          head: branch,
          title: `Publish form: ${recipe.title} v${recipe.version}`,
          body: renderPrBody({
            recipe,
            authorLogin: session.login,
            description,
          }),
        }),
      });
      if (!prRes.ok) {
        throw await ghError("Failed to open pull request", prRes);
      }
      const prJson = (await prRes.json()) as {
        number: number;
        html_url: string;
      };
      return { prUrl: prJson.html_url, prNumber: prJson.number };
    } catch (err) {
      await deleteBranch(branch, token);
      throw err;
    }
  });

/**
 * Exposes the runtime-resolved Deploy base branch to the client. The builder
 * route's loader awaits this so the Deploy modal can show the actual branch
 * name. It's a `createServerFn` (not a plain loader read of `process.env`)
 * because the loader also runs in the browser on client-side navigation, where
 * `process.env.PUBLISH_BASE_BRANCH` would be `undefined`.
 */
export const getPublishBaseBranch = createServerFn({ method: "GET" }).handler(
  async (): Promise<string> => resolveBaseBranch(),
);
