// GENERATED by scripts/generate-service-status-seed.ts — do not edit by hand.
// Regenerate with `pnpm generate:service-status-seed` when landing content or
// recipe visibility changes. Consumed only by the SeedServiceStatus migration.
import type { ServiceStatus } from "../entities";

export const SERVICE_STATUS_SEED_ROWS: {
  slug: string;
  status: `${ServiceStatus}`;
}[] = [
  {
    slug: "application-for-job-letter-ministry-of-education",
    status: "disabled",
  },
  {
    slug: "apply-financial-assistance",
    status: "enabled",
  },
  {
    slug: "apply-for-a-place-at-a-day-nursery",
    status: "enabled",
  },
  {
    slug: "apply-for-a-sixth-form-placement",
    status: "disabled",
  },
  {
    slug: "apply-for-a-special-education-bursary",
    status: "disabled",
  },
  {
    slug: "apply-for-conductor-licence",
    status: "form_disabled",
  },
  {
    slug: "apply-for-exemption-from-school-attendance",
    status: "disabled",
  },
  {
    slug: "apply-for-national-summer-camp-programme",
    status: "disabled",
  },
  {
    slug: "apply-for-national-summer-camp-programme-tropical-trails-and-tales-science-camp-2026",
    status: "disabled",
  },
  {
    slug: "apply-to-the-barbados-youthadvance-corps",
    status: "enabled",
  },
  {
    slug: "apply-to-volunteer-at-a-sports-camp",
    status: "enabled",
  },
  {
    slug: "barbados-secondary-entrance-exam-choice",
    status: "disabled",
  },
  {
    slug: "bssee-form-a-pupil-under-11-request",
    status: "disabled",
  },
  {
    slug: "bssee-form-b-defer-examination",
    status: "disabled",
  },
  {
    slug: "calculate-severance-pay",
    status: "enabled",
  },
  {
    slug: "calculate-your-pension",
    status: "disabled",
  },
  {
    slug: "camp-director-application",
    status: "disabled",
  },
  {
    slug: "cape-exam-registration-2024",
    status: "disabled",
  },
  {
    slug: "chat-feedback",
    status: "disabled",
  },
  {
    slug: "community-elder-care-programme-application",
    status: "disabled",
  },
  {
    slug: "crop-over-permits",
    status: "enabled",
  },
  {
    slug: "csec-private-candidate-registration",
    status: "disabled",
  },
  {
    slug: "cyber-security-training",
    status: "disabled",
  },
  {
    slug: "digital-media-training-programme-application",
    status: "disabled",
  },
  {
    slug: "driver-licence-renewal",
    status: "disabled",
  },
  {
    slug: "duties-performed-exam-claim",
    status: "disabled",
  },
  {
    slug: "exit-survey",
    status: "disabled",
  },
  {
    slug: "get-a-document-notarised",
    status: "enabled",
  },
  {
    slug: "get-a-primary-school-textbook-grant",
    status: "form_disabled",
  },
  {
    slug: "get-birth-certificate",
    status: "enabled",
  },
  {
    slug: "get-death-certificate",
    status: "enabled",
  },
  {
    slug: "get-disaster-relief-assistance",
    status: "enabled",
  },
  {
    slug: "get-marriage-certificate",
    status: "enabled",
  },
  {
    slug: "get-support-for-a-victim-of-domestic-abuse",
    status: "enabled",
  },
  {
    slug: "health-and-emergency-services/stormready",
    status: "enabled",
  },
  {
    slug: "home-care-programme-services",
    status: "disabled",
  },
  {
    slug: "homeschooling-application-2024",
    status: "disabled",
  },
  {
    slug: "jobstart-plus-programme",
    status: "enabled",
  },
  {
    slug: "loud-music-permit",
    status: "enabled",
  },
  {
    slug: "ministry-of-eduction-application-for-job-letter",
    status: "disabled",
  },
  {
    slug: "mission-barbados",
    status: "disabled",
  },
  {
    slug: "mohlm-application-use-state-land",
    status: "disabled",
  },
  {
    slug: "multiple-birth-benefit-application",
    status: "disabled",
  },
  {
    slug: "national-assistance-grant-application",
    status: "disabled",
  },
  {
    slug: "national-id-application",
    status: "disabled",
  },
  {
    slug: "national-summer-camp",
    status: "disabled",
  },
  {
    slug: "national-summer-camp-2025-registration",
    status: "form_disabled",
  },
  {
    slug: "nhc-application-rental-unit",
    status: "disabled",
  },
  {
    slug: "nhc-land-property-application",
    status: "disabled",
  },
  {
    slug: "nhs-tenants-notice-intention-purchase-freehold",
    status: "disabled",
  },
  {
    slug: "non-nationals-secondary-entry",
    status: "disabled",
  },
  {
    slug: "pathways-employability-programme-application-2026",
    status: "disabled",
  },
  {
    slug: "post-office-redirection-business",
    status: "form_disabled",
  },
  {
    slug: "post-office-redirection-deceased",
    status: "form_disabled",
  },
  {
    slug: "post-office-redirection-individual",
    status: "form_disabled",
  },
  {
    slug: "project-dawn-application",
    status: "disabled",
  },
  {
    slug: "project-protege-mentor",
    status: "enabled",
  },
  {
    slug: "referral-student-support-services",
    status: "disabled",
  },
  {
    slug: "register-a-birth",
    status: "enabled",
  },
  {
    slug: "report-a-concern-about-a-child",
    status: "enabled",
  },
  {
    slug: "report-elderly-abuse",
    status: "enabled",
  },
  {
    slug: "request-a-bssee-school-reallocation",
    status: "disabled",
  },
  {
    slug: "request-a-fire-service-inspection",
    status: "disabled",
  },
  {
    slug: "request-a-presidential-visit-for-a-centenarian",
    status: "disabled",
  },
  {
    slug: "request-a-statement-of-examination-results",
    status: "disabled",
  },
  {
    slug: "request-assistance-transportation-disabilities",
    status: "disabled",
  },
  {
    slug: "request-special-arrangements-for-the-bssee",
    status: "disabled",
  },
  {
    slug: "reserve-society-name",
    status: "disabled",
  },
  {
    slug: "school-registration-fee",
    status: "disabled",
  },
  {
    slug: "school-uniform-grant-barbados",
    status: "disabled",
  },
  {
    slug: "sell-goods-services-beach-park",
    status: "enabled",
  },
  {
    slug: "seniors-recreational-activities-programme",
    status: "disabled",
  },
  {
    slug: "simple-three-step-form",
    status: "disabled",
  },
  {
    slug: "smart-stream-vendor-registration",
    status: "disabled",
  },
  {
    slug: "sports-training-programme-form-schema",
    status: "enabled",
  },
  {
    slug: "statement-of-travelling-form",
    status: "disabled",
  },
  {
    slug: "temp-teacher-application-barbados",
    status: "disabled",
  },
  {
    slug: "term-leave-application",
    status: "disabled",
  },
  {
    slug: "terms-conditions",
    status: "enabled",
  },
  {
    slug: "web-design-entrepreneurs",
    status: "disabled",
  },
  {
    slug: "welfare-department",
    status: "enabled",
  },
  {
    slug: "what-we-mean-by-alpha",
    status: "enabled",
  },
  {
    slug: "whats-changing",
    status: "enabled",
  },
  {
    slug: "yar",
    status: "disabled",
  },
  {
    slug: "ydp",
    status: "disabled",
  },
  {
    slug: "ydp-performing-arts-registration-2025-2026",
    status: "disabled",
  },
  {
    slug: "yes",
    status: "disabled",
  },
  {
    slug: "youth-cultural-training-registration-2025",
    status: "disabled",
  },
  {
    slug: "youth-leadership-workshop-registration-2026",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-barbados-blooming-libraries",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-bright-sparks-2",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-btu",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-byac",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-cap",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-ceep",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-centre-access",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-cip",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-cmc",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-community-canvas",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-pathways",
    status: "disabled",
  },
  {
    slug: "youth-opportunity-ydp",
    status: "disabled",
  },
];
