/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    services: Service
    organisations: Organisation
    categories: Category
    subcategories: Subcategory
    media: Media
    users: User
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>
    categories: CategoriesSelect<false> | CategoriesSelect<true>
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    users: UsersSelect<false> | UsersSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {}
  globalsSelect: {}
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * Service and guide pages shown to the public on the site. Some services have sub-pages with a slashed slug like service-name/start — edit the main page for its description and listings, and the sub-page for the form-start content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number
  /**
   * The web address for this page. Leave blank and it fills in from the title. Once the page is live this is locked — changing it breaks every existing link, so ask an admin if it really must change.
   */
  slug: string
  /**
   * Set to “Flagged” while preparing — the page is hidden from the public and only visible to reviewers with the feature-flag cookie. Switch to “Live” when ready to release.
   */
  flag: 'live' | 'flagged'
  title: string
  /**
   * A one-sentence summary, shown in search results and listings. Aim for under 160 characters — that’s roughly what search engines show in results.
   */
  description?: string | null
  /**
   * The page content. Write normally; use the block menu to insert a Callout, Show / hide, Start now button or Link button.
   */
  body?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  /**
   * Which categories this page is listed under.
   */
  categories?: (number | Category)[] | null
  /**
   * Optional. Choose categories first — only subcategories of those categories are offered.
   */
  subcategory?: (number | null) | Subcategory
  /**
   * Choose “Digital” if the service has an online form authors can link to from a Start now button; otherwise leave as “Information only”.
   */
  serviceType: 'digital' | 'information'
  /**
   * How finished this page is. New pages start at Alpha. Use “Migrated” only for content carried over from the old gov.bb site.
   */
  stage: 'alpha' | 'beta' | 'migrated'
  /**
   * The original gov.bb page this migrated content came from.
   */
  sourceUrl?: string | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * The top-level groupings services are listed under on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number
  title: string
  /**
   * URL-safe id, lowercase with hyphens (e.g. travel-id-citizenship). Used in page URLs — changing it breaks existing links.
   */
  slug: string
  /**
   * Position in the homepage category list. Lower numbers appear first. Leave at 999 for new categories — they’ll land at the end until an admin reorders them.
   */
  order: number
  /**
   * One sentence shown under the category heading on the site.
   */
  description?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * Optional second level within a category. Most categories have none.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: number
  title: string
  /**
   * URL-safe id, lowercase with hyphens (e.g. travel-id-citizenship). Used in page URLs — changing it breaks existing links.
   */
  slug: string
  /**
   * The category this subcategory belongs to.
   */
  parent: number | Category
  description?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * Ministries, departments and state bodies.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: number
  /**
   * The web address for this page. Leave blank and it fills in from the title. Once the page is live this is locked — changing it breaks every existing link, so ask an admin if it really must change.
   */
  slug: string
  /**
   * Set to “Flagged” while preparing — the page is hidden from the public and only visible to reviewers with the feature-flag cookie. Switch to “Live” when ready to release.
   */
  flag: 'live' | 'flagged'
  /**
   * What type of organisation this is.
   */
  kind: 'ministry' | 'department' | 'state-body'
  /**
   * How finished this page is. Use “Migrated” only for content carried over from the old gov.bb site.
   */
  stage: 'alpha' | 'beta' | 'migrated'
  name: string
  /**
   * How this ministry is classified.
   */
  category?: ('ministerial' | 'non-ministerial' | 'agency') | null
  /**
   * One sentence shown in organisation listings. Aim for under 160 characters — that’s roughly what search engines show in results.
   */
  shortDescription?: string | null
  /**
   * A short introduction shown at the top of the page.
   */
  intro?: string | null
  /**
   * The minister or head of this organisation.
   */
  leader?: {
    name?: string | null
    role?: string | null
  }
  /**
   * Banner image for the ministry page.
   */
  heroImage?: (number | null) | Media
  /**
   * Search aliases — abbreviations and alternate names.
   */
  keywords?:
    | {
        value: string
        id?: string | null
      }[]
    | null
  /**
   * The original gov.bb page this migrated content came from.
   */
  originalSource?: string | null
  /**
   * Add a block per contact method.
   */
  contact?:
    | (
        | {
            /**
             * Shown beside the value, e.g. "Main office" or "Permanent Secretary".
             */
            label?: string | null
            value: string
            id?: string | null
            blockName?: string | null
            blockType: 'phone'
          }
        | {
            /**
             * Shown beside the value, e.g. "Main office" or "Permanent Secretary".
             */
            label?: string | null
            value: string
            id?: string | null
            blockName?: string | null
            blockType: 'email'
          }
        | {
            /**
             * Shown beside the value, e.g. "Main office" or "Permanent Secretary".
             */
            label?: string | null
            value: string
            /**
             * Optional friendly text to show instead of the raw URL.
             */
            display?: string | null
            id?: string | null
            blockName?: string | null
            blockType: 'website'
          }
        | {
            /**
             * Shown beside the value, e.g. "Main office" or "Permanent Secretary".
             */
            label?: string | null
            /**
             * One line per row — building, street, parish, country.
             */
            lines: string
            id?: string | null
            blockName?: string | null
            blockType: 'address'
          }
      )[]
    | null
  social?:
    | {
        /**
         * Lowercase platform name: twitter, facebook, instagram, linkedin, youtube.
         */
        platform: string
        url: string
        id?: string | null
      }[]
    | null
  /**
   * Links to online services, or forms in the forms app.
   */
  onlineServices?:
    | (
        | {
            title: string
            /**
             * A site path like /apply-for-a-passport, or a full external URL.
             */
            href: string
            description?: string | null
            id?: string | null
            blockName?: string | null
            blockType: 'linkService'
          }
        | {
            /**
             * The form ID from the forms app.
             */
            formId: string
            label?: string | null
            id?: string | null
            blockName?: string | null
            blockType: 'formService'
          }
      )[]
    | null
  /**
   * Highlighted tiles shown on the ministry page.
   */
  featured?:
    | {
        title: string
        /**
         * Where the tile links to: a path on this site like /apply-for-a-passport, or a full external URL.
         */
        href: string
        description: string
        image?: (number | null) | Media
        imageAlt?: string | null
        id?: string | null
      }[]
    | null
  /**
   * Services this ministry provides. Start typing to find and link a service page — its title and summary are pulled in automatically, and the link can never break.
   */
  services?: (number | Service)[] | null
  /**
   * Departments and bodies grouped under this ministry.
   */
  associatedDepartments?:
    | {
        /**
         * Optional heading to group these departments under (e.g. “Agencies”).
         */
        category?: string | null
        items?:
          | {
              name: string
              /**
               * Optional — slug of another organisation to link to.
               */
              slug?: string | null
              id?: string | null
            }[]
          | null
        id?: string | null
      }[]
    | null
  /**
   * The page content. Write normally; use the block menu to insert a Callout, Show / hide, Start now button or Link button. For role-to-phone directories (and any other reference table), insert a table from the toolbar — you can have as many tables as the organisation needs.
   */
  body?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  /**
   * Describes the image for screen readers and when it can't load.
   */
  alt: string
  /**
   * Optional caption shown beneath the image.
   */
  caption?: string | null
  /**
   * Optional photographer or source credit.
   */
  credit?: string | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  /**
   * The person's name, shown in the users list.
   */
  name?: string | null
  /**
   * Admins manage users and taxonomy. Editors create and edit content.
   */
  role: 'admin' | 'editor'
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'services'
        value: number | Service
      } | null)
    | ({
        relationTo: 'organisations'
        value: number | Organisation
      } | null)
    | ({
        relationTo: 'categories'
        value: number | Category
      } | null)
    | ({
        relationTo: 'subcategories'
        value: number | Subcategory
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T
  flag?: T
  title?: T
  description?: T
  body?: T
  categories?: T
  subcategory?: T
  serviceType?: T
  stage?: T
  sourceUrl?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  slug?: T
  flag?: T
  kind?: T
  stage?: T
  name?: T
  category?: T
  shortDescription?: T
  intro?: T
  leader?:
    | T
    | {
        name?: T
        role?: T
      }
  heroImage?: T
  keywords?:
    | T
    | {
        value?: T
        id?: T
      }
  originalSource?: T
  contact?:
    | T
    | {
        phone?:
          | T
          | {
              label?: T
              value?: T
              id?: T
              blockName?: T
            }
        email?:
          | T
          | {
              label?: T
              value?: T
              id?: T
              blockName?: T
            }
        website?:
          | T
          | {
              label?: T
              value?: T
              display?: T
              id?: T
              blockName?: T
            }
        address?:
          | T
          | {
              label?: T
              lines?: T
              id?: T
              blockName?: T
            }
      }
  social?:
    | T
    | {
        platform?: T
        url?: T
        id?: T
      }
  onlineServices?:
    | T
    | {
        linkService?:
          | T
          | {
              title?: T
              href?: T
              description?: T
              id?: T
              blockName?: T
            }
        formService?:
          | T
          | {
              formId?: T
              label?: T
              id?: T
              blockName?: T
            }
      }
  featured?:
    | T
    | {
        title?: T
        href?: T
        description?: T
        image?: T
        imageAlt?: T
        id?: T
      }
  services?: T
  associatedDepartments?:
    | T
    | {
        category?: T
        items?:
          | T
          | {
              name?: T
              slug?: T
              id?: T
            }
        id?: T
      }
  body?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  order?: T
  description?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  parent?: T
  description?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  caption?: T
  credit?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  role?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
