import {
  deleteContentPage,
  listOpenContentPRs,
  loadLandingContentPage,
  publishStartPage,
} from "./-server";

const PATH =
  "apps/landing/src/content/funeral-establishment-licence-application/index.md";
const BRANCH = "start-page-funeral-establishment-licence-application-index-123";
const PR_URL = "https://github.com/govtech-bb/gov-bb/pull/2450";
const EQUIVALENT_PATH =
  "apps/landing/src/content/funeral-establishment-licence-application.md";
const RAW_PAGE = `---
title: Apply for a funeral establishment licence
category: work-employment
visibility: draft
form_id: funeral-establishment-licence-application
---
## Apply online

<a data-start-link>Start now</a>
`;

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function callServer<T>(serverFn: unknown, options: unknown): Promise<T> {
  return (serverFn as (input: unknown) => Promise<T>)(options);
}

function pull(
  number = 2450,
  headSha = "head-1",
  body = "Generated by the form_builder Content flow.",
  repoFullName = "govtech-bb/gov-bb",
) {
  return {
    number,
    html_url: `https://github.com/govtech-bb/gov-bb/pull/${number}`,
    head: {
      ref: number === 2450 ? BRANCH : `${BRANCH.slice(0, -3)}456`,
      sha: headSha,
      repo: { full_name: repoFullName },
    },
    body,
  };
}

function installGitHubMock(
  opts: {
    pulls?: ReturnType<typeof pull>[];
    headSha?: string;
    failPullList?: boolean;
    changeType?: "added" | "modified" | "removed" | "renamed";
    failComment?: boolean;
    refConflict?: boolean;
    equivalentBaseExists?: boolean;
    rawPage?: string;
  } = {},
) {
  const pulls = opts.pulls ?? [pull(2450, opts.headSha ?? "head-1")];
  const fetchMock = vi.fn(
    async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = String(input);
      const method = init?.method ?? "GET";
      if (url.includes("/pulls?state=open")) {
        return opts.failPullList ? json({ message: "down" }, 503) : json(pulls);
      }
      if (/\/pulls\/\d+\/files/.test(url)) {
        return json([{ filename: PATH, status: opts.changeType ?? "added" }]);
      }
      if (url.includes(`/contents/${PATH}?ref=`)) {
        return json({
          sha: "page-sha",
          content: Buffer.from(opts.rawPage ?? RAW_PAGE).toString("base64"),
        });
      }
      if (url.includes(`/contents/${EQUIVALENT_PATH}?ref=main`)) {
        return opts.equivalentBaseExists
          ? json({ sha: "equivalent-page-sha", content: "" })
          : json({ message: "not found" }, 404);
      }
      if (url.endsWith("/git/commits/head-1") && method === "GET") {
        return json({ tree: { sha: "tree-1" } });
      }
      if (url.endsWith("/git/blobs") && method === "POST") {
        return json({ sha: "blob-1" }, 201);
      }
      if (url.endsWith("/git/trees") && method === "POST") {
        return json({ sha: "tree-2" }, 201);
      }
      if (url.endsWith("/git/commits") && method === "POST") {
        return json({ sha: "commit-2" }, 201);
      }
      if (url.includes(`/git/refs/heads/${BRANCH}`) && method === "PATCH") {
        return opts.refConflict
          ? json({ message: "not fast forward" }, 422)
          : json({ object: { sha: "commit-2" } });
      }
      if (url.endsWith("/issues/2450/comments") && method === "POST") {
        return opts.failComment
          ? json({ message: "down" }, 503)
          : json({ id: 1 }, 201);
      }
      throw new Error(`Unexpected GitHub request: ${method} ${url}`);
    },
  );
  vi.stubGlobal("fetch", fetchMock);
  return fetchMock;
}

const publishData = {
  formId: "funeral-establishment-licence-application",
  title: "Apply for a funeral establishment licence",
  category: "work-employment",
  body: "## Apply online\n\n<a data-start-link>Start now</a>",
  buttonLabel: "Start now",
  visibility: "draft" as const,
  prDescription: "Clarify the eligibility text.",
  path: PATH,
  sha: "page-sha",
  baseFrontmatter: {},
  expectedRevision: {
    source: "pr" as const,
    sha: "page-sha",
    prNumber: 2450,
    branch: BRANCH,
    headSha: "head-1",
  },
};

beforeEach(() => {
  process.env.GITHUB_ORG = "govtech-bb";
  process.env.PUBLISH_BASE_BRANCH = "main";
});

afterEach(() => {
  vi.unstubAllGlobals();
});

describe("content PR review inventory", () => {
  it("returns a real summary for a page that exists only on an open PR", async () => {
    installGitHubMock();

    const snapshot = await callServer<
      Awaited<ReturnType<typeof listOpenContentPRs>>
    >(listOpenContentPRs, { context: { token: "tok" } });

    expect(snapshot.complete).toBe(true);
    expect(snapshot.claims).toEqual([
      expect.objectContaining({
        path: PATH,
        prNumber: 2450,
        changeType: "added",
        writable: true,
        summary: expect.objectContaining({
          title: "Apply for a funeral establishment licence",
          formId: "funeral-establishment-licence-application",
        }),
      }),
    ]);
  });

  it("loads the PR-only page from the exact reviewed revision", async () => {
    installGitHubMock();

    const page = await callServer<
      Awaited<ReturnType<typeof loadLandingContentPage>>
    >(loadLandingContentPage, {
      data: { path: PATH },
      context: { token: "tok" },
    });

    expect(page.revision).toEqual({
      source: "pr",
      sha: "page-sha",
      prNumber: 2450,
      branch: BRANCH,
      headSha: "head-1",
    });
    expect(page.frontmatter.title).toBe(
      "Apply for a funeral establishment licence",
    );
  });

  it("surfaces a removal as read-only review state", async () => {
    installGitHubMock({ changeType: "removed" });

    const snapshot = await callServer<
      Awaited<ReturnType<typeof listOpenContentPRs>>
    >(listOpenContentPRs, { context: { token: "tok" } });

    expect(snapshot.claims[0]).toEqual(
      expect.objectContaining({
        changeType: "removed",
        writable: false,
        summary: undefined,
      }),
    );
  });

  it("keeps a similarly named manual PR read-only", async () => {
    installGitHubMock({ pulls: [pull(2450, "head-1", "Opened by hand")] });

    const snapshot = await callServer<
      Awaited<ReturnType<typeof listOpenContentPRs>>
    >(listOpenContentPRs, { context: { token: "tok" } });

    expect(snapshot.claims[0]).toEqual(
      expect.objectContaining({ writable: false, prNumber: 2450 }),
    );
  });

  it("keeps a fork PR visible without treating unreadable head content as an outage", async () => {
    const fetchMock = installGitHubMock({
      pulls: [
        pull(
          2450,
          "fork-head",
          "Generated by the form_builder Content flow.",
          "contributor/gov-bb",
        ),
      ],
    });

    const snapshot = await callServer<
      Awaited<ReturnType<typeof listOpenContentPRs>>
    >(listOpenContentPRs, { context: { token: "tok" } });

    expect(snapshot.complete).toBe(true);
    expect(snapshot.claims[0]).toEqual(
      expect.objectContaining({ writable: false, summary: undefined }),
    );
    expect(
      fetchMock.mock.calls.some(([url]) => String(url).includes("/contents/")),
    ).toBe(false);
  });
});

describe("same-PR content deploy", () => {
  it("updates the existing branch atomically and comments without opening a PR", async () => {
    const fetchMock = installGitHubMock();

    const result = await callServer<
      Awaited<ReturnType<typeof publishStartPage>>
    >(publishStartPage, {
      data: publishData,
      context: { session: { accessToken: "tok", login: "isaiah" } },
    });

    expect(result).toEqual({
      status: "success",
      prUrl: PR_URL,
      prNumber: 2450,
      path: PATH,
      updatedExistingPR: true,
      warning: undefined,
    });
    const calls = fetchMock.mock.calls.map(([url, init]) => ({
      url: String(url),
      method: init?.method ?? "GET",
      body: init?.body,
    }));
    expect(calls).toContainEqual(
      expect.objectContaining({
        url: expect.stringContaining(`/git/refs/heads/${BRANCH}`),
        method: "PATCH",
      }),
    );
    expect(calls).not.toContainEqual(
      expect.objectContaining({ url: expect.stringMatching(/\/git\/refs$/) }),
    );
    expect(calls).not.toContainEqual(
      expect.objectContaining({
        url: expect.stringMatching(/\/pulls$/),
        method: "POST",
      }),
    );
    expect(calls).toContainEqual(
      expect.objectContaining({
        url: expect.stringContaining("/issues/2450/comments"),
        body: expect.stringContaining("Clarify the eligibility text."),
      }),
    );
  });

  it("blocks a stale editor before creating any Git objects", async () => {
    const fetchMock = installGitHubMock({ headSha: "head-2" });

    const result = await callServer<
      Awaited<ReturnType<typeof publishStartPage>>
    >(publishStartPage, {
      data: publishData,
      context: { session: { accessToken: "tok", login: "isaiah" } },
    });

    expect(result).toEqual(
      expect.objectContaining({
        status: "conflict",
        conflict: expect.objectContaining({ kind: "stale-revision" }),
      }),
    );
    expect(
      fetchMock.mock.calls.some(([url, init]) => {
        const method = init?.method ?? "GET";
        return method !== "GET" && String(url).includes("/git/");
      }),
    ).toBe(false);
  });

  it("blocks when two PRs claim the same path", async () => {
    const fetchMock = installGitHubMock({ pulls: [pull(2450), pull(2451)] });

    const result = await callServer<
      Awaited<ReturnType<typeof publishStartPage>>
    >(publishStartPage, {
      data: publishData,
      context: { session: { accessToken: "tok", login: "isaiah" } },
    });

    expect(result).toEqual(
      expect.objectContaining({
        status: "conflict",
        conflict: expect.objectContaining({ kind: "multiple-reviews" }),
      }),
    );
    expect(
      fetchMock.mock.calls.some(
        ([url, init]) =>
          (init?.method ?? "GET") === "PATCH" &&
          String(url).includes("/git/refs/heads/"),
      ),
    ).toBe(false);
  });

  it("reports a successful update when only the PR comment fails", async () => {
    installGitHubMock({ failComment: true });

    const result = await callServer<
      Awaited<ReturnType<typeof publishStartPage>>
    >(publishStartPage, {
      data: publishData,
      context: { session: { accessToken: "tok", login: "isaiah" } },
    });

    expect(result).toEqual(
      expect.objectContaining({
        status: "success",
        updatedExistingPR: true,
        warning: expect.stringContaining("description could not be added"),
      }),
    );
  });

  it("preserves an unmerged category already present on the exact PR revision", async () => {
    const category = "brand-new-section";
    installGitHubMock({
      rawPage: RAW_PAGE.replace("work-employment", category),
    });

    const result = await callServer<
      Awaited<ReturnType<typeof publishStartPage>>
    >(publishStartPage, {
      data: { ...publishData, category },
      context: { session: { accessToken: "tok", login: "isaiah" } },
    });

    expect(result).toEqual(
      expect.objectContaining({ status: "success", updatedExistingPR: true }),
    );
  });

  it("leaves the PR unchanged when its ref moves during the atomic update", async () => {
    installGitHubMock({ refConflict: true });

    const result = await callServer<
      Awaited<ReturnType<typeof publishStartPage>>
    >(publishStartPage, {
      data: publishData,
      context: { session: { accessToken: "tok", login: "isaiah" } },
    });

    expect(result).toEqual(
      expect.objectContaining({
        status: "conflict",
        conflict: expect.objectContaining({ kind: "stale-revision" }),
      }),
    );
  });

  it("blocks an existing PR update when another base file owns the same URL", async () => {
    const fetchMock = installGitHubMock({ equivalentBaseExists: true });

    const result = await callServer<
      Awaited<ReturnType<typeof publishStartPage>>
    >(publishStartPage, {
      data: publishData,
      context: { session: { accessToken: "tok", login: "isaiah" } },
    });

    expect(result).toEqual(
      expect.objectContaining({
        status: "conflict",
        conflict: expect.objectContaining({ kind: "path-exists" }),
      }),
    );
    expect(
      fetchMock.mock.calls.some(
        ([url, init]) =>
          (init?.method ?? "GET") === "PATCH" &&
          String(url).includes("/git/refs/heads/"),
      ),
    ).toBe(false);
  });

  it("fails closed when open PRs cannot be checked", async () => {
    const fetchMock = installGitHubMock({ failPullList: true });

    const result = await callServer<
      Awaited<ReturnType<typeof publishStartPage>>
    >(publishStartPage, {
      data: { ...publishData, expectedRevision: { source: "absent" as const } },
      context: { session: { accessToken: "tok", login: "isaiah" } },
    });

    expect(result).toEqual(
      expect.objectContaining({
        status: "conflict",
        conflict: expect.objectContaining({ kind: "review-unavailable" }),
      }),
    );
    expect(
      fetchMock.mock.calls.some(([url, init]) => {
        const method = init?.method ?? "GET";
        return method !== "GET" && String(url).includes("/git/");
      }),
    ).toBe(false);
  });
});

describe("content removal", () => {
  it("abandons the removal branch if the page changes during preflight", async () => {
    const fetchMock = vi.fn(
      async (input: RequestInfo | URL, init?: RequestInit) => {
        const url = String(input);
        const method = init?.method ?? "GET";
        if (url.includes("/pulls?state=open")) return json([]);
        if (url.includes(`/contents/${PATH}?ref=main`)) {
          return json({ sha: "page-sha" });
        }
        if (url.endsWith("/git/ref/heads/main")) {
          return json({ object: { sha: "base-head" } });
        }
        if (url.endsWith("/git/refs") && method === "POST") {
          return json({ ref: "created" }, 201);
        }
        if (url.includes(`/contents/${PATH}?ref=start-page-`)) {
          return json({ sha: "changed-page-sha" });
        }
        if (
          url.includes("/git/refs/heads/start-page-") &&
          method === "DELETE"
        ) {
          return new Response(null, { status: 204 });
        }
        throw new Error(`Unexpected GitHub request: ${method} ${url}`);
      },
    );
    vi.stubGlobal("fetch", fetchMock);

    await expect(
      callServer(deleteContentPage, {
        data: {
          path: PATH,
          title: "Funeral establishment licence",
          expectedRevision: { source: "base", sha: "page-sha" },
        },
        context: { session: { accessToken: "tok", login: "isaiah" } },
      }),
    ).rejects.toThrow(/changed on main/);

    expect(
      fetchMock.mock.calls.some(
        ([url, init]) =>
          (init?.method ?? "GET") === "DELETE" &&
          String(url).includes("/contents/"),
      ),
    ).toBe(false);
    expect(
      fetchMock.mock.calls.some(
        ([url, init]) =>
          (init?.method ?? "GET") === "DELETE" &&
          String(url).includes("/git/refs/heads/start-page-"),
      ),
    ).toBe(true);
  });
});
