import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { SMART_TOOLS, smartTool } from "@govtech-bb/content/smart-tools";
import {
  contentSchema,
  displayContent,
  prepareContentChange,
  withContentFields,
  type ContentObject,
} from "@govtech-bb/content/smart-tool-fields";
import { requireSession } from "../../server/auth/require-session";
import { sessionTokenOrDev } from "../../server/auth/session-or-dev";
import { resolveBaseBranch } from "../../server/publish";
import {
  createBranchFrom,
  deleteBranch,
  getContents,
  openPullRequest,
  listOpenPRHeads,
  ghError,
  repoUrl,
  authHeaders,
} from "../../server/github";
import { REPO_NAME, repoOwner } from "../../server/github-repo";
import {
  listPRFiles,
  commitFilesToExistingPR,
} from "../../server/content-github";
import { contentRevisionSchema, type ContentRevision } from "./-server";

const ROOT = "apps/landing/src/";
export const SMART_TOOL_FILES: Readonly<Record<string, string>> = {
  pharmacies: `${ROOT}routes/health-and-emergency-services/find-an-open-pharmacy/-data/pharmacies.json`,
  shelters: `${ROOT}routes/health-and-emergency-services/find-an-emergency-shelter/-data/emergency-shelters.json`,
};
const MARKER = "Generated by the form_builder Smart tools flow.";

export interface ToolReview {
  id: string;
  prNumber: number;
  prUrl: string;
  branch: string;
  headSha: string;
  writable: boolean;
  readable: boolean;
}

export interface LoadedSmartTool {
  id: string;
  content: ContentObject;
  revision: Exclude<ContentRevision, { source: "absent" }>;
  review?: ToolReview;
  canPublish: boolean;
  warning?: string;
}

/** Inspect all open PRs: a manually authored change also claims the file. */
async function reviews(token: string): Promise<ToolReview[]> {
  const prs = await listOpenPRHeads(token, resolveBaseBranch());
  const sameRepo = `${repoOwner()}/${REPO_NAME}`.toLowerCase();
  const results = await Promise.all(
    prs.map(async (pr) => {
      if (!pr.headSha)
        throw new Error(
          "An open change has no readable revision. Refresh before publishing.",
        );
      const files = await listPRFiles(token, pr.number);
      return SMART_TOOLS.flatMap((tool): ToolReview[] => {
        const file = files.find(
          (f) =>
            f.filename === SMART_TOOL_FILES[tool.id] ||
            f.previous_filename === SMART_TOOL_FILES[tool.id],
        );
        if (!file) return [];
        const ownRepo = pr.headRepoFullName?.toLowerCase() === sameRepo;
        return [
          {
            id: tool.id,
            prNumber: pr.number,
            prUrl: pr.htmlUrl,
            branch: pr.headRef,
            headSha: pr.headSha!,
            readable:
              ownRepo &&
              file.status !== "removed" &&
              file.filename === SMART_TOOL_FILES[tool.id],
            writable:
              ownRepo &&
              file.status === "modified" &&
              new RegExp(`^smart-tool-${tool.id}-[a-z0-9-]+$`).test(
                pr.headRef,
              ) &&
              pr.body?.includes(MARKER) === true,
          },
        ];
      });
    }),
  );
  return results.flat();
}

async function readTool(
  id: string,
  token: string | null,
  openReviews?: ToolReview[],
): Promise<LoadedSmartTool> {
  const definition = smartTool(id);
  const path = SMART_TOOL_FILES[id];
  let raw: string;
  let sha: string;
  const claims = token
    ? (openReviews ?? (await reviews(token))).filter((pr) => pr.id === id)
    : [];
  const review = claims.length === 1 ? claims[0] : undefined;
  if (token) {
    const response = await getContents(
      token,
      path,
      review?.readable ? review.headSha : resolveBaseBranch(),
    );
    if (!response.ok)
      throw await ghError("This smart tool could not be loaded", response);
    const file = (await response.json()) as { sha: string; content: string };
    raw = Buffer.from(file.content, "base64").toString("utf8");
    sha = file.sha;
  } else {
    const [{ readFile }, { resolve }, { createHash }] = await Promise.all([
      import("node:fs/promises"),
      import("node:path"),
      import("node:crypto"),
    ]);
    raw = await readFile(
      resolve(process.cwd(), "../landing/src", path.slice(ROOT.length)),
      "utf8",
    );
    sha = createHash("sha256").update(raw).digest("hex");
  }
  const revision: LoadedSmartTool["revision"] = review?.readable
    ? {
        source: "pr",
        sha,
        prNumber: review.prNumber,
        branch: review.branch,
        headSha: review.headSha,
      }
    : { source: "base", sha };
  const parsed = JSON.parse(raw) as ContentObject;
  const content = contentSchema(withContentFields(definition, parsed)).parse(
    parsed,
  ) as ContentObject;
  const warning =
    claims.length > 1
      ? "More than one open change affects this tool. Resolve those changes before publishing."
      : review && !review.writable
        ? "This tool has an existing change that must be resolved in GitHub before publishing here."
        : undefined;
  return {
    id,
    content,
    revision,
    review,
    canPublish: token !== null && !warning,
    warning,
  };
}

export const listSmartTools = createServerFn({ method: "GET", strict: false })
  .middleware([sessionTokenOrDev])
  .handler(async ({ context }) => {
    let openReviews: ToolReview[];
    try {
      openReviews = context.token ? await reviews(context.token) : [];
    } catch {
      return SMART_TOOLS.map((tool) => ({
        id: tool.id,
        available: false,
        warning: "Smart tools could not be loaded. Refresh to try again.",
      }));
    }
    return Promise.all(
      SMART_TOOLS.map(async (tool) => {
        try {
          const loaded = await readTool(tool.id, context.token, openReviews);
          return {
            id: tool.id,
            available: true,
            review: loaded.review,
            warning: loaded.warning,
          };
        } catch (error) {
          return {
            id: tool.id,
            available: false,
            warning:
              error instanceof Error
                ? error.message
                : "This smart tool is unavailable.",
          };
        }
      }),
    );
  });

export const loadSmartTool = createServerFn({ method: "GET", strict: false })
  .middleware([sessionTokenOrDev])
  .inputValidator(z.object({ id: z.string() }))
  .handler(({ data, context }) => readTool(data.id, context.token));

export const publishSmartTool = createServerFn({
  method: "POST",
  strict: false,
})
  .middleware([requireSession])
  .inputValidator(
    z.object({
      id: z.string(),
      draft: z.record(z.string(), z.unknown()),
      removals: z.array(z.string()),
      expectedRevision: contentRevisionSchema,
      description: z.string().max(4000).default(""),
    }),
  )
  .handler(async ({ data, context }) => {
    const token = context.session.accessToken;
    const current = await readTool(data.id, token);
    const conflict = (message: string) => ({
      status: "conflict" as const,
      message,
    });
    if (!current.canPublish)
      return conflict(current.warning ?? "Publishing is unavailable.");
    const expected = data.expectedRevision;
    const revision = current.revision;
    if (
      expected.source === "absent" ||
      expected.source !== revision.source ||
      expected.sha !== revision.sha ||
      (expected.source === "pr" &&
        revision.source === "pr" &&
        (expected.prNumber !== revision.prNumber ||
          expected.headSha !== revision.headSha ||
          expected.branch !== revision.branch))
    )
      return conflict(
        "This tool changed after you loaded it. Your draft is safe; reload the source before publishing.",
      );
    const definition = withContentFields(smartTool(data.id), current.content);
    const prepared = prepareContentChange(
      definition,
      current.content,
      data.draft,
      data.removals,
    );
    if (!prepared.changes.length)
      throw new Error("There are no changes to publish.");
    const content = `${JSON.stringify(prepared.content, null, 2)}\n`;
    const message = `Update ${definition.title}`;
    if (revision.source === "pr") {
      const committed = await commitFilesToExistingPR(
        token,
        revision.branch,
        revision.headSha,
        message,
        [{ path: SMART_TOOL_FILES[data.id], content }],
      );
      if (!committed)
        return conflict(
          "The pending change was updated while you were publishing. Your draft is safe; reload the source.",
        );
      return {
        status: "success" as const,
        prNumber: revision.prNumber,
        prUrl: current.review!.prUrl,
        updatedExistingPR: true,
      };
    }
    // GitHub permits one reservation for this published revision, including concurrent requests.
    const branchBase = `smart-tool-${data.id}-${revision.sha}`;
    let branch = branchBase;
    let headSha: string | undefined;
    for (let attempt = 0; attempt < 8; attempt++) {
      try {
        headSha = await createBranchFrom(token, resolveBaseBranch(), branch);
        break;
      } catch (error) {
        if (!(error instanceof Error) || !error.message.includes("status 422"))
          throw error;
        const response = await fetch(
          repoUrl(
            `/pulls?state=all&head=${encodeURIComponent(`${repoOwner()}:${branch}`)}&per_page=100`,
          ),
          { headers: authHeaders(token) },
        );
        if (!response.ok)
          throw await ghError(
            "The previous publication could not be checked",
            response,
          );
        const attempts = (await response.json()) as {
          number: number;
          state: string;
          body: string | null;
        }[];
        if (attempts.some((review) => review.state === "open"))
          return conflict(
            "Another publication started. Reload to load its pending change; your draft is safe.",
          );
        const lastClosed = Math.max(
          0,
          ...attempts
            .filter(
              (review) =>
                review.state === "closed" && review.body?.includes(MARKER),
            )
            .map((review) => review.number),
        );
        if (!lastClosed)
          return conflict(
            "A publication is being prepared or needs recovery. Your draft is safe. Refresh shortly; if this continues, ask a publisher to check the saved publication branch.",
          );
        // Closed PR branches remain untouched; every retry shares the next reservation.
        branch = `${branchBase}-${lastClosed}`;
      }
    }
    if (!headSha)
      return conflict(
        "Previous publications need review before another update can be prepared. Your draft is safe.",
      );
    let openingReview = false;
    try {
      const branched = await getContents(
        token,
        SMART_TOOL_FILES[data.id],
        headSha,
      );
      if (
        !branched.ok ||
        ((await branched.json()) as { sha: string }).sha !== revision.sha
      ) {
        await deleteBranch(branch, token);
        return conflict(
          "The published source changed while preparing this update. Your draft is safe; reload it.",
        );
      }
      if ((await reviews(token)).some((review) => review.id === data.id)) {
        await deleteBranch(branch, token);
        return conflict(
          "Another publication started for this tool. Reload to continue in its pending change.",
        );
      }
      const committed = await commitFilesToExistingPR(
        token,
        branch,
        headSha,
        message,
        [{ path: SMART_TOOL_FILES[data.id], content }],
      );
      if (!committed)
        throw new Error(
          "The publication branch changed. Your draft is safe; try again.",
        );
      const summary = prepared.changes
        .slice(0, 100)
        .map(
          (change) =>
            `- ${change.label}: ${displayContent(change.before, change.format).slice(0, 160)} → ${displayContent(change.after, change.format).slice(0, 160)}`,
        )
        .join("\n");
      openingReview = true;
      const result = await openPullRequest(token, {
        title: message,
        head: branch,
        base: resolveBaseBranch(),
        body: `${MARKER}\n\n${data.description}\n\n${summary}`,
      });
      return {
        status: "success" as const,
        ...result,
        updatedExistingPR: false,
      };
    } catch (error) {
      if (!openingReview) await deleteBranch(branch, token);
      else {
        // A lost response may still have opened the PR. Never delete its branch.
        try {
          const opened = (await reviews(token)).find(
            (review) => review.id === data.id && review.branch === branch,
          );
          if (opened)
            return {
              status: "success" as const,
              prNumber: opened.prNumber,
              prUrl: opened.prUrl,
              updatedExistingPR: false,
            };
          await deleteBranch(branch, token);
        } catch {
          /* Preserve the reservation until GitHub can confirm its state. */
        }
      }
      throw error;
    }
  });
