import { SMART_TOOLS } from "@govtech-bb/content/smart-tools";
import {
  loadSmartTool,
  publishSmartTool,
  SMART_TOOL_FILES,
} from "./-tools-server";

const path = SMART_TOOL_FILES.pharmacies;
const branch = "smart-tool-pharmacies-source-sha";
const data = {
  schemaVersion: 1,
  lastUpdated: "2026-09-09",
  retained: "future field",
  copy: { title: "Find an open pharmacy" },
  pharmacies: [
    {
      slug: "cs",
      name: "C S Pharmacy",
      type: "private",
      pppStatus: "participating",
      parish: "St. Michael",
      phone: "1111111",
      retained: { source: "original" },
    },
    {
      slug: "second",
      name: "Second pharmacy",
      type: "private",
      pppStatus: "unconfirmed",
      parish: "St. James",
    },
  ],
};
const draft = {
  schemaVersion: 1,
  pharmacies: [{ slug: "cs", phone: "2222222" }],
};
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status });
const call = <T>(fn: unknown, options: unknown) =>
  (fn as (options: unknown) => Promise<T>)(options);
const review = (overrides = {}) => ({
  number: 42,
  html_url: "https://github.com/govtech-bb/gov-bb/pull/42",
  head: { ref: branch, sha: "head", repo: { full_name: "govtech-bb/gov-bb" } },
  body: "Generated by the form_builder Smart tools flow.",
  ...overrides,
});

function github(
  options: {
    reviews?: ReturnType<typeof review>[];
    sha?: string;
    refConflict?: boolean;
    reserved?: boolean;
    closedPrior?: boolean;
    failure?: "list" | "commit" | "pr";
  } = {},
) {
  const mock = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = String(input);
    const method = init?.method ?? "GET";
    if (url.includes("/pulls?state=all"))
      return json(
        options.closedPrior
          ? [
              {
                number: 42,
                state: "closed",
                body: "Generated by the form_builder Smart tools flow.",
              },
            ]
          : [],
      );
    if (url.includes("/pulls?state=open"))
      return options.failure === "list"
        ? json({}, 503)
        : json(options.reviews ?? []);
    if (/\/pulls\/\d+\/files/.test(url))
      return json([{ filename: path, status: "modified" }]);
    if (url.includes(`/contents/${path}?ref=`))
      return json({
        sha: options.sha ?? "source-sha",
        content: Buffer.from(JSON.stringify(data)).toString("base64"),
      });
    if (url.endsWith("/git/ref/heads/main"))
      return json({ object: { sha: "head" } });
    if (url.endsWith("/git/refs") && method === "POST")
      return json(
        {},
        options.reserved ||
          (options.closedPrior &&
            JSON.parse(String(init?.body)).ref === `refs/heads/${branch}`)
          ? 422
          : 201,
      );
    if (url.endsWith("/git/commits/head"))
      return json({ tree: { sha: "tree" } });
    if (url.endsWith("/git/blobs")) return json({ sha: "blob" }, 201);
    if (url.endsWith("/git/trees")) return json({ sha: "next-tree" }, 201);
    if (url.endsWith("/git/commits"))
      return options.failure === "commit"
        ? json({}, 503)
        : json({ sha: "next-head" }, 201);
    if (url.includes(`/git/refs/heads/${branch}`))
      return method === "DELETE"
        ? new Response(null, { status: 204 })
        : json({}, options.refConflict ? 422 : 200);
    if (url.endsWith("/pulls") && method === "POST")
      return options.failure === "pr"
        ? json({}, 503)
        : json(
            {
              number: 42,
              html_url: "https://github.com/govtech-bb/gov-bb/pull/42",
            },
            201,
          );
    throw new Error(`Unexpected request: ${method} ${url}`);
  });
  vi.stubGlobal("fetch", mock);
  return mock;
}
const publish = (
  revision: unknown = { source: "base", sha: "source-sha" },
  extra = {},
) =>
  call<{ status: string }>(publishSmartTool, {
    context: { session: { accessToken: "token" } },
    data: {
      id: "pharmacies",
      draft,
      removals: [],
      description: "Correct the phone number",
      expectedRevision: revision,
      ...extra,
    },
  });
const writes = (mock: ReturnType<typeof github>) =>
  mock.mock.calls.filter(([, init]) => (init?.method ?? "GET") !== "GET");

beforeEach(() => {
  process.env.GITHUB_ORG = "govtech-bb";
  process.env.PUBLISH_BASE_BRANCH = "main";
});
afterEach(() => vi.unstubAllGlobals());

it("publishes one record without losing omitted records or unknown fields", async () => {
  const mock = github();
  expect(await publish()).toMatchObject({ status: "success", prNumber: 42 });
  const blob = mock.mock.calls.find(([url]) =>
    String(url).endsWith("/git/blobs"),
  )!;
  const committed = JSON.parse(JSON.parse(String(blob[1]?.body)).content);
  expect(committed).toEqual({
    ...data,
    pharmacies: [
      { ...data.pharmacies[0], phone: "2222222" },
      data.pharmacies[1],
    ],
  });
  const tree = mock.mock.calls.find(([url]) =>
    String(url).endsWith("/git/trees"),
  )!;
  expect(JSON.parse(String(tree[1]?.body)).tree).toEqual([
    { path, mode: "100644", type: "blob", sha: "blob" },
  ]);
});

it("loads and updates the exact pending revision without creating another PR", async () => {
  const mock = github({ reviews: [review()] });
  const loaded = await call<{ revision: unknown; content: unknown }>(
    loadSmartTool,
    { data: { id: "pharmacies" }, context: { token: "token" } },
  );
  expect(loaded.content).toEqual(data);
  expect(await publish(loaded.revision)).toMatchObject({
    status: "success",
    updatedExistingPR: true,
  });
  expect(writes(mock).map(([url]) => String(url))).not.toContainEqual(
    expect.stringMatching(/\/pulls$/),
  );
  expect(
    mock.mock.calls.some(([url]) => String(url).includes("?ref=head")),
  ).toBe(true);
});

it.each([
  ["changed content", { sha: "new-sha" }],
  ["manual review", { reviews: [review({ body: "Manual change" })] }],
  ["multiple reviews", { reviews: [review(), review({ number: 43 })] }],
])("blocks %s before writing", async (_name, options) => {
  const mock = github(options);
  expect(await publish()).toMatchObject({ status: "conflict" });
  expect(writes(mock)).toHaveLength(0);
});

it("does not overwrite a PR that moves during commit preparation", async () => {
  const mock = github({ reviews: [review()], refConflict: true });
  expect(
    await publish({
      source: "pr",
      sha: "source-sha",
      prNumber: 42,
      branch,
      headSha: "head",
    }),
  ).toMatchObject({ status: "conflict" });
  const update = writes(mock).find(([, init]) => init?.method === "PATCH")!;
  expect(JSON.parse(String(update[1]?.body)).force).toBe(false);
});

it.each(["commit", "pr"] as const)(
  "keeps the source untouched and releases the reservation after a %s failure",
  async (failure) => {
    const mock = github({ failure });
    await expect(publish()).rejects.toThrow();
    expect(writes(mock).some(([, init]) => init?.method === "DELETE")).toBe(
      true,
    );
    expect(
      writes(mock).some(([url]) => String(url).includes("/contents/")),
    ).toBe(false);
  },
);

it("allows only one new publication for a source revision", async () => {
  const mock = github({ reserved: true });
  expect(await publish()).toMatchObject({ status: "conflict" });
  expect(writes(mock)).toHaveLength(1);
});

it("fails closed for an unreadable review list, invalid content and unregistered targets", async () => {
  let mock = github({ failure: "list" });
  await expect(publish()).rejects.toThrow();
  expect(writes(mock)).toHaveLength(0);
  mock = github();
  await expect(
    publish(undefined, {
      draft: {
        ...draft,
        pharmacies: [{ ...draft.pharmacies[0], parish: "Missing" }],
      },
    }),
  ).rejects.toThrow();
  await expect(
    publish(undefined, { id: "../../arbitrary.json" }),
  ).rejects.toThrow("not registered");
  await expect(
    call(publishSmartTool, { data: {}, context: {} }),
  ).rejects.toThrow();
  expect(writes(mock)).toHaveLength(0);
});

it.each(SMART_TOOLS.map((tool) => tool.id))(
  "loads the canonical %s migration through the registered schema",
  async (id) => {
    const loaded = await call<{
      id: string;
      canPublish: boolean;
      content: { schemaVersion: number };
    }>(loadSmartTool, { data: { id }, context: { token: null } });
    expect(loaded).toMatchObject({
      id,
      canPublish: false,
      content: { schemaVersion: 1 },
    });
  },
);

it("starts a fresh reservation after a closed PR without touching its retained branch", async () => {
  const mock = github({ closedPrior: true });
  expect(await publish()).toMatchObject({ status: "success" });
  const reservations = writes(mock).filter(([url]) =>
    String(url).endsWith("/git/refs"),
  );
  expect(
    reservations.map(([, init]) => JSON.parse(String(init?.body)).ref),
  ).toEqual([`refs/heads/${branch}`, `refs/heads/${branch}-42`]);
  expect(writes(mock).some(([, init]) => init?.method === "DELETE")).toBe(
    false,
  );
  expect(
    writes(mock).find(([, init]) => init?.method === "PATCH")?.[0],
  ).toContain(`${branch}-42`);
});
