import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { format, resolveConfig } from "prettier";
import { buildFormCategories, loadContent } from "@govtech-bb/content";

async function main() {
  const { services, warnings } = await loadContent();
  for (const w of warnings) console.warn(w);
  const map = buildFormCategories(services);
  const sorted = Object.fromEntries(
    Object.entries(map).sort(([a], [b]) => a.localeCompare(b)),
  );
  const body =
    "// GENERATED by scripts/generate-form-categories.ts — do not edit by hand.\n" +
    "// Regenerate with `pnpm generate:form-categories` when landing content changes.\n" +
    `export const FORM_CATEGORIES: Record<string, string> = ${JSON.stringify(sorted, null, 2)};\n`;
  const out = join(
    "packages",
    "content",
    "src",
    "form-categories.generated.ts",
  );
  // Format with Prettier so the written file matches what the lint-staged
  // pre-commit hook (`prettier --write`) would produce. Without this, the raw
  // JSON.stringify output (quoted keys, no line wrapping) always differs from
  // the committed file, so the CI drift guard could never gate this file on
  // anything but formatting noise. Same reasoning as
  // scripts/generate-services-index.ts.
  const config = await resolveConfig(out);
  const formatted = await format(body, { ...config, filepath: out });
  await writeFile(out, formatted, "utf8");
  console.log(
    `Wrote ${Object.keys(sorted).length} form→category entries to ${out}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
