// Generates apps/api/src/content/services-index.generated.ts from the landing
// content index. Offline-safe (filesystem read only, no network) — run it when
// landing content changes: `pnpm generate:services-index`.
//
// The output is owned by apps/api (compiled into its own bundle) so the api
// needs no runtime dependency on @govtech-bb/content — see
// docs/superpowers/specs/2026-07-07-services-index-endpoint-design.md.
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { format, resolveConfig } from "prettier";
import {
  buildServicesIndex,
  loadContent,
  loadFeatureRouteServices,
} from "@govtech-bb/content";

async function main() {
  const { services, warnings } = await loadContent();
  // Code-route (`-meta.ts`) pages aren't markdown, so loadContent can't see
  // them; fold them in here so they reach `GET /services` and the
  // feature-flagging tool. See the durable-fix design doc.
  const { services: featureServices, warnings: featureWarnings } =
    await loadFeatureRouteServices();
  for (const w of [...warnings, ...featureWarnings]) console.warn(w);
  const index = buildServicesIndex([...services, ...featureServices]);
  const body =
    "// GENERATED by scripts/generate-services-index.ts — do not edit by hand.\n" +
    "// Regenerate with `pnpm generate:services-index` when landing content changes.\n" +
    'import type { ServiceIndexEntry } from "./service-index.type";\n\n' +
    `export const SERVICES_INDEX: ServiceIndexEntry[] = ${JSON.stringify(index, null, 2)};\n`;
  const out = join(
    "apps",
    "api",
    "src",
    "content",
    "services-index.generated.ts",
  );
  // Format with Prettier so the written file matches what the lint-staged
  // pre-commit hook (`prettier --write`) would produce — otherwise the raw
  // JSON.stringify output (quoted keys, no trailing commas) always differs from
  // the committed file, and the CI drift guard would fail on formatting alone.
  // `filepath` lets Prettier infer the TypeScript parser, exactly as the hook does.
  const config = await resolveConfig(out);
  const formatted = await format(body, { ...config, filepath: out });
  await writeFile(out, formatted, "utf8");
  console.log(`Wrote ${index.length} services to ${out}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
