import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { buildFormCategories, loadContent } from "@govtech-bb/content";

async function main() {
  const { services, warnings } = await loadContent();
  for (const w of warnings) console.warn(w);
  const map = buildFormCategories(services);
  const sorted = Object.fromEntries(
    Object.entries(map).sort(([a], [b]) => a.localeCompare(b)),
  );
  const body =
    "// GENERATED by scripts/generate-form-categories.ts — do not edit by hand.\n" +
    "// Regenerate with `pnpm generate:form-categories` when landing content changes.\n" +
    `export const FORM_CATEGORIES: Record<string, string> = ${JSON.stringify(sorted, null, 2)};\n`;
  const out = join(
    "packages",
    "content",
    "src",
    "form-categories.generated.ts",
  );
  await writeFile(out, body, "utf8");
  console.log(
    `Wrote ${Object.keys(sorted).length} form→category entries to ${out}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
