// Generates packages/database/src/migrations/service-status-seed.data.ts — the
// one-time `service_status` seed (#1650) capturing every service's current
// static visibility (landing frontmatter + form recipe). Offline-safe
// (filesystem read only, no network). Regenerate when landing content or recipe
// visibility changes: `pnpm generate:service-status-seed`.
//
// Content side mirrors scripts/generate-services-index.ts (#1911); form side
// mirrors scripts/validate-recipes.ts (the served flat-file set). The derivation
// itself lives in the pure, unit-tested builder in packages/database/scripts.
import { readFile, readdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { buildServicesIndex, loadContent } from "@govtech-bb/content";
import { getRecipeVisibility } from "@govtech-bb/form-types";
import {
  buildServiceStatusSeed,
  type SeedFormVisibility,
} from "../packages/database/scripts/build-service-status-seed";

// Same path the API file loader, validate-recipes, and the dump script use.
// Legacy versioned dirs are frozen and excluded — only the flat files are served.
const RECIPES_ROOT = resolve(
  __dirname,
  "../apps/api/src/forms/form-definitions/recipes",
);

const OUT = join(
  "packages",
  "database",
  "src",
  "migrations",
  "service-status-seed.data.ts",
);

async function loadFormVisibilities(): Promise<
  Record<string, SeedFormVisibility>
> {
  const entries = await readdir(RECIPES_ROOT, { withFileTypes: true });
  const files = entries
    .filter((e) => e.isFile() && e.name.endsWith(".json"))
    .map((e) => e.name);

  const visibilities: Record<string, SeedFormVisibility> = {};
  for (const file of files) {
    // getRecipeVisibility reads only `meta` and defaults a missing
    // meta/visibility to "preview", so the narrow shape here is sufficient.
    const parsed = JSON.parse(
      await readFile(join(RECIPES_ROOT, file), "utf8"),
    ) as { formId?: string; meta?: { visibility: SeedFormVisibility } };
    const formId = parsed.formId ?? file.replace(/\.json$/, "");
    visibilities[formId] = getRecipeVisibility(parsed);
  }
  return visibilities;
}

async function main(): Promise<void> {
  const { services, warnings: contentWarnings } = await loadContent();
  for (const w of contentWarnings) console.warn(w);

  const contentEntries = buildServicesIndex(services);
  const formVisibilities = await loadFormVisibilities();

  const { rows, warnings } = buildServiceStatusSeed(
    contentEntries,
    formVisibilities,
  );

  for (const w of warnings) console.warn(`⚠ ${w}`);

  const counts = rows.reduce<Record<string, number>>((acc, r) => {
    acc[r.status] = (acc[r.status] ?? 0) + 1;
    return acc;
  }, {});

  const body =
    "// GENERATED by scripts/generate-service-status-seed.ts — do not edit by hand.\n" +
    "// Regenerate with `pnpm generate:service-status-seed` when landing content or\n" +
    "// recipe visibility changes. Consumed only by the SeedServiceStatus migration.\n" +
    'import type { ServiceStatus } from "../entities";\n\n' +
    "export const SERVICE_STATUS_SEED_ROWS: { slug: string; status: `${ServiceStatus}` }[] = " +
    JSON.stringify(rows, null, 2) +
    ";\n";

  await writeFile(OUT, body, "utf8");

  console.log(`Wrote ${rows.length} seed row(s) to ${OUT}`);
  console.log(
    `  by status: ${Object.entries(counts)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([k, v]) => `${k}=${v}`)
      .join(", ")}`,
  );
  if (warnings.length > 0) {
    console.log(
      `  ${warnings.length} warning(s) above — review before merging.`,
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
