/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsSearchRouteImport } from './routes/analytics/search'
import { Route as AnalyticsProjectsRouteImport } from './routes/analytics/projects'
import { Route as AnalyticsFormsIndexRouteImport } from './routes/analytics/forms/index'
import { Route as AnalyticsFormsFormIdRouteImport } from './routes/analytics/forms/$formId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsSearchRoute = AnalyticsSearchRouteImport.update({
  id: '/analytics/search',
  path: '/analytics/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsProjectsRoute = AnalyticsProjectsRouteImport.update({
  id: '/analytics/projects',
  path: '/analytics/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsFormsIndexRoute = AnalyticsFormsIndexRouteImport.update({
  id: '/analytics/forms/',
  path: '/analytics/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsFormsFormIdRoute = AnalyticsFormsFormIdRouteImport.update({
  id: '/analytics/forms/$formId',
  path: '/analytics/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics/projects': typeof AnalyticsProjectsRoute
  '/analytics/search': typeof AnalyticsSearchRoute
  '/analytics/forms/$formId': typeof AnalyticsFormsFormIdRoute
  '/analytics/forms/': typeof AnalyticsFormsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics/projects': typeof AnalyticsProjectsRoute
  '/analytics/search': typeof AnalyticsSearchRoute
  '/analytics/forms/$formId': typeof AnalyticsFormsFormIdRoute
  '/analytics/forms': typeof AnalyticsFormsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics/projects': typeof AnalyticsProjectsRoute
  '/analytics/search': typeof AnalyticsSearchRoute
  '/analytics/forms/$formId': typeof AnalyticsFormsFormIdRoute
  '/analytics/forms/': typeof AnalyticsFormsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics/projects'
    | '/analytics/search'
    | '/analytics/forms/$formId'
    | '/analytics/forms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics/projects'
    | '/analytics/search'
    | '/analytics/forms/$formId'
    | '/analytics/forms'
  id:
    | '__root__'
    | '/'
    | '/analytics/projects'
    | '/analytics/search'
    | '/analytics/forms/$formId'
    | '/analytics/forms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsProjectsRoute: typeof AnalyticsProjectsRoute
  AnalyticsSearchRoute: typeof AnalyticsSearchRoute
  AnalyticsFormsFormIdRoute: typeof AnalyticsFormsFormIdRoute
  AnalyticsFormsIndexRoute: typeof AnalyticsFormsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/search': {
      id: '/analytics/search'
      path: '/analytics/search'
      fullPath: '/analytics/search'
      preLoaderRoute: typeof AnalyticsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/projects': {
      id: '/analytics/projects'
      path: '/analytics/projects'
      fullPath: '/analytics/projects'
      preLoaderRoute: typeof AnalyticsProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/forms/': {
      id: '/analytics/forms/'
      path: '/analytics/forms'
      fullPath: '/analytics/forms/'
      preLoaderRoute: typeof AnalyticsFormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/forms/$formId': {
      id: '/analytics/forms/$formId'
      path: '/analytics/forms/$formId'
      fullPath: '/analytics/forms/$formId'
      preLoaderRoute: typeof AnalyticsFormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsProjectsRoute: AnalyticsProjectsRoute,
  AnalyticsSearchRoute: AnalyticsSearchRoute,
  AnalyticsFormsFormIdRoute: AnalyticsFormsFormIdRoute,
  AnalyticsFormsIndexRoute: AnalyticsFormsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
