// Active Participating Private Pharmacies (PPPs) — Barbados Drug Service,
// supplied 31 August 2026. This is the authoritative list: a private pharmacy
// on it takes the subsidy ('private-sbs'); anything absent is not a PPP and
// the patient pays full price. Government polyclinic dispensaries are not on
// this list and are classified separately.
//
// Transcribed verbatim from the Drug Service table (name / address / tel).
// Read by convert-pharmacies.mjs and asserted against in pharmacies.test.ts,
// so the record types cannot drift from this list. No app code imports it, so
// it never reaches the bundle.

// One line per pharmacy, left unformatted on purpose: the next refresh
// replaces this list wholesale, and a changed entry should read as a single
// changed line.
// prettier-ignore
export const ACTIVE_PPP = [
  { name: 'A.P Jones & Co. Ltd', address: '8 High Street, Bridgetown, St. Michael', tel: ['426-1289', '426-3241'] },
  { name: 'A Plus Care Pharmacy', address: 'Gall Hill Medical Centre, Gall Hill, Ch Ch', tel: ['428-3497'] },
  { name: 'Ace Pharmacy', address: '#3 10th Ave Belleville, St. Michael', tel: ['228-2026'] },
  { name: 'Advanced Care Pharmacy', address: 'Harts Gap, Hastings, Ch Ch', tel: ['228-6453'] },
  { name: 'Allington Pharmacy', address: 'Canewood Business Centre, Canewood, St. Michael', tel: ['622-2070'] },
  { name: 'Alpha Pharmacy', address: 'Sunny Side Complex, Black Rock Main Road', tel: ['426-3499'] },
  { name: 'Apothec Pharmacy', address: '“Athrol” Upper Collymore Rock, St. Michael', tel: ['436-6337'] },
  { name: 'Aqua Pharmacy', address: 'Shop #1 Coral Sands Complex, Worthing, Ch. Ch', tel: ['622-2782', '233-3118'] },
  { name: 'Avida Pharmacy', address: 'Ellerton Building, Welches, Ch Ch', tel: ['537-0294'] },
  { name: 'Avis Pharmacy', address: '#4 Thorpes Main Road, St. James', tel: ['438-4444'] },
  { name: 'Bato’s Pharmacy', address: 'King Street, Bridgetown, St. Michael', tel: ['426-1699'] },
  { name: 'Belmont Pharmacy', address: 'Belmont Road, St. Michael', tel: ['241-6203', '234-5841'] },
  { name: 'Betterlife Pharmacy', address: 'Building 2 #1 Friendship Terrace, Green Hill, St. Michael', tel: ['571-3788', '231-1862'] },
  { name: 'Beyond Pharmacy', address: '11 Dunscombe, St. Thomas', tel: ['571-7640', '824-0787'] },
  { name: 'Brittons Hill Dispensary', address: 'Brittons Hill Medical Centre', tel: ['429-5461'] },
  { name: 'BT Pharmacy', address: 'Sandy Crest Medical Centre', tel: ['422-0488'] },
  { name: 'CB Forde Ltd', address: 'Shoppers Centre, Black Rock, St. Michael', tel: ['425-9654'] },
  { name: 'C S Pharmacy', address: 'Trident House, Broad Street, Bridgetown', tel: ['427-2047', '426-0320'] },
  { name: 'Callies Pharmacy', address: 'Bayside Plaza, Upper Bay Street, St. Michael', tel: ['431-9560'] },
  { name: 'Callies Pharmacy', address: 'Cottage Plantation, St. John', tel: ['429-9346', '233-4757'] },
  { name: 'Collins Pharmacy', address: '28 Broad Street, Bridgetown', tel: ['426-4246'] },
  { name: 'Community Pharmacy', address: 'Ivy Medical Clinic', tel: ['431-8762'] },
  { name: 'Cosmopolitan Pharmacy', address: '121 Roebuck Street, Bridgetown, St. Michael', tel: ['436-6101'] },
  { name: 'Cosmopolitan Pharmacy', address: 'Six Roads, St. Philip', tel: ['423-6640'] },
  { name: 'Delaware Dispensary', address: 'Jemmotts Lane, St. Michael', tel: ['429-7430', '230-4795'] },
  { name: 'Drugmart', address: 'Salters, St. George', tel: ['622-4088', '248-3494'] },
  { name: 'Eagle Hall Pharmacy', address: 'Eagle Hall, St. Michael', tel: ['427-2828'] },
  { name: 'Elbethel Pharmacy', address: '6th Ave Belleville, St. Michael', tel: ['622-1405'] },
  { name: 'Elbethel Pharmacy', address: '2nd Ave Belleville, St. Michael', tel: ['437-9261'] },
  { name: 'Elbethel Pharmacy', address: 'Prerogative, St. George', tel: ['233-2141', '243-9248'] },
  { name: 'Elcourt Pharmacy', address: 'Maxwell Main Road, Ch Ch', tel: ['428-5323'] },
  { name: 'Elgar Pharmacy', address: '7 Thorpes, St. James', tel: ['438-5693'] },
  { name: 'Elgar Pharmacy', address: 'Market Hill, St. George', tel: ['435-4919'] },
  { name: 'Elitecare Pharmacy', address: 'Salters Market, Salters, St. George', tel: ['622-1923'] },
  { name: 'Enterprise Pharmacy', address: 'Enterprise Drive, Ch Ch', tel: ['546-6979', '259-4666'] },
  { name: 'Felimar Plus Pharmacy', address: 'Omni Plus Centre, Appleby Road, Appleby Gardens, St. James', tel: ['538-5685', '234-5746'] },
  { name: 'Flanders Pharmacy', address: 'Rickett Street, Bridgetown', tel: ['426-7198'] },
  { name: 'Get Well Pharmacy', address: 'Windsor Medical Centre, Cnr Govt Hill & Pine Plantation Rd, St. Michael', tel: ['622-4171', '828-9599'] },
  { name: 'Habibi Pharmacy', address: 'Riverside Medical Clinic, River Road, St. Michael', tel: ['826-6622', '232-7894'] },
  { name: 'H.C Walkes Pharmacy', address: '#47 Tudor Street, Bridgetown, St. Michael', tel: ['426-3707'] },
  { name: 'Healthrite Pharmacy', address: 'Specialist Centre, Black Rock, St. Michael', tel: ['421-3499'] },
  { name: 'Health Care Pharmacy', address: '101 Devlind Walmer Lodge, Black Rock, St. Michael', tel: ['425-2273'] },
  { name: 'Health Care Pharmacy', address: 'Cnr Westbury Road & St. Leonards Ave, St. Michael', tel: ['434-0754'] },
  { name: 'Health-Sync Pharmacy', address: '23 Maxwell Main Rd, Ch Ch', tel: ['258-3639'] },
  { name: 'Henley’s Pharmacy', address: 'Charles Rowe Bridge, St. George', tel: ['436-7417'] },
  { name: 'Heritage Pharmacy', address: 'Elma’s Complex, Spooners Hill, St. Michael', tel: ['425-3159'] },
  { name: 'Heritage Pharmacy', address: 'Kendal Hill, Christ Church', tel: ['622-2321'] },
  { name: 'Holborn Pharmacy', address: '#36A Pine Road, Belleville, St. Michael', tel: ['430-0675'] },
  { name: 'iMart Pharmacy Lanterns', address: 'Lanterns Mall, Hastings, Ch Ch', tel: ['271-0346', '826-1125'] },
  { name: 'iMart Pharmacy W Plaza', address: 'W Plaza, Welches, St. Thomas', tel: ['271-3784'] },
  { name: 'iMart Pharmacy Sheraton', address: 'Sheraton Mall, Sargeants Village, Ch Ch', tel: ['436-1231'] },
  { name: 'iMart Pharmacy Welches', address: 'Shop 11, Welches Plaza, St. Michael', tel: ['271-3784'] },
  { name: 'iMart Pharmacy Haggatt Hall', address: 'One Haggatt Hall, Haggatt Hall, St. Michael', tel: ['271-3784'] },
  { name: 'iMart Pharmacy The Estates', address: 'The Estates', tel: ['422-4156'] },
  { name: 'iMart Pharmacy', address: 'Wildey Commercial Centre, Wildey, St. Michael', tel: ['826-1127'] },
  { name: 'iMart Pharmacy Six Roads', address: 'One Six Roads, Emerald Park, Six Rds', tel: ['271-3784'] },
  { name: 'Jems Pharmacy', address: 'Four Roads Medical Clinic, Four Roads, St. Philip', tel: ['537-0231', '233-8887'] },
  { name: 'J & J Pharma-C', address: '#1 Cnr Sharon & Arthur Seat, St. Thomas', tel: ['537-2099', '833-3480'] },
  { name: 'Joes Pharmacy', address: 'Oistins, Christ Church', tel: ['271-8990'] },
  { name: 'Lewis Drug Mart', address: 'Rockley Main Road, Christ Church', tel: ['435-8090'] },
  { name: 'Lyte Drug Mart', address: 'Brittons Cross Road, St. Michael', tel: ['624-4581', '231-2366'] },
  { name: 'Massy Sargeants Village', address: 'Sargeants Village, Christ Church', tel: ['429-7107'] },
  { name: 'Massy Sunset Crest', address: 'Sunset Crest Plaza, St. James', tel: ['432-1290'] },
  { name: 'Massy Oistins', address: 'Southern Plaza, Oistins, Ch Ch', tel: ['428-6057'] },
  { name: 'Massy Six Roads', address: 'Cosmopolitan Place, Six Roads, St. Philip', tel: ['423-3700'] },
  { name: 'Massy Warrens', address: 'Warrens, St. Michael', tel: ['417-5232'] },
  { name: 'Massy Worthing', address: 'Peronne Plaza, Worthing, Ch Ch', tel: ['435-0020'] },
  { name: 'Massy Sky Mall', address: 'Sky Mall, Haggatt Hall, St. Michael', tel: ['434-1023'] },
  { name: 'Massy Coverley', address: '‘Villages’ Coverley, Christ Church', tel: ['623-7374'] },
  { name: 'Maxwell Pharmacy', address: 'Maxwell Coast Road, Christ Church', tel: ['420-2775'] },
  { name: 'Mayfield Pharmacy', address: 'Mayfield Medical Centre, 4th Ave Belleville, St. Michael', tel: ['427-6066', '233-7367'] },
  { name: 'Medshop Pharmacy', address: '“Hammersmith House” 3rd Ave Belleville, St. Michael', tel: ['622-4041'] },
  { name: 'Medpro Pharmacy', address: 'Prerogative House, Wilkinson Road, Prerogative, St. George', tel: ['285-0772'] },
  { name: 'Neighbourhood Care Pharmacy', address: 'Bank Hall Medical Clinic, Bank Hall, St. Michael', tel: ['427-0317'] },
  { name: 'Neighbourhood Care Pharmacy', address: 'Rock Dundo', tel: ['624-5160'] },
  { name: 'Nutripharm Services Inc', address: 'Blades Hill, St. Philip', tel: ['271-2653'] },
  { name: 'O’Hana Pharmacy', address: 'Gill’s Terrace, Speightstown, St. Peter', tel: ['422-1800'] },
  { name: 'One Up Pharmacy', address: 'Jemmotts Lane, St. Michael', tel: ['426-6387', '828-4897'] },
  { name: 'One Up Pharmacy', address: 'Unit 3B Wildey Mall, Wildey, St. Michael', tel: ['828-4897'] },
  { name: 'One Up Pharmacy', address: 'Lot 11&13 Lodge Hill Road', tel: ['426-6387', '828-4897'] },
  { name: 'One Up Pharmacy', address: 'Diagnostic Medical, Beckles Rd, St. Michael', tel: ['426-6387', '828-4897'] },
  { name: 'Palmcourt Dispensary', address: '#28 Pine Road, Belleville, St. Michael', tel: ['437-8098'] },
  { name: 'Pearsons Pharmacy', address: 'Upper Collymore Rock, St. Michael', tel: ['427-5521'] },
  { name: 'Pharmaceuticals Plus', address: 'Omni Mall, Speightstown, St. Peter', tel: ['422-1095'] },
  { name: 'Pharmacy World', address: 'Shop #1 The Peoples Market', tel: ['429-0334'] },
  { name: 'Pharmaco Ltd', address: 'Church Street, Speightstown, St. Peter', tel: ['422-1908'] },
  { name: 'Pharm-N-Care', address: '#49 Warrens Business Centre, Warrens, St. Michael', tel: ['421-8245'] },
  { name: 'Phillips Pharmacy', address: '287 Crystal Heights, St. James', tel: ['232-9069'] },
  { name: 'Pine Dispensary', address: 'Pine Medical Centre, 3rd Ave Belleville, St. Michael', tel: ['436-8678'] },
  { name: 'Premier Pharmacy', address: 'Dinkryst Medical Centre, Brittons Hill, St. Michael', tel: ['426-7456'] },
  { name: 'Prescriptions Online', address: 'Venture #3, St. John', tel: ['433-2048'] },
  { name: 'Prescriptions Plus', address: 'Shop #18 Canary Lane, George Street, Bridgetown', tel: ['435-7587'] },
  { name: 'Price Drug Mart', address: '2nd Ave Godding Rd, Station Hill, St. Michael', tel: ['824-1215', '285-9032'] },
  { name: 'Rosegate Pharmacy', address: 'RoseGate Medical Centre, Rosegate, St. John', tel: ['271-2745'] },
  { name: 'Roundhay Pharmacy', address: 'One Accord Plaza, Warrens Industrial Park, Warrens, St. Michael', tel: ['537-7863', '266-6587'] },
  { name: 'RX Pharma & Medical Supplies', address: 'Kensington New Road, St. Michael', tel: ['237-8374'] },
  { name: 'S.K Total Health', address: 'Rendezvous Court, Rendezvous, Ch Ch', tel: ['436-0140'] },
  { name: 'Standard Pharmacy', address: 'Upper Tweedside Rd, Carrington Village, St. Michael', tel: ['429-3298'] },
  { name: 'Strathclyde Pharmacy & Health Shop', address: 'Peterkin Rd, Bank Hall, St. Michael', tel: ['622-1970', '435-6581'] },
  { name: 'TDL Pharmacy', address: 'No.3 W H Golden Plaza, Montrose, Ch Ch', tel: ['537-0057'] },
  { name: 'The Pharmacy Hub', address: 'Spry Street, Bridgetown', tel: ['436-0172', '238-5133'] },
  { name: 'Total Care Pharmacy', address: 'Emerald City Supermarket, Six Rds, St. Philip', tel: ['423-1213'] },
  { name: 'Top Tier Pharmacy', address: 'Lot 51 Rouens Rd, Neils Tenantry, Tichbourne, St. Michael', tel: ['547-5674'] },
  { name: 'Unique Pharmacy', address: 'Ocean View Medical, St. Martins, St. Philip', tel: ['622-1797'] },
  { name: 'Vitalpharm Pharmacy', address: '4th Ave Belleville, St. Michael', tel: ['627-9238', '256-5582'] },
  { name: 'We Care Pharmacy', address: 'Pilgrim Road, Ch Ch', tel: ['538-2273', '263-3857'] },
  { name: 'Welches Pharmacy', address: '#43 Kingston Terrace, Welches, St. Michael', tel: ['538-0141'] },
  { name: 'Wellhouse Dispensary', address: 'Wellhouse Corner, Wellhouse, St. Philip', tel: ['423-3896'] },
  { name: 'Whole Health Pharmacy', address: 'Jordans Complex, Speightstown, St. Peter', tel: ['422-5207'] },
]
