/**
 * Pharmacies — Barbados
 * --------------------------------------------------------------
 * Single source of truth for the pharmacy finder at
 * /health-and-emergency-services/find-an-open-pharmacy.
 *
 * GENERATED from the GovTech pharmacy prototype dataset (23 July 2026), with
 * subsequent Drug Service review amendments — do not hand-edit records;
 * regenerate via the conversion script instead.
 * Provenance: government and Drug Service pharmacies come from the Drug
 * Service register, verified May 2026; 'unconfirmed' entries are drawn from
 * a wider public pharmacy list and have NOT been confirmed with the Drug
 * Service. Known conflicts are flagged in each record's notes. Keep
 * META.visibility 'preview' until the Drug Service signs the data off.
 */

export const PARISHES = [
  'Christ Church',
  'St. Andrew',
  'St. George',
  'St. James',
  'St. John',
  'St. Joseph',
  'St. Lucy',
  'St. Michael',
  'St. Peter',
  'St. Philip',
  'St. Thomas',
] as const

export type Parish = (typeof PARISHES)[number]

/** Weekday keys, Monday first (display order). */
export const WEEKDAYS = [
  'mon',
  'tue',
  'wed',
  'thu',
  'fri',
  'sat',
  'sun',
] as const

export type Weekday = (typeof WEEKDAYS)[number]

/**
 * One continuous opening period within a single day, 24-hour 'HH:MM'
 * wall-clock. Semantics are [opens, closes): open at 'opens' exactly,
 * closed at 'closes' exactly.
 */
export interface TimeRange {
  /** '00:00'–'23:59'. */
  opens: string
  /** Must be later than opens; '24:00' means end of day. */
  closes: string
}

/**
 * Opening ranges per day, earliest first. [] = closed that day; two ranges =
 * a split shift; a single 00:00–24:00 range = open 24 hours.
 */
export type WeeklyHours = Readonly<Record<Weekday, ReadonlyArray<TimeRange>>>

export interface LatLon {
  lat: number
  lon: number
}

/**
 * What the visit costs — the reader's decision variable.
 * government = free polyclinic dispensary; private-sbs = private pharmacy in
 * the Drug Service subsidy (small dispensing fee); unconfirmed = not on the
 * confirmed subsidy list (full price until confirmed otherwise).
 */
export type PharmacyType = 'government' | 'private-sbs' | 'unconfirmed'

export interface Pharmacy {
  name: string
  type: PharmacyType
  /** 'All parishes' is the island-wide delivery service. */
  parish: Parish | 'All parishes'
  address: string
  /** Display form '(246) NNN-NNNN'; '' when no number is listed. */
  phone: string
  /** Absent = opening hours not confirmed — open/closed state is unknown. */
  hours?: WeeklyHours
  /** Geocoded point, used for the "Use my location" distance sort. */
  coords?: LatLon
  notes?: string
  /** Bus routes from Bridgetown, when known. */
  routes?: string
  /**
   * Confirmed WhatsApp ordering number, display form '(246) NNN-NNNN'.
   * Only set where the pharmacy explicitly published one — a dead wa.me
   * link is worse than no button.
   */
  whatsapp?: string
}

export const PHARMACIES_LAST_UPDATED = '2026-08-25'
export const PHARMACIES_NEXT_REVIEW = '2027-01-01'
/** When the Drug Service register was last verified (shown per card). */
export const REGISTER_VERIFIED = 'May 2026'

export const PHARMACIES: ReadonlyArray<Pharmacy> = [
  {
    name: 'Winston Scott Polyclinic',
    type: 'government',
    parish: 'St. Michael',
    address: 'Jemmotts Lane, St. Michael',
    phone: '(246) 536-3419',
    hours: {
      mon: [{ opens: '08:15', closes: '22:00' }],
      tue: [{ opens: '08:15', closes: '22:00' }],
      wed: [{ opens: '08:15', closes: '22:00' }],
      thu: [{ opens: '08:15', closes: '22:00' }],
      fri: [{ opens: '08:15', closes: '22:00' }],
      sat: [{ opens: '08:15', closes: '16:30' }],
      sun: [],
    },
    notes: 'Latest-closing government pharmacy. The only one open Saturdays.',
    routes: 'Routes 11, 12 from Bridgetown Terminal (Probyn St)',
    coords: { lat: 13.091964, lon: -59.607581 },
  },
  {
    name: 'Branford Taitt Polyclinic',
    type: 'government',
    parish: 'St. Michael',
    address: 'Black Rock Main Road, St. Michael',
    phone: '(246) 536-3701',
    hours: {
      mon: [{ opens: '08:30', closes: '16:30' }],
      tue: [{ opens: '08:30', closes: '16:30' }],
      wed: [{ opens: '08:30', closes: '16:30' }],
      thu: [{ opens: '08:30', closes: '16:30' }],
      fri: [{ opens: '08:30', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    routes: 'Routes 11, 11A from Bridgetown Terminal',
    coords: { lat: 13.118089, lon: -59.618137 },
  },
  {
    name: 'Edgar Cochrane Polyclinic',
    type: 'government',
    parish: 'St. Michael',
    address: 'Wildey, St. Michael',
    phone: '(246) 536-4103',
    hours: {
      mon: [{ opens: '08:30', closes: '16:30' }],
      tue: [{ opens: '08:30', closes: '16:30' }],
      wed: [{ opens: '08:30', closes: '16:30' }],
      thu: [{ opens: '08:30', closes: '16:30' }],
      fri: [{ opens: '08:30', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    routes: 'Routes 11, 22 from Bridgetown',
    coords: { lat: 13.092702, lon: -59.586323 },
  },
  {
    name: 'Eunice Gibson Polyclinic',
    type: 'government',
    parish: 'St. Michael',
    address: 'Henry Dunant Road, Warrens, St. Michael',
    phone: '(246) 536-4000',
    hours: {
      mon: [{ opens: '08:15', closes: '16:30' }],
      tue: [{ opens: '08:15', closes: '16:30' }],
      wed: [{ opens: '08:15', closes: '16:30' }],
      thu: [{ opens: '08:15', closes: '16:30' }],
      fri: [{ opens: '08:15', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    routes: 'Routes 11, 11C from Bridgetown',
    coords: { lat: 13.141018, lon: -59.605905 },
  },
  {
    name: 'Randal Phillips Polyclinic',
    type: 'government',
    parish: 'Christ Church',
    address: 'Oistins Main Road, Oistins, Christ Church',
    phone: '(246) 536-4300',
    hours: {
      mon: [{ opens: '07:30', closes: '16:30' }],
      tue: [{ opens: '08:15', closes: '16:30' }],
      wed: [{ opens: '08:15', closes: '16:30' }],
      thu: [{ opens: '08:30', closes: '16:30' }],
      fri: [{ opens: '08:15', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    routes: 'Routes 30, 31 from Bridgetown (Fairchild St Terminal)',
    coords: { lat: 13.062149, lon: -59.540746 },
  },
  {
    name: 'Frederick Miller Polyclinic',
    type: 'government',
    parish: 'St. George',
    address: 'Glebe, St. George',
    phone: '(246) 536-3940',
    hours: {
      mon: [{ opens: '08:30', closes: '16:30' }],
      tue: [{ opens: '08:30', closes: '16:30' }],
      wed: [{ opens: '08:30', closes: '16:30' }],
      thu: [{ opens: '08:30', closes: '16:30' }],
      fri: [{ opens: '08:30', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    routes: 'Route 3 from Bridgetown (Fairchild St Terminal)',
    coords: { lat: 13.135065, lon: -59.563367 },
  },
  {
    name: 'David Thompson Health Complex',
    type: 'government',
    parish: 'St. John',
    address: 'Colleton Road, Glebe, St. John',
    phone: '(246) 416-7000',
    hours: {
      mon: [{ opens: '08:30', closes: '16:30' }],
      tue: [{ opens: '08:30', closes: '16:30' }],
      wed: [{ opens: '08:30', closes: '16:30' }],
      thu: [{ opens: '08:30', closes: '16:30' }],
      fri: [{ opens: '08:30', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    routes: 'Routes 3B or 5 from Bridgetown',
    coords: { lat: 13.18188, lon: -59.496353 },
  },
  {
    name: 'Maurice Byer Polyclinic',
    type: 'government',
    parish: 'St. Peter',
    address: 'Station Hill, St. Peter',
    phone: '(246) 536-3200',
    hours: {
      mon: [{ opens: '08:15', closes: '16:30' }],
      tue: [{ opens: '08:15', closes: '16:30' }],
      wed: [{ opens: '08:15', closes: '16:30' }],
      thu: [{ opens: '08:15', closes: '16:30' }],
      fri: [{ opens: '08:15', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    routes: 'Route 1B from Bridgetown (Lower Green Terminal)',
    coords: { lat: 13.25357, lon: -59.638514 },
  },
  {
    name: 'St. Philip Polyclinic',
    type: 'government',
    parish: 'St. Philip',
    address: 'Six Roads, St. Philip',
    phone: '(246) 536-4215',
    hours: {
      mon: [{ opens: '08:15', closes: '16:30' }],
      tue: [{ opens: '08:15', closes: '16:30' }],
      wed: [{ opens: '08:15', closes: '16:30' }],
      thu: [{ opens: '08:15', closes: '16:30' }],
      fri: [{ opens: '08:15', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    routes: 'Route 10 from Bridgetown (Fairchild St Terminal)',
    coords: { lat: 13.118084, lon: -59.476286 },
  },
  {
    name: 'St. Andrew Outpatient Clinic',
    type: 'government',
    parish: 'St. Andrew',
    address: 'Belleplaine, St. Andrew',
    phone: '(246) 536-4071',
    hours: {
      mon: [{ opens: '08:15', closes: '12:00' }],
      tue: [],
      wed: [{ opens: '08:15', closes: '12:00' }],
      thu: [],
      fri: [],
      sat: [],
      sun: [],
    },
    notes: 'Open Mondays and Wednesdays only.',
    routes: 'Route 2 from Bridgetown (Lower Green Terminal)',
    coords: { lat: 13.24567, lon: -59.562925 },
  },
  {
    name: 'St. Joseph Outpatient Clinic',
    type: 'government',
    parish: 'St. Joseph',
    address: 'Horse Hill, St. Joseph',
    phone: '(246) 536-3285',
    hours: {
      mon: [],
      tue: [{ opens: '08:15', closes: '16:30' }],
      wed: [{ opens: '08:15', closes: '16:30' }],
      thu: [],
      fri: [{ opens: '08:15', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    notes: 'Three days per week.',
    routes: 'Route 5 from Bridgetown',
    coords: { lat: 13.20049, lon: -59.538843 },
  },
  {
    name: 'St. Thomas Outpatient Clinic',
    type: 'government',
    parish: 'St. Thomas',
    address: 'Rock Hall, St. Thomas',
    phone: '(246) 536-4952',
    hours: {
      mon: [],
      tue: [{ opens: '08:15', closes: '16:30' }],
      wed: [],
      thu: [{ opens: '08:15', closes: '16:30' }],
      fri: [{ opens: '08:15', closes: '16:30' }],
      sat: [],
      sun: [],
    },
    notes: 'Three days per week.',
    routes: 'Route 6 from Bridgetown',
    coords: { lat: 13.186991, lon: -59.604351 },
  },
  {
    name: 'iMart Pharmacy — Lanterns Mall',
    type: 'private-sbs',
    parish: 'Christ Church',
    address: 'Lanterns Mall, Christ Church',
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '08:00', closes: '20:00' }],
      tue: [{ opens: '08:00', closes: '20:00' }],
      wed: [{ opens: '08:00', closes: '20:00' }],
      thu: [{ opens: '08:00', closes: '20:00' }],
      fri: [{ opens: '08:00', closes: '20:00' }],
      sat: [{ opens: '08:00', closes: '20:00' }],
      sun: [{ opens: '09:00', closes: '14:00' }],
    },
    notes: 'WhatsApp prescription service available.',
    routes: 'Routes 30, 31 from Bridgetown',
    coords: { lat: 13.076846, lon: -59.594315 },
  },
  {
    name: 'iMart Pharmacy — Sheraton Mall',
    type: 'private-sbs',
    parish: 'Christ Church',
    address: "Sheraton Centre, Sargeant's Village, Christ Church",
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '09:00', closes: '20:00' }],
      tue: [{ opens: '09:00', closes: '20:00' }],
      wed: [{ opens: '09:00', closes: '20:00' }],
      thu: [{ opens: '09:00', closes: '20:00' }],
      fri: [{ opens: '09:00', closes: '20:00' }],
      sat: [{ opens: '09:00', closes: '20:00' }],
      sun: [],
    },
    notes: 'WhatsApp prescription service available.',
    routes: 'Routes 11, 22 from Bridgetown',
    coords: { lat: 13.083436, lon: -59.567168 },
  },
  {
    name: 'iMart Pharmacy — Haggatt Hall',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Haggatt Hall, St. Michael',
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '08:00', closes: '20:00' }],
      tue: [{ opens: '08:00', closes: '20:00' }],
      wed: [{ opens: '08:00', closes: '20:00' }],
      thu: [{ opens: '08:00', closes: '20:00' }],
      fri: [{ opens: '08:00', closes: '20:00' }],
      sat: [{ opens: '08:00', closes: '20:00' }],
      sun: [{ opens: '09:00', closes: '14:00' }],
    },
    notes: 'WhatsApp prescription service available.',
    routes: 'Routes 11, 11C from Bridgetown',
    coords: { lat: 13.108148, lon: -59.578662 },
  },
  {
    name: 'iMart Pharmacy — The Walk, Welches',
    type: 'private-sbs',
    parish: 'St. Thomas',
    address: 'The Walk at Welches, St. Thomas',
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '08:00', closes: '20:00' }],
      tue: [{ opens: '08:00', closes: '20:00' }],
      wed: [{ opens: '08:00', closes: '20:00' }],
      thu: [{ opens: '08:00', closes: '20:00' }],
      fri: [{ opens: '08:00', closes: '20:00' }],
      sat: [{ opens: '08:00', closes: '20:00' }],
      sun: [{ opens: '09:00', closes: '14:00' }],
    },
    notes: 'WhatsApp prescription service available.',
    routes: 'Routes 30, 31 from Bridgetown',
    coords: { lat: 13.15516, lon: -59.610324 },
  },
  {
    name: 'iMart Pharmacy — Wildey Commercial Centre',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Wildey, St. Michael',
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '08:00', closes: '20:00' }],
      tue: [{ opens: '08:00', closes: '20:00' }],
      wed: [{ opens: '08:00', closes: '20:00' }],
      thu: [{ opens: '08:00', closes: '20:00' }],
      fri: [{ opens: '08:00', closes: '20:00' }],
      sat: [{ opens: '08:00', closes: '20:00' }],
      sun: [],
    },
    notes: 'WhatsApp prescription service available.',
    routes: 'Routes 11, 22 from Bridgetown',
    coords: { lat: 13.092504, lon: -59.584983 },
  },
  {
    name: 'iMart Pharmacy — Six Roads',
    type: 'private-sbs',
    parish: 'St. Philip',
    address: 'Emerald Park, Six Cross Roads, St. Philip',
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '08:00', closes: '20:00' }],
      tue: [{ opens: '08:00', closes: '20:00' }],
      wed: [{ opens: '08:00', closes: '20:00' }],
      thu: [{ opens: '08:00', closes: '20:00' }],
      fri: [{ opens: '08:00', closes: '20:00' }],
      sat: [{ opens: '08:00', closes: '20:00' }],
      sun: [],
    },
    notes: 'Bank holidays 10am–2pm.',
    routes: 'Route 10 from Bridgetown',
    coords: { lat: 13.114636, lon: -59.478382 },
  },
  {
    name: 'iMart Pharmacy — The Estates',
    type: 'private-sbs',
    parish: 'St. George',
    address: 'Boarded Hall, St. George',
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '08:00', closes: '20:00' }],
      tue: [{ opens: '08:00', closes: '20:00' }],
      wed: [{ opens: '08:00', closes: '20:00' }],
      thu: [{ opens: '08:00', closes: '20:00' }],
      fri: [{ opens: '08:00', closes: '20:00' }],
      sat: [{ opens: '08:00', closes: '20:00' }],
      sun: [{ opens: '09:00', closes: '14:00' }],
    },
    notes: 'Bank holidays 10am–2pm.',
    routes: 'Route 3 from Bridgetown',
    coords: { lat: 13.108848, lon: -59.543596 },
  },
  {
    name: 'iMart Pharmacy — W Plaza',
    type: 'private-sbs',
    parish: 'St. Thomas',
    address: 'Welches, St. Thomas',
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '09:00', closes: '18:00' }],
      tue: [{ opens: '09:00', closes: '18:00' }],
      wed: [{ opens: '09:00', closes: '18:00' }],
      thu: [{ opens: '09:00', closes: '18:00' }],
      fri: [{ opens: '09:00', closes: '18:00' }],
      sat: [{ opens: '09:00', closes: '18:00' }],
      sun: [],
    },
    routes: 'Route 6 from Bridgetown',
    coords: { lat: 13.152919, lon: -59.61432 },
  },
  {
    name: 'DASAE Pharmacy (Sparman Clinic)',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Belleville, St. Michael',
    phone: '(246) 624-3278',
    hours: {
      mon: [{ opens: '00:00', closes: '17:00' }],
      tue: [{ opens: '00:00', closes: '17:00' }],
      wed: [{ opens: '00:00', closes: '17:00' }],
      thu: [{ opens: '00:00', closes: '17:00' }],
      fri: [{ opens: '00:00', closes: '17:00' }],
      sat: [{ opens: '00:00', closes: '08:00' }],
      sun: [{ opens: '00:00', closes: '08:00' }],
    },
    notes:
      'This pharmacy serves overnight shift workers: it opens at midnight and closes in the afternoon or morning. If you are visiting in normal daytime hours, note it is closed after 5pm on weekdays and after 8am at weekends. Always call (246) 624-3278 to confirm before visiting.',
    routes: 'Routes 12, 22 from Bridgetown',
    coords: { lat: 13.096193, lon: -59.604597 },
  },
  {
    name: 'HealthRite Pharmacy',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'The Specialist Centre, Black Rock Main Road, St. Michael',
    phone: '(246) 421-3499',
    notes: 'Blood pressure and glucose testing available.',
    routes: 'Routes 11, 11A from Bridgetown',
    coords: { lat: 13.117804, lon: -59.603729 },
  },
  {
    name: 'Pharmaceuticals Plus Inc',
    type: 'private-sbs',
    parish: 'St. Peter',
    address: 'Omni Mall, Queen Street, Speightstown, St. Peter',
    phone: '(246) 422-1095',
    routes: 'Route 1B from Bridgetown northbound',
    coords: { lat: 13.249397, lon: -59.643499 },
  },
  {
    name: 'Rx Plus Pharmacy',
    type: 'private-sbs',
    parish: 'St. Peter',
    address: 'Singh Medical Centre, Queen Street, Speightstown, St. Peter',
    phone: '(246) 422-7636',
    routes: 'Route 1B from Bridgetown northbound',
    coords: { lat: 13.249159, lon: -59.643444 },
  },
  {
    name: 'Felimar Plus Pharmacy',
    type: 'private-sbs',
    parish: 'St. James',
    address: 'Appleby Road, Appleby, St. James',
    phone: '(246) 538-5685',
    notes: 'Drive-through service available.',
    routes: 'Route 1 from Bridgetown northbound',
    coords: { lat: 13.154253, lon: -59.636022 },
  },
  {
    name: 'Lewis Drug Mart',
    type: 'private-sbs',
    parish: 'Christ Church',
    address: 'Rockley Main Road, Rockley, Christ Church',
    phone: '(246) 435-8090',
    notes:
      '25+ years serving Barbadians and visitors. DATA CONFLICT: a Barbados business directory lists Lewis Drug Mart at Carmen, Rockley / Highway 7 — verify with the Drug Service.',
    routes: 'Routes 30, 31 from Bridgetown',
    coords: { lat: 13.072427, lon: -59.590732 },
  },
  {
    name: 'Acare Pharmacy',
    type: 'private-sbs',
    parish: 'Christ Church',
    address: 'Gall Hill Medical Centre, Christ Church',
    phone: '(246) 428-3497',
    routes: 'Routes 30, 31 from Bridgetown',
    coords: { lat: 13.079943, lon: -59.538333 },
  },
  {
    name: "Connolly's Pharmacy",
    type: 'private-sbs',
    parish: 'St. Philip',
    address: 'Emerald City Supermarket, Six Roads, St. Philip',
    phone: '(246) 423-4937',
    notes:
      "DATA CONFLICT: a Barbados business directory lists Connolly's at Hadley House, Lower Broad Street, Bridgetown — a different parish. Verify with the Drug Service.",
    routes: 'Route 10 from Bridgetown',
    coords: { lat: 13.113997, lon: -59.474283 },
  },
  {
    name: 'Cosmopolitan Pharmacy',
    type: 'private-sbs',
    parish: 'St. Philip',
    address: 'Six Roads, St. Philip',
    phone: '(246) 423-6640',
    routes: 'Route 10 from Bridgetown',
    coords: { lat: 13.115907, lon: -59.475789 },
  },
  {
    name: 'Market Hill Dispensary',
    type: 'private-sbs',
    parish: 'St. George',
    address: 'Bridge Cot, St. George',
    phone: '(246) 437-9909',
    routes: 'Route 3 from Bridgetown',
    coords: { lat: 13.150422, lon: -59.556477 },
  },
  {
    name: 'SWM Pharmacy',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Bank Hall Plaza, Hill Road, Bank Hall, St. Michael',
    phone: '(246) 429-7378',
    routes: 'Routes 2, 3 from Bridgetown',
    coords: { lat: 13.113246, lon: -59.610157 },
  },
  {
    name: 'Community Pharmacy',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Ivy Medical Clinic, Ivy May Road, St. Michael',
    phone: '(246) 429-8762',
    routes: 'Routes 11, 12 from Bridgetown',
    coords: { lat: 13.117282, lon: -59.599367 },
  },
  {
    name: 'Rxpharma & Medical Supplies Dispensary',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Kensington New Road, St. Michael',
    phone: '(246) 237-8374',
    hours: {
      mon: [
        { opens: '08:00', closes: '15:00' },
        { opens: '18:45', closes: '21:00' },
      ],
      tue: [
        { opens: '08:00', closes: '15:00' },
        { opens: '18:45', closes: '21:00' },
      ],
      wed: [
        { opens: '08:00', closes: '15:00' },
        { opens: '18:45', closes: '21:00' },
      ],
      thu: [
        { opens: '08:00', closes: '15:00' },
        { opens: '18:45', closes: '21:00' },
      ],
      fri: [
        { opens: '08:00', closes: '15:00' },
        { opens: '18:45', closes: '21:00' },
      ],
      sat: [{ opens: '08:00', closes: '13:30' }],
      sun: [{ opens: '08:00', closes: '12:30' }],
    },
    notes: 'Also (246) 237-8992.',
    coords: { lat: 13.101808, lon: -59.618736 },
  },
  {
    name: 'BT Pharmacy',
    type: 'private-sbs',
    parish: 'St. James',
    address: 'Sandy Crest Medical Centre, Holetown, St. James',
    phone: '(246) 422-0488',
    hours: {
      mon: [{ opens: '08:00', closes: '19:00' }],
      tue: [{ opens: '08:00', closes: '19:00' }],
      wed: [{ opens: '08:00', closes: '19:00' }],
      thu: [{ opens: '08:00', closes: '19:00' }],
      fri: [{ opens: '08:00', closes: '19:00' }],
      sat: [{ opens: '08:00', closes: '19:00' }],
      sun: [{ opens: '08:00', closes: '16:00' }],
    },
    notes: 'Hours do not change on bank holidays.',
    routes: 'Route 1 from Bridgetown northbound',
    coords: { lat: 13.182416, lon: -59.635393 },
  },
  {
    name: 'Top Tier Pharmacy',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: "Lot 51 Rouen Road, Neil's Tenantry, St. Michael",
    phone: '(246) 547-5674',
    hours: {
      mon: [{ opens: '08:00', closes: '17:00' }],
      tue: [{ opens: '08:00', closes: '19:00' }],
      wed: [{ opens: '08:00', closes: '17:00' }],
      thu: [{ opens: '08:00', closes: '19:00' }],
      fri: [{ opens: '08:00', closes: '17:00' }],
      sat: [{ opens: '09:00', closes: '17:00' }],
      sun: [],
    },
    coords: { lat: 13.119435, lon: -59.599597 },
  },
  {
    name: 'OneUp Pharmacy — Wildey Mall',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Wildey Mall, Wildey, St. Michael',
    phone: '(246) 426-6387',
    hours: {
      mon: [{ opens: '08:30', closes: '15:30' }],
      tue: [{ opens: '08:30', closes: '15:30' }],
      wed: [{ opens: '08:30', closes: '15:30' }],
      thu: [{ opens: '08:30', closes: '15:30' }],
      fri: [{ opens: '08:30', closes: '15:30' }],
      sat: [{ opens: '08:30', closes: '17:30' }],
      sun: [],
    },
    notes: 'Telephone / WhatsApp +1 (246) 426-6387. oneuppharmacy.com',
    routes: 'Routes 11, 22 from Bridgetown',
    coords: { lat: 13.093396, lon: -59.583396 },
    whatsapp: '(246) 426-6387',
  },
  {
    name: 'OneUp Pharmacy — Jemmotts Lane',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Jemmotts Lane, St. Michael',
    phone: '(246) 426-6387',
    hours: {
      mon: [{ opens: '08:00', closes: '16:30' }],
      tue: [{ opens: '08:00', closes: '16:30' }],
      wed: [{ opens: '08:00', closes: '16:30' }],
      thu: [{ opens: '08:00', closes: '16:30' }],
      fri: [{ opens: '08:00', closes: '16:30' }],
      sat: [{ opens: '08:00', closes: '15:30' }],
      sun: [],
    },
    notes: 'Telephone / WhatsApp +1 (246) 426-6387. oneuppharmacy.com',
    coords: { lat: 13.092381, lon: -59.608722 },
    whatsapp: '(246) 426-6387',
  },
  {
    name: 'OneUp Pharmacy — Triad Health',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Triad Health Centre, St. Michael',
    phone: '(246) 426-6387',
    hours: {
      mon: [{ opens: '08:30', closes: '16:30' }],
      tue: [{ opens: '08:30', closes: '16:30' }],
      wed: [{ opens: '08:30', closes: '16:30' }],
      thu: [{ opens: '08:30', closes: '16:30' }],
      fri: [{ opens: '08:30', closes: '16:30' }],
      sat: [{ opens: '09:00', closes: '13:30' }],
      sun: [],
    },
    notes: 'Telephone / WhatsApp +1 (246) 426-6387. oneuppharmacy.com',
    coords: { lat: 13.119856, lon: -59.599402 },
    whatsapp: '(246) 426-6387',
  },
  {
    name: 'OneUp Pharmacy — Diagnostic Medical',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Diagnostic Medical, St. Michael',
    phone: '(246) 426-6387',
    hours: {
      mon: [{ opens: '08:00', closes: '15:00' }],
      tue: [{ opens: '08:00', closes: '15:00' }],
      wed: [{ opens: '08:00', closes: '15:00' }],
      thu: [{ opens: '08:00', closes: '15:00' }],
      fri: [{ opens: '08:00', closes: '15:00' }],
      sat: [{ opens: '08:00', closes: '13:00' }],
      sun: [],
    },
    notes: 'Telephone / WhatsApp +1 (246) 426-6387. oneuppharmacy.com',
    coords: { lat: 13.119736, lon: -59.599475 },
    whatsapp: '(246) 426-6387',
  },
  {
    name: 'Callies Pharmacy — Bayside',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Bayside Plaza, Bay Street, St. Michael',
    phone: '(246) 431-9560',
    hours: {
      mon: [{ opens: '08:30', closes: '16:30' }],
      tue: [{ opens: '08:30', closes: '16:30' }],
      wed: [{ opens: '08:30', closes: '16:30' }],
      thu: [{ opens: '08:30', closes: '16:30' }],
      fri: [{ opens: '08:30', closes: '16:30' }],
      sat: [{ opens: '08:30', closes: '14:00' }],
      sun: [{ opens: '09:00', closes: '13:00' }],
    },
    notes: 'Bank holidays 9am–12pm.',
    routes: 'Routes 11, 12 from Bridgetown',
    coords: { lat: 13.085684, lon: -59.608612 },
  },
  {
    name: 'Callies Pharmacy — Cottage',
    type: 'private-sbs',
    parish: 'St. George',
    address: 'Cottage Plantation, St. George',
    phone: '(246) 429-9346',
    hours: {
      mon: [{ opens: '09:00', closes: '15:00' }],
      tue: [{ opens: '09:00', closes: '15:00' }],
      wed: [{ opens: '09:00', closes: '15:00' }],
      thu: [{ opens: '09:00', closes: '15:00' }],
      fri: [{ opens: '09:00', closes: '15:00' }],
      sat: [{ opens: '09:00', closes: '13:00' }],
      sun: [],
    },
    routes: 'Route 3 from Bridgetown',
    coords: { lat: 13.154822, lon: -59.553607 },
  },
  {
    name: 'Elcourt Pharmacy',
    type: 'private-sbs',
    parish: 'Christ Church',
    address: 'Maxwell Main Road, Christ Church',
    phone: '(246) 428-5323',
    notes:
      'Listed as 8am–10pm — call to confirm opening days. Address and phone from a Barbados business directory — confirm opening days and whether they offer the government subsidy with the Drug Service.',
  },
  {
    name: 'Lyte Drug Mart',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Brittons Cross Roads, St. Michael',
    phone: '(246) 624-4581',
    notes:
      'Listed as 8am–5:30pm — call to confirm opening days. Address, phone and opening days to be confirmed with the Drug Service.',
    coords: { lat: 13.088571, lon: -59.596507 },
  },
  {
    name: 'Palmcourt Dispensary',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: '28 Pine Road, Belleville, St. Michael',
    phone: '(246) 437-8098',
    notes:
      'Listed as 8am–4:30pm — call to confirm opening days. Address and phone from a Barbados business directory — confirm opening days and whether they offer the government subsidy with the Drug Service.',
  },
  {
    name: 'Holborn Pharmacy',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: '36A Pine Road, St. Michael',
    phone: '(246) 427-8143',
    hours: {
      mon: [{ opens: '08:00', closes: '18:00' }],
      tue: [{ opens: '08:00', closes: '18:00' }],
      wed: [{ opens: '08:00', closes: '18:00' }],
      thu: [{ opens: '08:00', closes: '18:00' }],
      fri: [{ opens: '08:00', closes: '18:00' }],
      sat: [{ opens: '08:00', closes: '18:00' }],
      sun: [],
    },
    notes: 'Opening days assumed Mon–Sat — confirm with the Drug Service.',
    coords: { lat: 13.095956, lon: -59.601443 },
  },
  {
    name: 'Ace Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Pine Housing Estate, St. Michael',
    phone: '(246) 228-2026',
    notes:
      'DATA CONFLICT: a Barbados business directory lists Ace Pharmacy at 3 10th Ave, Belleville — verify with the Drug Service.',
    coords: { lat: 13.09793, lon: -59.605172 },
  },
  {
    name: 'Bayside Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Mall Internationale, Haggatt Hall, St. Michael',
    phone: '(246) 228-2255',
    coords: { lat: 13.096997, lon: -59.597342 },
  },
  {
    name: 'C S Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Trident House, Broad Street, Bridgetown',
    phone: '(246) 427-2047',
    coords: { lat: 13.10024, lon: -59.617016 },
  },
  {
    name: 'Collins Limited',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Broad Street, Bridgetown',
    phone: '(246) 426-4515',
    coords: { lat: 13.100006, lon: -59.616987 },
  },
  {
    name: 'Delaware Dispensary',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Jemmotts Lane, St. Michael',
    phone: '(246) 429-7430',
    coords: { lat: 13.092888, lon: -59.608285 },
  },
  {
    name: 'Eagle Hall Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Eagle Hall, St. Michael',
    phone: '',
    coords: { lat: 13.111866, lon: -59.61516 },
  },
  {
    name: 'Elgar Pharmacy',
    type: 'unconfirmed',
    parish: 'St. James',
    address: '7 Thorpes, St. James',
    phone: '(246) 438-5693',
    coords: { lat: 13.176701, lon: -59.638591 },
  },
  {
    name: 'Family Health Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Warrens Industrial Park, St. Michael',
    phone: '(246) 421-8245',
    coords: { lat: 13.143432, lon: -59.60743 },
  },
  {
    name: 'Flanders Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: '5 Ricketts Street, Bridgetown',
    phone: '(246) 426-7198',
    coords: { lat: 13.100169, lon: -59.617014 },
  },
  {
    name: 'Friendship Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: '23 Baxters Road, St. Michael',
    phone: '(246) 438-9218',
    notes:
      'DATA CONFLICT: a Barbados business directory lists Friendship Pharmacy at Manor Lodge Complex, Lodge Hill, and shows 23 Baxters Road as Total Care Pharmacy — this address may be mislabelled. Verify with the Drug Service.',
    coords: { lat: 13.104791, lon: -59.618223 },
  },
  {
    name: 'Grants Pharmacy & Cosmetique',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Fairchild Street, Bridgetown',
    phone: '(246) 228-0496',
    coords: { lat: 13.098974, lon: -59.616191 },
  },
  {
    name: 'Maxwell Pharmacy',
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Maxwell, Christ Church',
    phone: '',
    coords: { lat: 13.070873, lon: -59.563742 },
  },
  {
    name: 'Medic Aid Dispensary',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Corner Wavell Ave & Black Rock Main Rd, St. Michael',
    phone: '(246) 425-9999',
    coords: { lat: 13.09934, lon: -59.626111 },
  },
  {
    name: 'Neighbourhood Care Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Rock Dundo, Cave Hill, St. Michael',
    phone: '',
    coords: { lat: 13.136058, lon: -59.626065 },
  },
  {
    name: 'Pharm-N-Care Pharmacy',
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Unit 3, Emperors Court, Worthing, Christ Church',
    phone: '(246) 426-2601',
    notes:
      'Address, parish and phone from a Barbados business directory — confirm with the Drug Service.',
    coords: { lat: 13.076596, lon: -59.57795 },
  },
  {
    name: 'The Pharmacy Shoppe',
    type: 'unconfirmed',
    parish: 'St. Thomas',
    address: 'Welchman Hall, St. Thomas',
    phone: '(246) 438-5926',
    coords: { lat: 13.189991, lon: -59.577626 },
  },
  {
    name: 'Pharmacy World Inc',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Peterkin Road, Bank Hall, St. Michael',
    phone: '(246) 429-0334',
    notes:
      'Address and phone from a Barbados business directory — confirm with the Drug Service.',
    coords: { lat: 13.110854, lon: -59.613587 },
  },
  {
    name: 'Station Hill Medical Complex Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Peter',
    address: 'Godding Road, Station Hill, St. Peter',
    phone: '',
    coords: { lat: 13.251389, lon: -59.639723 },
  },
  {
    name: 'JillAnDeeHLP — Island-wide Delivery',
    type: 'unconfirmed',
    parish: 'All parishes',
    address: 'Island-wide delivery service',
    phone: '(246) 264-6768',
    notes: 'Delivery service available island-wide.',
  },
  {
    name: '1 - Stop Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'George Saint Belleville, St. Michael',
    phone: '(246) 426-8771',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.097735, lon: -59.603193 },
  },
  {
    name: 'Alpha Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Sunny Side Complex, Black Rock, St. Michael',
    phone: '(246) 426-3499',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.099174, lon: -59.611161 },
  },
  {
    name: 'Apothec Pharmacy',
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Worthing, Christ Church',
    phone: '(246) 436-6337',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.070991, lon: -59.580453 },
  },
  {
    name: 'Avis Pharmacy',
    type: 'unconfirmed',
    parish: 'St. James',
    address: '28 Thorpes Main Road, St. James',
    phone: '(246) 438-4444',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.151059, lon: -59.623756 },
  },
  {
    name: 'Belleville Dispensary',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Corner George St & 3rd Avenue, St. Michael',
    phone: '(246) 429-5616',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.101584, lon: -59.611308 },
  },
  {
    name: 'Brittons Hill Dispensary',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Corner Flagstaff & Brittons New Road, St. Michael',
    phone: '(246) 429-5461',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.10155, lon: -59.611341 },
  },
  {
    name: 'Callies Pharmacy — Garrison',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Brigade House Garrison, St. Michael',
    phone: '(246) 429-9346',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.101481, lon: -59.611396 },
  },
  {
    name: 'Carledon Drug Emporium Inc',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Lr Bay St, St. Michael',
    phone: '(246) 228-2476',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.101387, lon: -59.611467 },
  },
  {
    name: 'Carlton Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Carlton Complex, Black Rock Main Road, St. Michael',
    phone: '(246) 425-1604',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.101257, lon: -59.61156 },
  },
  {
    name: "Cave's Pharmacy",
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Worthing Plaza, Christ Church',
    phone: '(246) 435-7460',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.070723, lon: -59.579373 },
  },
  {
    name: "Crayton's Pharmacy",
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Gall Hill Medical Centre, Christ Church',
    phone: '(246) 428-3497',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.070256, lon: -59.54074 },
  },
  {
    name: 'DNK Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Wildey Main Road, St. Michael',
    phone: '(246) 427-7070',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.093217, lon: -59.592847 },
  },
  {
    name: 'E C Gill Drugstore',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Marhill St, St. Michael',
    phone: '(246) 426-2454',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.097549, lon: -59.613494 },
  },
  {
    name: 'Eastern Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Philip',
    address: 'Church Village, St. Philip',
    phone: '(246) 423-4449',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.138901, lon: -59.488371 },
  },
  {
    name: 'Elbethel Pharmacy — 2nd Avenue',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: '2nd Avenue, Belleville, St. Michael',
    phone: '(246) 437-9261',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.099119, lon: -59.611222 },
  },
  {
    name: 'Felimar Drug Mart',
    type: 'unconfirmed',
    parish: 'St. James',
    address: 'Jordans Complex Fitts Vlge, St. James',
    phone: '(246) 417-5685',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.17917, lon: -59.635632 },
  },
  {
    name: 'Forde C B Pharmacy Ltd',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Shoppers Centre Black Rock, St. Michael',
    phone: '(246) 425-9654',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.0988, lon: -59.611047 },
  },
  {
    name: "Gill Shirley S (Gill's Pharmacy)",
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Chapel St Nr Tudor St',
    phone: '(246) 427-2654',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.097926, lon: -59.609707 },
  },
  {
    name: 'Griffiths Reliance Pharmacy Ltd',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: "Lr Dayrell's Road, St. Michael",
    phone: '(246) 426-0438',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.097918, lon: -59.609191 },
  },
  {
    name: 'Grosvenor Pharmacy Inc',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Beckles Road, St. Michael',
    phone: '(246) 436-6842',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.087087, lon: -59.604372 },
  },
  {
    name: 'Hastings Pharmacy',
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Skyway Plaza, Christ Church',
    phone: '(246) 429-8932',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.074388, lon: -59.596224 },
  },
  {
    name: 'Health Care Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: '101 Devlind Lr Black Rock Tel/Fax, St. Michael',
    phone: '(246) 425-2273',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.100699, lon: -59.60721 },
  },
  {
    name: "Henley's Pharmacy",
    type: 'unconfirmed',
    parish: 'St. George',
    address: 'Charles Rowe Bridge, St. George, Froster Hall',
    phone: '(246) 436-7417',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.130525, lon: -59.550329 },
  },
  {
    name: 'Heritage Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Spooners Hill, St. Michael',
    phone: '(246) 425-3159',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.122228, lon: -59.609911 },
  },
  {
    name: 'Imperial Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Bethesda Black Rock, St. Michael',
    phone: '(246) 436-1744',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.102518, lon: -59.610162 },
  },
  {
    name: 'Jems Pharmacy',
    type: 'unconfirmed',
    parish: 'St. James',
    address: 'Jamestown Clinic Holetown, St. James',
    phone: '(246) 432-6997',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.181214, lon: -59.634549 },
  },
  {
    name: "Joe's Pharmacy",
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Oistins Main Road, Christ Church',
    phone: '(246) 428-6025',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.065204, lon: -59.544351 },
  },
  {
    name: 'Jones A P & Co Ltd',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Drug Store 8 High Street, St. Michael',
    phone: '(246) 426-3241',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.101667, lon: -59.611318 },
  },
  {
    name: 'K C B Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Brittons New Road Brittons Hill, St. Michael',
    phone: '(246) 426-7456',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.085751, lon: -59.591351 },
  },
  {
    name: "K O D's Pharmacy",
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Fontabelle, St. Michael',
    phone: '(246) 228-5087',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.106023, lon: -59.62467 },
  },
  {
    name: 'Maranatha Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Rock Dundo Medical Clinic White Main Road St Michael Tel/Fax',
    phone: '(246) 271-5736',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.099622, lon: -59.611827 },
  },
  {
    name: 'Maycare Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Philip',
    address: 'Emerald City Supermarket, Six Roads, St. Philip',
    phone: '(246) 423-4937',
    notes:
      'Directory listing says open until 10pm Mon–Sat — confirm by phone. Location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.119513, lon: -59.46114 },
  },
  {
    name: 'Mayfield Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Mayfield Medical Centre, 4th Avenue Belleville, St. Michael',
    phone: '(246) 427-6066',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.094231, lon: -59.603082 },
  },
  {
    name: "Neil's Pharmacy",
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Aberfoyle Black Rock, St. Michael',
    phone: '(246) 427-5762',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.098741, lon: -59.611061 },
  },
  {
    name: "O'Hana Pharmacy",
    type: 'unconfirmed',
    parish: 'St. Peter',
    address: 'Gills Terr Speightstown, St. Peter',
    phone: '(246) 422-1800',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.250727, lon: -59.641291 },
  },
  {
    name: "Pearson's Pharmacies",
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Upper Collymore Rock Road, St. Michael',
    phone: '(246) 427-5521',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.097887, lon: -59.609592 },
  },
  {
    name: 'Pharmaco',
    type: 'unconfirmed',
    parish: 'St. Peter',
    address: 'Church St Speightstown, St. Peter',
    phone: '(246) 422-1908',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.250617, lon: -59.640794 },
  },
  {
    name: 'Pickwick Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Peterkin Road Bank Hall, St. Michael',
    phone: '(246) 430-9594',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.110587, lon: -59.613429 },
  },
  {
    name: 'Pine Dispensary Inc',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Pine Medical Centre 3rd Avenue Belleville, St. Michael',
    phone: '(246) 436-8678',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.09825, lon: -59.608056 },
  },
  {
    name: 'Prescription Specialist Pharmacy The',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: '4th Avenue Belleville, St. Michael',
    phone: '(246) 437-3684',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.09502, lon: -59.601459 },
  },
  {
    name: 'Prescriptions Plus Inc',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Canary Lane Mall, St George Street, St. Michael',
    phone: '(246) 435-7587',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.097115, lon: -59.616704 },
  },
  {
    name: 'River Road Dispensary',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Glendor House River Road, St. Michael',
    phone: '(246) 429-4240',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.100779, lon: -59.607199 },
  },
  {
    name: 'Rock Dundo Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Cave Hill, St. Michael',
    phone: '(246) 425-1088',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.135653, lon: -59.627371 },
  },
  {
    name: 'Roebuck Pharmacy Ltd',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: '121 Roebuck, St. Michael',
    phone: '(246) 436-6101',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.103757, lon: -59.606956 },
  },
  {
    name: 'S E Well Care Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'ARS Medicare 6th Avenue Belleville, St. Michael',
    phone: '(246) 436-1099',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.102913, lon: -59.60927 },
  },
  {
    name: 'S K Total Health Pharmacy Inc',
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: "Rendezvous Court R'vous, Christ Church",
    phone: '(246) 436-0140',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.071846, lon: -59.539509 },
  },
  {
    name: 'Standard Pharmacy Ltd',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Corner of Fairfield Road Tweedside Road, St. Michael',
    phone: '(246) 429-3298',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.102549, lon: -59.610225 },
  },
  {
    name: 'Total Care Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: '23 Baxters Road Opp Jordans Supermarket, St. Michael',
    phone: '(246) 436-5241',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.102003, lon: -59.611109 },
  },
  {
    name: 'Walkers H C Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: '47 Tudor St',
    phone: '(246) 426-3707',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.101937, lon: -59.618601 },
  },
  {
    name: 'Weekes L A Drug Store',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Carlton Black Rock Main Road, St. Michael',
    phone: '(246) 425-1046',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.100388, lon: -59.612247 },
  },
  {
    name: 'Welches Dispensary',
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Welches, Christ Church',
    phone: '(246) 428-1206',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.065187, lon: -59.549856 },
  },
  {
    name: 'Whole Health Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Peter',
    address: 'Queen Saint Speightstown, St. Peter',
    phone: '(246) 422-5207',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.249468, lon: -59.64362 },
  },
  {
    name: "Worrell's Pharmacy Inc",
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Wildey Shopping Plaza, St. Michael',
    phone: '(246) 427-5468',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.09877, lon: -59.611737 },
  },
  {
    name: 'Worthing Pharmacy',
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Worthing, Christ Church',
    phone: '(246) 435-7041',
    notes:
      'From a Barbados business directory — location approximate and subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.071095, lon: -59.581476 },
  },
  {
    name: 'Massy Pharmacy — Warrens',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Warrens SuperCentre, St. Michael',
    phone: '',
    notes:
      'Massy Stores pharmacy (formerly Knights) — on the Drug Service subsidised list; pharmacy hours unconfirmed — call to confirm.',
    coords: { lat: 13.140182, lon: -59.60768 },
  },
  {
    name: 'Massy Pharmacy — Sky Mall',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Sky Mall, Haggatt Hall, St. Michael',
    phone: '',
    notes:
      'Massy Stores pharmacy (formerly Knights) — on the Drug Service subsidised list; pharmacy hours unconfirmed — call to confirm.',
    coords: { lat: 13.106699, lon: -59.577748 },
  },
  {
    name: 'Massy Pharmacy — Sunset Crest',
    type: 'private-sbs',
    parish: 'St. James',
    address: 'Sunset Crest, Holetown, St. James',
    phone: '',
    notes:
      'Massy Stores pharmacy (formerly Knights) — on the Drug Service subsidised list; pharmacy hours unconfirmed — call to confirm.',
    coords: { lat: 13.185508, lon: -59.637305 },
  },
  {
    name: 'Massy Pharmacy — Six Roads',
    type: 'private-sbs',
    parish: 'St. Philip',
    address: 'Six Roads, St. Philip',
    phone: '',
    notes:
      'Massy Stores pharmacy (formerly Knights) — on the Drug Service subsidised list; pharmacy hours unconfirmed — call to confirm.',
    coords: { lat: 13.117812, lon: -59.477786 },
  },
  {
    name: 'Massy Pharmacy — Worthing',
    type: 'private-sbs',
    parish: 'Christ Church',
    address: 'Rendezvous Road, Worthing, Christ Church',
    phone: '',
    notes:
      'Massy Stores pharmacy (formerly Knights) — on the Drug Service subsidised list; pharmacy hours unconfirmed — call to confirm.',
    coords: { lat: 13.073487, lon: -59.581698 },
  },
  {
    name: 'Massy Pharmacy — Oistins',
    type: 'private-sbs',
    parish: 'Christ Church',
    address: 'Oistins, Christ Church',
    phone: '',
    notes:
      'Massy Stores pharmacy (formerly Knights) — on the Drug Service subsidised list; pharmacy hours unconfirmed — call to confirm.',
    coords: { lat: 13.063301, lon: -59.542029 },
  },
  {
    name: 'Roundhay Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'One Accord Plaza, Warrens Industrial Park, St. Michael',
    phone: '',
    notes:
      'Warrens Healthcare complex. Subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.144871, lon: -59.604204 },
  },
  {
    name: 'iMart Pharmacy — Carlton Complex',
    type: 'private-sbs',
    parish: 'St. Michael',
    address: 'Carlton Complex, Black Rock, St. Michael',
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '08:00', closes: '17:00' }],
      tue: [{ opens: '08:00', closes: '17:00' }],
      wed: [{ opens: '08:00', closes: '17:00' }],
      thu: [{ opens: '08:00', closes: '17:00' }],
      fri: [{ opens: '08:00', closes: '17:00' }],
      sat: [{ opens: '08:00', closes: '17:00' }],
      sun: [],
    },
    notes: 'iMart Pharmacy Express, Carlton Complex. Hours per iMart.',
    coords: { lat: 13.122828, lon: -59.625611 },
  },
  {
    name: 'iMart Pharmacy — Sunset Crest Service Station',
    type: 'private-sbs',
    parish: 'St. James',
    address: 'Sunset Crest Service Station, Holetown, St. James',
    phone: '(246) 271-3784',
    hours: {
      mon: [{ opens: '09:00', closes: '18:00' }],
      tue: [{ opens: '09:00', closes: '18:00' }],
      wed: [{ opens: '09:00', closes: '18:00' }],
      thu: [{ opens: '09:00', closes: '18:00' }],
      fri: [{ opens: '09:00', closes: '18:00' }],
      sat: [{ opens: '09:00', closes: '18:00' }],
      sun: [],
    },
    notes:
      'iMart Pharmacy Express, Sunset Crest Service Station. Hours per iMart.',
    coords: { lat: 13.177244, lon: -59.638809 },
  },
  {
    name: 'Elbethel Pharmacy — 6th Avenue',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Corner 6th Avenue, Belleville, St. Michael',
    phone: '(246) 622-1405',
    notes:
      'Second Elbethel branch (Lloyd A Burrowes). Subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.096861, lon: -59.602114 },
  },
  {
    name: 'Aqua Pharmacy',
    type: 'unconfirmed',
    parish: 'Christ Church',
    address: 'Coral Sands Complex, Worthing, Christ Church',
    phone: '(246) 622-2782',
    hours: {
      mon: [{ opens: '08:30', closes: '17:00' }],
      tue: [{ opens: '08:30', closes: '17:00' }],
      wed: [{ opens: '08:30', closes: '17:00' }],
      thu: [{ opens: '08:30', closes: '17:00' }],
      fri: [{ opens: '08:30', closes: '17:00' }],
      sat: [{ opens: '09:00', closes: '14:00' }],
      sun: [],
    },
    notes:
      'Hours per Aqua Pharmacy. Subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.070148, lon: -59.579202 },
  },
  {
    name: 'BetterLife Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Building 2, 1 Friendship Drive, Green Hill, St. Michael',
    phone: '(246) 571-3788',
    notes: 'Subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.13687, lon: -59.605941 },
  },
  {
    name: 'Get Well Pharmacy',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address:
      'Windsor Medical Centre, cnr Government Hill & Pine Plantation Rd, St. Michael',
    phone: '(246) 622-4171',
    notes:
      'Retail counter at Windsor Medical Centre (also Wildey Industrial Estate). Confirm address and hours by phone. Subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.101385, lon: -59.591569 },
  },
  {
    name: 'City Pharmacy Inc',
    type: 'unconfirmed',
    parish: 'St. Michael',
    address: 'Marhill Street, Bridgetown, St. Michael',
    phone: '(246) 426-2454',
    notes: 'Subsidy status not confirmed with the Drug Service.',
    coords: { lat: 13.097765, lon: -59.613279 },
  },
  {
    name: 'Massy Pharmacy — Coverley',
    type: 'private-sbs',
    parish: 'Christ Church',
    address: 'The Villages at Coverley, Christ Church',
    phone: '(246) 623-7374',
    notes:
      'Massy Stores pharmacy (formerly Knights) — on the Drug Service subsidised list. Phone is the store line; pharmacy hours unconfirmed — call to confirm.',
    coords: { lat: 13.086209, lon: -59.501558 },
  },
]

export const PHARMACY_COUNT = PHARMACIES.length
