// Copied from ~/Code/gov-bb/packages/registry/src/components/{title,sex,parish,country,nationality,relationship,marital-status,primary-school,secondary-school,account-type}.ts.
// ponytail: these are copies; SSB's later edits arrive only when someone copies them again.

export const TITLES: [label: string, value: string][] = [
  ["Mr", "mr"],
  ["Miss", "miss"],
  ["Ms", "ms"],
  ["Mrs", "mrs"],
  ["Dr", "dr"],
];

export const SEXES: [label: string, value: string][] = [
  ["Male", "male"],
  ["Female", "female"],
];

export const PARISHES: [label: string, value: string][] = [
  ["Christ Church", "christ-church"],
  ["St. Andrew", "st-andrew"],
  ["St. George", "st-george"],
  ["St. James", "st-james"],
  ["St. John", "st-john"],
  ["St. Joseph", "st-joseph"],
  ["St. Lucy", "st-lucy"],
  ["St. Michael", "st-michael"],
  ["St. Peter", "st-peter"],
  ["St. Philip", "st-philip"],
  ["St. Thomas", "st-thomas"],
];

export const COUNTRIES: [label: string, value: string][] = [
  ["Barbados", "barbados"],
  ["Antigua and Barbuda", "antigua-and-barbuda"],
  ["Bahamas", "bahamas"],
  ["Belize", "belize"],
  ["Cuba", "cuba"],
  ["Dominica", "dominica"],
  ["Dominican Republic", "dominican-republic"],
  ["Grenada", "grenada"],
  ["Guyana", "guyana"],
  ["Haiti", "haiti"],
  ["Jamaica", "jamaica"],
  ["Saint Kitts and Nevis", "saint-kitts-and-nevis"],
  ["Saint Lucia", "saint-lucia"],
  ["Saint Vincent and the Grenadines", "saint-vincent-and-the-grenadines"],
  ["Suriname", "suriname"],
  ["Trinidad and Tobago", "trinidad-and-tobago"],
  ["Afghanistan", "afghanistan"],
  ["Albania", "albania"],
  ["Algeria", "algeria"],
  ["Andorra", "andorra"],
  ["Angola", "angola"],
  ["Argentina", "argentina"],
  ["Armenia", "armenia"],
  ["Australia", "australia"],
  ["Austria", "austria"],
  ["Azerbaijan", "azerbaijan"],
  ["Bangladesh", "bangladesh"],
  ["Belarus", "belarus"],
  ["Belgium", "belgium"],
  ["Bolivia", "bolivia"],
  ["Bosnia and Herzegovina", "bosnia-and-herzegovina"],
  ["Brazil", "brazil"],
  ["Bulgaria", "bulgaria"],
  ["Cambodia", "cambodia"],
  ["Cameroon", "cameroon"],
  ["Canada", "canada"],
  ["Chile", "chile"],
  ["China", "china"],
  ["Colombia", "colombia"],
  ["Costa Rica", "costa-rica"],
  ["Croatia", "croatia"],
  ["Czech Republic", "czech-republic"],
  ["Democratic Republic of the Congo", "dr-congo"],
  ["Denmark", "denmark"],
  ["Ecuador", "ecuador"],
  ["Egypt", "egypt"],
  ["Eritrea", "eritrea"],
  ["Estonia", "estonia"],
  ["Ethiopia", "ethiopia"],
  ["Finland", "finland"],
  ["France", "france"],
  ["Georgia", "georgia"],
  ["Germany", "germany"],
  ["Ghana", "ghana"],
  ["Greece", "greece"],
  ["Guatemala", "guatemala"],
  ["Honduras", "honduras"],
  ["Hungary", "hungary"],
  ["India", "india"],
  ["Indonesia", "indonesia"],
  ["Iran", "iran"],
  ["Iraq", "iraq"],
  ["Ireland", "ireland"],
  ["Israel", "israel"],
  ["Italy", "italy"],
  ["Japan", "japan"],
  ["Jordan", "jordan"],
  ["Kazakhstan", "kazakhstan"],
  ["Kenya", "kenya"],
  ["Kuwait", "kuwait"],
  ["Latvia", "latvia"],
  ["Lebanon", "lebanon"],
  ["Libya", "libya"],
  ["Lithuania", "lithuania"],
  ["Luxembourg", "luxembourg"],
  ["Malaysia", "malaysia"],
  ["Mexico", "mexico"],
  ["Moldova", "moldova"],
  ["Morocco", "morocco"],
  ["Mozambique", "mozambique"],
  ["Namibia", "namibia"],
  ["Nepal", "nepal"],
  ["Netherlands", "netherlands"],
  ["New Zealand", "new-zealand"],
  ["Nicaragua", "nicaragua"],
  ["Nigeria", "nigeria"],
  ["Norway", "norway"],
  ["Pakistan", "pakistan"],
  ["Panama", "panama"],
  ["Paraguay", "paraguay"],
  ["Peru", "peru"],
  ["Philippines", "philippines"],
  ["Poland", "poland"],
  ["Portugal", "portugal"],
  ["Romania", "romania"],
  ["Russia", "russia"],
  ["Saudi Arabia", "saudi-arabia"],
  ["Senegal", "senegal"],
  ["Serbia", "serbia"],
  ["Sierra Leone", "sierra-leone"],
  ["Singapore", "singapore"],
  ["Slovakia", "slovakia"],
  ["Somalia", "somalia"],
  ["South Africa", "south-africa"],
  ["South Korea", "south-korea"],
  ["Spain", "spain"],
  ["Sri Lanka", "sri-lanka"],
  ["Sudan", "sudan"],
  ["Sweden", "sweden"],
  ["Switzerland", "switzerland"],
  ["Syria", "syria"],
  ["Taiwan", "taiwan"],
  ["Tanzania", "tanzania"],
  ["Thailand", "thailand"],
  ["Tunisia", "tunisia"],
  ["Turkey", "turkey"],
  ["Uganda", "uganda"],
  ["Ukraine", "ukraine"],
  ["United Kingdom", "united-kingdom"],
  ["United States", "united-states"],
  ["Uruguay", "uruguay"],
  ["Uzbekistan", "uzbekistan"],
  ["Venezuela", "venezuela"],
  ["Vietnam", "vietnam"],
  ["Yemen", "yemen"],
  ["Zambia", "zambia"],
  ["Zimbabwe", "zimbabwe"],
  ["Other", "other"],
];

export const NATIONALITIES: [label: string, value: string][] = [
  ["Barbadian", "barbadian"],
  ["Antiguan and Barbudan", "antiguan-and-barbudan"],
  ["Bahamian", "bahamian"],
  ["Belizean", "belizean"],
  ["Cuban", "cuban"],
  ["Dominican", "dominican"],
  ["Grenadian", "grenadian"],
  ["Guyanese", "guyanese"],
  ["Haitian", "haitian"],
  ["Jamaican", "jamaican"],
  ["Kittsian and Nevisian", "kittsian-and-nevisian"],
  ["Saint Lucian", "saint-lucian"],
  ["Surinamese", "surinamese"],
  ["Trinidadian and Tobagonian", "trinidadian-and-tobagonian"],
  ["Vincentian", "vincentian"],
  ["Afghan", "afghan"],
  ["Albanian", "albanian"],
  ["Algerian", "algerian"],
  ["American", "american"],
  ["Andorran", "andorran"],
  ["Angolan", "angolan"],
  ["Argentine", "argentine"],
  ["Armenian", "armenian"],
  ["Australian", "australian"],
  ["Austrian", "austrian"],
  ["Azerbaijani", "azerbaijani"],
  ["Bangladeshi", "bangladeshi"],
  ["Belarusian", "belarusian"],
  ["Belgian", "belgian"],
  ["Bolivian", "bolivian"],
  ["Bosnian", "bosnian"],
  ["Brazilian", "brazilian"],
  ["British", "british"],
  ["Bulgarian", "bulgarian"],
  ["Cambodian", "cambodian"],
  ["Cameroonian", "cameroonian"],
  ["Canadian", "canadian"],
  ["Chilean", "chilean"],
  ["Chinese", "chinese"],
  ["Colombian", "colombian"],
  ["Congolese", "congolese"],
  ["Costa Rican", "costa-rican"],
  ["Croatian", "croatian"],
  ["Czech", "czech"],
  ["Danish", "danish"],
  ["Dutch", "dutch"],
  ["Ecuadorian", "ecuadorian"],
  ["Egyptian", "egyptian"],
  ["Eritrean", "eritrean"],
  ["Estonian", "estonian"],
  ["Ethiopian", "ethiopian"],
  ["Filipino", "filipino"],
  ["Finnish", "finnish"],
  ["French", "french"],
  ["Georgian", "georgian"],
  ["German", "german"],
  ["Ghanaian", "ghanaian"],
  ["Greek", "greek"],
  ["Guatemalan", "guatemalan"],
  ["Honduran", "honduran"],
  ["Hungarian", "hungarian"],
  ["Indian", "indian"],
  ["Indonesian", "indonesian"],
  ["Iranian", "iranian"],
  ["Iraqi", "iraqi"],
  ["Irish", "irish"],
  ["Israeli", "israeli"],
  ["Italian", "italian"],
  ["Ivorian", "ivorian"],
  ["Japanese", "japanese"],
  ["Jordanian", "jordanian"],
  ["Kazakhstani", "kazakhstani"],
  ["Kenyan", "kenyan"],
  ["Korean", "korean"],
  ["Kuwaiti", "kuwaiti"],
  ["Latvian", "latvian"],
  ["Lebanese", "lebanese"],
  ["Libyan", "libyan"],
  ["Lithuanian", "lithuanian"],
  ["Luxembourgish", "luxembourgish"],
  ["Malaysian", "malaysian"],
  ["Maldivian", "maldivian"],
  ["Mexican", "mexican"],
  ["Moldovan", "moldovan"],
  ["Moroccan", "moroccan"],
  ["Mozambican", "mozambican"],
  ["Myanmar", "myanmar"],
  ["Namibian", "namibian"],
  ["Nepalese", "nepalese"],
  ["New Zealander", "new-zealander"],
  ["Nicaraguan", "nicaraguan"],
  ["Nigerian", "nigerian"],
  ["Norwegian", "norwegian"],
  ["Pakistani", "pakistani"],
  ["Panamanian", "panamanian"],
  ["Paraguayan", "paraguayan"],
  ["Peruvian", "peruvian"],
  ["Polish", "polish"],
  ["Portuguese", "portuguese"],
  ["Romanian", "romanian"],
  ["Russian", "russian"],
  ["Saudi Arabian", "saudi-arabian"],
  ["Senegalese", "senegalese"],
  ["Serbian", "serbian"],
  ["Sierra Leonean", "sierra-leonean"],
  ["Singaporean", "singaporean"],
  ["Slovak", "slovak"],
  ["Somali", "somali"],
  ["South African", "south-african"],
  ["Spanish", "spanish"],
  ["Sri Lankan", "sri-lankan"],
  ["Sudanese", "sudanese"],
  ["Swedish", "swedish"],
  ["Swiss", "swiss"],
  ["Syrian", "syrian"],
  ["Taiwanese", "taiwanese"],
  ["Tanzanian", "tanzanian"],
  ["Thai", "thai"],
  ["Tunisian", "tunisian"],
  ["Turkish", "turkish"],
  ["Ugandan", "ugandan"],
  ["Ukrainian", "ukrainian"],
  ["Uruguayan", "uruguayan"],
  ["Uzbekistani", "uzbekistani"],
  ["Venezuelan", "venezuelan"],
  ["Vietnamese", "vietnamese"],
  ["Yemeni", "yemeni"],
  ["Zambian", "zambian"],
  ["Zimbabwean", "zimbabwean"],
  ["Other", "other"],
];

export const RELATIONSHIPS: [label: string, value: string][] = [
  ["Spouse", "spouse"],
  ["Parent", "parent"],
  ["Child", "child"],
  ["Sibling", "sibling"],
  ["Grandparent", "grandparent"],
  ["Grandchild", "grandchild"],
  ["Friend", "friend"],
  ["Colleague", "colleague"],
  ["Other", "other"],
];

export const MARITAL_STATUSES: [label: string, value: string][] = [
  ["Single", "single"],
  ["Married", "married"],
  ["Divorced", "divorced"],
];

export const PRIMARY_SCHOOLS: [label: string, value: string][] = [
  ["A Dacosta Edwards", "a-dacosta-edwards"],
  ["All Saints' Primary", "all-saints-primary"],
  ["Arthur Smith Primary", "arthur-smith-primary"],
  ["Bay Primary School", "bay-primary-school"],
  ["Bayley's Primary", "bayleys-primary"],
  ["Belmont Primary", "belmont-primary"],
  ["Blackman/Gollop Primary", "blackman-gollop-primary"],
  ["Charles F Broome", "charles-f-broome"],
  ["Christ Church Girls", "christ-church-girls"],
  ["Cuthbert Moore Primary", "cuthbert-moore-primary"],
  ["Deacons Primary", "deacons-primary"],
  ["Eagle Hall Primary", "eagle-hall-primary"],
  ["Eden Lodge", "eden-lodge"],
  ["Ellerton Primary", "ellerton-primary"],
  ["Elliot Belgrave", "elliot-belgrave"],
  ["Good Shepherd Primary", "good-shepherd-primary"],
  ["Gordon Greenidge Primary", "gordon-greenidge-primary"],
  ["Gordon Walters", "gordon-walters"],
  ["Grantley Prescod Memorial", "grantley-prescod-memorial"],
  ["Grazettes Primary", "grazettes-primary"],
  ["Half Moon Fort", "half-moon-fort"],
  ["Hilda Skeene Primary", "hilda-skeene-primary"],
  ["Hillaby Turner's Hall", "hillaby-turners-hall"],
  ["Hindsbury Primary", "hindsbury-primary"],
  ["Holy Innocents' Primary", "holy-innocents-primary"],
  ["Ignatius Byer Primary", "ignatius-byer-primary"],
  ["Lawrence T Gay", "lawrence-t-gay"],
  ["Luther Thorne Memorial", "luther-thorne-memorial"],
  ["Milton Lynch Primary", "milton-lynch-primary"],
  ["Mount Tabor Primary School", "mount-tabor-primary-school"],
  ["New Horizon Academy", "new-horizon-academy"],
  ["Reynold Weekes Primary School", "reynold-weekes-primary-school"],
  ["Roland Edwards Primary", "roland-edwards-primary"],
  ["Selah Primary School", "selah-primary-school"],
  ["Sharon Primary", "sharon-primary"],
  ["St. Albans Primary", "st-albans-primary"],
  ["St. Ambrose Primary", "st-ambrose-primary"],
  ["St. Bartholomew Primary", "st-bartholomew-primary"],
  ["St. Bernard's Primary", "st-bernards-primary"],
  ["St. Catherine's Primary", "st-catherines-primary"],
  ["St. Christopher Primary", "st-christopher-primary"],
  ["St. Elizabeth Primary", "st-elizabeth-primary"],
  ["St. George Primary", "st-george-primary"],
  ["St. Giles Primary", "st-giles-primary"],
  ["St. James Primary", "st-james-primary"],
  ["St. John's Primary", "st-johns-primary"],
  ["St. Joseph Primary", "st-joseph-primary"],
  ["St. Jude's Primary", "st-judes-primary"],
  ["St. Lawrence Primary", "st-lawrence-primary"],
  ["St. Lucy's Primary", "st-lucys-primary"],
  ["St. Lukes/Brighton Primary", "st-lukes-brighton-primary"],
  ["St. Margaret's Primary School", "st-margarets-primary-school"],
  ["St. Marks Primary", "st-marks-primary"],
  ["St. Martins Mangrove", "st-martins-mangrove"],
  ["St. Mary's Primary", "st-marys-primary"],
  ["St. Matthew's Primary", "st-matthews-primary"],
  ["St. Paul Primary", "st-paul-primary"],
  ["St. Philip Primary", "st-philip-primary"],
  ["St. Silas Primary", "st-silas-primary"],
  ["St. Stephen's Primary", "st-stephens-primary"],
  ["The Ann Hill School", "the-ann-hill-school"],
  ["The Irving Wilson School", "the-irving-wilson-school"],
  ["Vauxhall Primary", "vauxhall-primary"],
  ["Welches Primary", "welches-primary"],
  ["Wesley Hall Infants", "wesley-hall-infants"],
  ["Wesley Hall Junior", "wesley-hall-junior"],
  ["West Terrace", "west-terrace"],
  ["Westbury Primary", "westbury-primary"],
  ["Wilkie Cumberbatch", "wilkie-cumberbatch"],
  ["Workman's Primary", "workmans-primary"],
];

export const SECONDARY_SCHOOLS: [label: string, value: string][] = [
  ["Alexandra School", "alexandra-school"],
  ["Alleyne School", "alleyne-school"],
  ["Christ Church Foundation School", "christ-church-foundation-school"],
  ["Coleridge & Parry School", "coleridge-parry-school"],
  ["Combermere School", "combermere-school"],
  ["Daryll Jordan Secondary School", "daryll-jordan-secondary-school"],
  ["Deighton Griffith Secondary School", "deighton-griffith-secondary-school"],
  ["Ellerslie Secondary School", "ellerslie-secondary-school"],
  ["Grantley Adams Memorial School", "grantley-adams-memorial-school"],
  ["Graydon Sealy Secondary School", "graydon-sealy-secondary-school"],
  ["Harrison College", "harrison-college"],
  ["Parkinson Memorial Secondary School", "parkinson-memorial-secondary-school"],
  ["Princess Margaret Secondary School", "princess-margaret-secondary-school"],
  ["Queen's College", "queens-college"],
  ["Springer Memorial Secondary School", "springer-memorial-secondary-school"],
  ["The Frederick Smith Secondary School", "frederick-smith-secondary-school"],
  ["The Lester Vaughan School", "lester-vaughan-school"],
  ["The Lodge School", "lodge-school"],
  ["The St. George Secondary School", "st-george-secondary-school"],
  ["The St. Leonard's Boys' Secondary School", "st-leonards-boys-secondary-school"],
  ["The St. Michael School", "st-michael-school"],
];

export const ACCOUNT_TYPES: [label: string, value: string][] = [
  ["Checking", "checking"],
  ["Savings", "savings"],
  ["Business", "business"],
  ["Joint", "joint"],
];
